#line 2 "aggr_mtd.lex.c"

#line 4 "aggr_mtd.lex.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 33
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE aggr_mtdrestart(aggr_mtdin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int aggr_mtdleng;

extern FILE *aggr_mtdin, *aggr_mtdout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up aggr_mtdtext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up aggr_mtdtext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef unsigned int yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via aggr_mtdrestart()), so that the user can continue scanning by
	 * just pointing aggr_mtdin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when aggr_mtdtext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int aggr_mtdleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow aggr_mtdwrap()'s to do buffer switches
 * instead of setting up a fresh aggr_mtdin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void aggr_mtdrestart (FILE *input_file  );
void aggr_mtd_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE aggr_mtd_create_buffer (FILE *file,int size  );
void aggr_mtd_delete_buffer (YY_BUFFER_STATE b  );
void aggr_mtd_flush_buffer (YY_BUFFER_STATE b  );
void aggr_mtdpush_buffer_state (YY_BUFFER_STATE new_buffer  );
void aggr_mtdpop_buffer_state (void );

static void aggr_mtdensure_buffer_stack (void );
static void aggr_mtd_load_buffer_state (void );
static void aggr_mtd_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER aggr_mtd_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE aggr_mtd_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE aggr_mtd_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE aggr_mtd_scan_bytes (yyconst char *bytes,int len  );

void *aggr_mtdalloc (yy_size_t  );
void *aggr_mtdrealloc (void *,yy_size_t  );
void aggr_mtdfree (void *  );

#define yy_new_buffer aggr_mtd_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        aggr_mtdensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            aggr_mtd_create_buffer(aggr_mtdin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        aggr_mtdensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            aggr_mtd_create_buffer(aggr_mtdin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *aggr_mtdin = (FILE *) 0, *aggr_mtdout = (FILE *) 0;

typedef int yy_state_type;

extern int aggr_mtdlineno;

int aggr_mtdlineno = 1;

extern char *aggr_mtdtext;
#define yytext_ptr aggr_mtdtext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up aggr_mtdtext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	aggr_mtdleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 11
#define YY_END_OF_BUFFER 12
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[229] =
    {   0,
        0,    0,   12,   10,    1,    1,    1,   10,   10,   10,
       10,   10,    0,    0,    1,    1,    0,    0,    0,    0,
        5,    0,    0,    0,    6,    0,    8,    8,    8,    8,
        0,    0,    0,    0,    0,    0,    9,    9,    0,    0,
        0,    8,    8,    8,    8,    0,    0,    0,    0,    0,
        9,    7,    7,    7,    7,    0,    0,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    0,    0,    0,    0,
        0,    0,    9,    7,    7,    7,    7,    7,    7,    0,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    4,    0,    0,    0,    0,    0,    7,    7,    7,

        7,    7,    7,    0,    0,    0,    0,    8,    8,    8,
        8,    8,    0,    0,    2,    0,    0,    9,    9,    9,
        9,    0,    7,    7,    7,    7,    7,    7,    7,    0,
        0,    0,    0,    0,    8,    8,    0,    8,    8,    8,
        0,    3,    0,    9,    9,    0,    9,    9,    9,    9,
        0,    7,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    0,    7,    7,    7,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    0,

        0,    0,    0,    0,    0,    0,    9,    9,    9,    9,
        9,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        9,    9,    0,    9,    9,    9,    0,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    5,    1,    6,    7,    1,    8,    9,    9,
       10,   11,   12,   13,   14,   14,   14,   15,    1,    1,
        1,    1,    1,    1,   17,   18,   19,   20,   21,   22,
       22,   22,   23,   22,   22,   22,   22,   24,   25,   26,
       22,   27,   28,   29,   30,   22,   22,   31,   22,   22,
        1,    1,    1,    1,   16,    1,   17,   18,   19,   20,

       21,   22,   22,   22,   23,   22,   22,   22,   22,   24,
       25,   26,   22,   27,   28,   29,   30,   22,   22,   31,
       22,   22,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[32] =
    {   0,
        1,    1,    1,    2,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1
    } ;

static yyconst flex_int16_t yy_base[234] =
    {   0,
        0,   25,  504,  463,    3,    7,   10,   13,    1,   14,
       17,   18,  462,    5,   50,   53,   23,   62,   41,   44,
      425,   48,   28,   61,  345,   79,   82,   93,  103,  110,
       42,   66,   70,  106,  117,  134,  273,  114,  144,  121,
      154,  161,  168,  175,  182,  178,  113,  180,  263,  181,
        0,  199,  200,  210,  217,   81,  110,   49,  223,  230,
      237,  242,  249,  256,  263,  136,  186,  182,  261,  262,
      264,  111,  278,  185,  266,  287,  294,  301,  308,  313,
      320,  327,  334,  341,  346,  351,  356,  361,  366,  370,
      380,  184,  267,  265,  378,  390,  179,  364,  397,  404,

      411,  418,  374,  426,  437,  444,  451,  456,  463,  473,
      480,  427,  487,  494,  143,  377,  511,  514,  525,  533,
      540,  340,  502,  430,  515,  545,  548,  551,  142,  558,
      565,  572,  579,  586,  591,  594,  600,  608,  611,  614,
      498,  109,  628,   78,  492,  638,  645,  652,  659,  666,
       75,  671,  597,  678,  685,  692,  697,  704,  711,  718,
      628,  617,  624,  725,  733,  740,  745,  752,  759,  766,
      773,  767,  788,  795,  802,  807,  814,  821,  828,  778,
      833,  838,  843,  848,  852,  862,  868,  876,  883,  890,
      897,  856,  869,  902,  907,  912,  916,  926,  924,  934,

      941,  951,  958,  783,  965,  972,  982,  989,  999, 1006,
      919, 1013, 1020,  977, 1025, 1033, 1041, 1044, 1047,  837,
     1054, 1057, 1063, 1071, 1074, 1077,  923, 1094, 1091,   35,
       18,   15,    0
    } ;

static yyconst flex_int16_t yy_def[234] =
    {   0,
      229,  229,  228,  230,  230,  230,  228,  230,  230,  230,
      230,  230,  230,  230,  230,  228,  230,  230,  230,  230,
      230,  230,  230,  230,  230,  231,  230,  230,   28,   29,
      230,  230,  230,  230,  230,  231,   36,   36,  230,  230,
       39,   29,   29,   29,   44,  230,  230,  230,  230,  230,
       36,  232,  232,   53,   54,  230,  230,  230,   44,   59,
       60,   44,   44,   44,   44,   65,  230,  230,  230,  230,
      230,  230,   36,  232,  232,   54,   54,   54,   78,   18,
       60,   60,   60,   83,   65,   65,   65,   65,   65,  230,
       89,  230,  230,  230,  230,   18,  230,  232,   78,   78,

       78,   78,  102,  230,   89,  105,  106,   83,   83,   83,
       83,  111,   39,  230,  230,  230,  233,  230,   39,  119,
      120,  230,  232,  102,  102,  102,  102,  102,  232,   39,
      106,  106,  106,  133,  111,  111,  111,  111,  111,  111,
      230,  230,  233,  143,  143,   39,  120,  120,  120,  149,
      230,  102,  230,  111,  111,  155,  133,  133,  133,  133,
      160,  143,  230,  155,  164,  165,  149,  149,  149,  149,
      170,  230,  102,  102,  174,  155,  155,  155,  178,  160,
      160,  160,  160,  160,  230,  184,  143,  165,  165,  165,
      190,  170,  170,  170,  170,  170,  230,  196,  230,  178,

      178,  178,  178,  203,   39,  230,  190,  190,  190,  190,
      210,   39,  230,  203,  203,  203,  203,  203,  203,  230,
      210,  210,  210,  210,  210,  210,  230,    0,  228,  228,
      228,  228,  228
    } ;

static yyconst flex_int16_t yy_nxt[1126] =
    {   0,
      144,    5,    6,    7,   15,   15,   16,   73,   15,   15,
       16,   16,   16,   16,   50,   74,    8,   14,   37,   14,
        9,   14,   10,   14,   11,   12,    5,    6,    7,   14,
       14,   19,   24,   14,   14,   13,   17,   20,   23,   14,
       18,    8,   25,   21,   14,    9,   22,   10,   34,   11,
       12,   15,   15,   16,   16,   16,   16,   14,   14,   31,
       14,   32,   46,   40,   14,   14,   14,   26,   35,   27,
       28,   28,   28,   28,   29,   30,   33,   14,   14,   13,
       13,   13,   14,   13,   36,   13,   14,   48,   39,   35,
       47,  172,   50,   13,   36,   38,   40,   14,   14,   41,

       42,   42,   42,   42,   42,   42,   42,   40,   80,   14,
       43,   43,   43,   43,   44,   45,   45,   45,   45,   45,
       45,   45,   14,   39,   35,   14,   14,   14,   50,   14,
       23,   97,   49,   14,   13,   13,   13,   56,   13,   36,
       13,   51,   68,   90,   90,   90,   57,   90,   13,   36,
       38,   52,   53,   53,   53,   53,   54,   55,   75,   14,
       14,   58,   59,   59,   59,   59,   60,   61,   62,   62,
       62,   62,   62,   62,   62,   63,   63,   63,   63,   63,
       63,   63,   64,   64,   64,   64,   65,   66,   66,   66,
       66,   66,   66,   66,   14,   14,   14,   71,   14,  122,

       14,   75,   14,   67,   69,   93,   72,   76,   76,   76,
       76,   76,   76,   76,   92,   75,   75,   77,   77,   77,
       77,   78,   79,   79,   79,   79,   79,   79,   79,   13,
       81,   81,   81,   81,   81,   81,   81,   82,   82,   82,
       82,   83,   84,   84,   84,   84,   84,   84,   84,   85,
       85,   85,   85,   85,   85,   85,   86,   86,   86,   86,
       86,   86,   86,   87,   87,   87,   87,   87,   87,   87,
       88,   88,   89,   90,   91,   90,   90,   14,   14,   70,
       14,   14,   75,   14,   39,   73,  115,   50,  116,   95,
       94,   96,   50,   98,   99,   99,   99,   99,   99,   99,

       99,  100,  100,  100,  100,  100,  100,  100,  101,  101,
      101,  101,  102,  103,  103,  103,  103,  103,  103,  103,
      104,  105,  105,  105,  105,  106,  107,  108,  108,  108,
      108,  108,  108,  108,  109,  109,  109,  109,  109,  109,
      109,  110,  110,  110,  110,  111,  112,  112,  112,  112,
      112,  112,  112,   90,   90,   90,   14,   90,   90,   90,
       90,   14,   90,   90,   90,   90,  151,   90,   90,   90,
       90,  123,   90,   90,   90,   90,   41,   90,   13,   13,
       75,  129,  129,  129,   40,   35,   14,  113,  113,   13,
       13,  114,   40,   14,   14,  117,  142,  118,  119,  119,

      119,  119,  120,  121,  124,  124,  124,  124,  124,  124,
      124,  125,  125,  125,  125,  125,  125,  125,  126,  126,
      126,  126,  126,  126,  126,  127,  127,  128,  129,  129,
      129,  129,   39,   35,   58,   58,   58,  129,  129,  129,
       40,   14,   14,  130,  131,  131,  131,  131,  131,  131,
      131,  132,  132,  132,  132,  133,  134,  134,  134,  134,
      134,  134,  134,  135,  135,  135,  135,  135,  135,  135,
      136,  136,  136,  136,  136,  136,  136,  137,   14,   14,
      138,  138,  138,  138,  138,  138,  138,  139,  139,  140,
       58,   58,   58,   58,  141,  141,  141,  141,  141,  141,

      141,  113,  113,  228,   41,  114,   50,  228,  152,  123,
       14,   13,   13,   13,   14,   13,  143,   13,   75,  162,
       39,   35,  129,  129,  129,   13,  143,  145,   50,  228,
       14,  146,  147,  147,  147,  147,  147,  147,  147,   50,
      148,  148,  148,  148,  149,  150,  150,  150,  150,  150,
      150,  150,  129,  129,  129,  129,  129,  129,  129,  129,
      129,  228,  228,   74,   74,  153,  154,  154,  154,  154,
      155,  156,  157,  157,  157,  157,  157,  157,  157,  158,
      158,  158,  158,  158,  158,  158,  159,  159,  159,  159,
      160,  161,  161,  161,  161,  161,  161,  161,   58,   58,

       58,   58,   58,   58,   58,  228,  228,   58,   58,   58,
      228,   40,   58,   14,   13,   58,   58,   58,   58,   58,
       58,   58,   58,   58,  187,  228,   13,   13,   13,   13,
       13,   50,   13,  143,   13,  185,  185,  185,   50,  185,
       14,  228,   13,  143,  145,  163,  164,  164,  164,  164,
      165,  166,  167,  167,  167,  167,  167,  167,  167,  168,
      168,  168,  168,  168,  168,  168,  169,  169,  169,  169,
      170,  171,  171,  171,  171,  171,  171,  171,  129,  173,
      173,  173,  173,  174,  175,  176,  176,  176,  176,  176,
      176,  176,  177,  177,  177,  177,  178,  179,  179,  179,

      179,  179,  179,  179,  180,  180,  180,  180,  180,  180,
      180,  181,  181,  181,  181,  181,  181,  181,  182,  182,
      182,  182,  182,  182,  182,  183,  183,  184,  185,  186,
      185,  185,  188,  188,  188,  188,  188,  188,  188,   50,
      189,  189,  189,  189,  190,  191,  191,  191,  191,  191,
      191,  191,  192,  192,  192,  192,  192,  192,  192,  193,
      193,  193,  193,  193,  193,  193,  194,  194,  194,  194,
      194,  194,  194,  195,  195,  196,  197,  198,  197,  197,
      197,  197,  197,   14,  197,  185,  185,  185,  228,  185,
      153,  153,  153,  228,  199,   76,   76,   76,   76,   76,

       76,   76,   77,   77,   77,   77,   78,   79,   79,   79,
       79,   79,   79,   79,  200,  200,  200,  200,  200,  200,
      200,  201,  201,  201,  201,  201,  201,  201,  202,  202,
      202,  202,  203,  204,  204,  204,  204,  204,  204,  204,
      185,  185,  185,  130,  185,  185,  185,  185,  228,  185,
      185,  185,  185,   14,  185,  185,  185,  185,  130,  185,
       13,   13,  228,  197,  197,  197,   40,  197,   14,  205,
      205,   13,   13,  206,   39,  187,  197,  197,  197,  228,
      197,  228,   50,  207,  207,  207,  207,  207,  207,  207,
      208,  208,  208,  208,  208,  208,  208,  209,  209,  209,

      209,  210,  211,  211,  211,  211,  211,  211,  211,  197,
      197,  197,  228,  197,  197,  197,  197,  228,  197,  197,
      197,  197,  146,  197,   13,   13,  163,  163,  163,  146,
       50,   35,   14,  212,  212,   13,   13,  213,   50,   14,
       14,  214,  214,  214,  214,  214,  214,  214,  215,  215,
      215,  215,  215,  215,  215,  216,  228,  228,  217,  217,
      217,  217,  217,  217,  217,  218,  218,  219,  153,  153,
      153,  153,  220,  220,  220,  220,  220,  220,  220,  205,
      205,  228,  228,  206,  153,  153,  153,  228,   14,  221,
      221,  221,  221,  221,  221,  221,  222,  222,  222,  222,

      222,  222,  222,  223,  228,  228,  224,  224,  224,  224,
      224,  224,  224,  225,  225,  226,  163,  163,  163,  163,
      227,  227,  227,  227,  227,  227,  227,  212,  212,  228,
      228,  213,  153,  153,  153,  228,   14,  153,  228,  228,
      153,  153,  153,  228,  228,  153,  228,   13,  153,  153,
      153,  153,  153,  153,  153,  153,  153,  228,  228,   13,
       13,  163,  163,  163,  163,  163,  163,  163,  228,  228,
      163,  163,  163,  228,  228,  163,  228,   13,  163,  163,
      163,  163,  163,  163,  163,  163,  163,  228,  228,   13,
       13,    4,    4,    3,  228,  228,  228,  228,  228,  228,

      228,  228,  228,  228,  228,  228,  228,  228,  228,  228,
      228,  228,  228,  228,  228,  228,  228,  228,  228,  228,
      228,  228,  228,  228,  228
    } ;

static yyconst flex_int16_t yy_chk[1126] =
    {   0,
      233,    1,    1,    1,    5,    5,    5,   51,    6,    6,
        6,    7,    7,    7,   51,  232,    1,    9,  231,    5,
        1,   14,    1,    6,    1,    1,    2,    2,    2,    8,
       10,    9,   14,   11,   12,  230,    8,   10,   12,   17,
        8,    2,   17,   11,   23,    2,   11,    2,   23,    2,
        2,   15,   15,   15,   16,   16,   16,   19,   31,   19,
       20,   20,   31,   58,   22,   58,   15,   18,   24,   18,
       18,   18,   18,   18,   18,   18,   22,   24,   18,   26,
       26,   26,   32,   26,   26,   26,   33,   33,   27,   27,
       32,  151,  144,   26,   26,   26,   27,   56,   27,   28,

       28,   28,   28,   28,   28,   28,   28,   28,   56,   28,
       29,   29,   29,   29,   29,   29,   29,   30,   30,   30,
       30,   30,   34,   35,   35,  142,   57,   72,   38,   47,
       57,   72,   34,   35,   36,   36,   36,   40,   36,   36,
       36,   38,   47,   66,   66,   66,   40,   66,   36,   36,
       36,   39,   39,   39,   39,   39,   39,   39,  129,  115,
       39,   41,   41,   41,   41,   41,   41,   41,   42,   42,
       42,   42,   42,   42,   42,   43,   43,   43,   43,   43,
       43,   43,   44,   44,   44,   44,   44,   44,   44,   45,
       45,   45,   45,   45,   46,   97,   48,   50,   68,   97,

       92,   74,   67,   46,   48,   68,   50,   53,   53,   53,
       53,   53,   53,   53,   67,   52,   53,   54,   54,   54,
       54,   54,   54,   54,   55,   55,   55,   55,   55,   59,
       59,   59,   59,   59,   59,   59,   59,   60,   60,   60,
       60,   60,   60,   60,   61,   61,   61,   61,   61,   62,
       62,   62,   62,   62,   62,   62,   63,   63,   63,   63,
       63,   63,   63,   64,   64,   64,   64,   64,   64,   64,
       65,   65,   65,   65,   65,   65,   65,   69,   70,   49,
       71,   94,   75,   93,   73,   73,   93,   37,   94,   70,
       69,   71,   73,   75,   76,   76,   76,   76,   76,   76,

       76,   77,   77,   77,   77,   77,   77,   77,   78,   78,
       78,   78,   78,   78,   78,   79,   79,   79,   79,   79,
       80,   80,   80,   80,   80,   80,   80,   81,   81,   81,
       81,   81,   81,   81,   82,   82,   82,   82,   82,   82,
       82,   83,   83,   83,   83,   83,   83,   83,   84,   84,
       84,   84,   84,   85,   85,   85,  122,   85,   86,   86,
       86,   25,   86,   87,   87,   87,  122,   87,   88,   88,
       88,   98,   88,   89,   89,   89,   90,   89,   89,   89,
       98,  103,  103,  103,   90,   95,   90,   91,   91,   91,
       91,   91,   95,  116,   95,   96,  116,   96,   96,   96,

       96,   96,   96,   96,   99,   99,   99,   99,   99,   99,
       99,  100,  100,  100,  100,  100,  100,  100,  101,  101,
      101,  101,  101,  101,  101,  102,  102,  102,  102,  102,
      102,  102,  104,  104,  112,  112,  112,  124,  124,  124,
      104,   21,  104,  105,  105,  105,  105,  105,  105,  105,
      105,  106,  106,  106,  106,  106,  106,  106,  107,  107,
      107,  107,  107,  108,  108,  108,  108,  108,  108,  108,
      109,  109,  109,  109,  109,  109,  109,  110,   13,    4,
      110,  110,  110,  110,  110,  110,  110,  111,  111,  111,
      111,  111,  111,  111,  113,  113,  113,  113,  113,  113,

      113,  114,  114,    3,  141,  114,  145,    0,  123,  123,
      114,  117,  117,  117,  141,  117,  117,  117,  123,  145,
      118,  118,  125,  125,  125,  117,  117,  117,  118,    0,
      118,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      120,  120,  120,  120,  120,  120,  120,  121,  121,  121,
      121,  121,  126,  126,  126,  127,  127,  127,  128,  128,
      128,    0,    0,  128,  128,  130,  130,  130,  130,  130,
      130,  130,  131,  131,  131,  131,  131,  131,  131,  132,
      132,  132,  132,  132,  132,  132,  133,  133,  133,  133,
      133,  133,  133,  134,  134,  134,  134,  134,  135,  135,

      135,  136,  136,  136,  137,    0,    0,  137,  137,  137,
        0,  153,  138,  153,  137,  138,  138,  138,  139,  139,
      139,  140,  140,  140,  162,    0,  140,  140,  143,  143,
      143,  162,  143,  143,  143,  161,  161,  161,  163,  161,
      163,    0,  143,  143,  143,  146,  146,  146,  146,  146,
      146,  146,  147,  147,  147,  147,  147,  147,  147,  148,
      148,  148,  148,  148,  148,  148,  149,  149,  149,  149,
      149,  149,  149,  150,  150,  150,  150,  150,  152,  152,
      152,  152,  152,  152,  152,  154,  154,  154,  154,  154,
      154,  154,  155,  155,  155,  155,  155,  155,  155,  156,

      156,  156,  156,  156,  157,  157,  157,  157,  157,  157,
      157,  158,  158,  158,  158,  158,  158,  158,  159,  159,
      159,  159,  159,  159,  159,  160,  160,  160,  160,  160,
      160,  160,  164,  164,  164,  164,  164,  164,  164,  164,
      165,  165,  165,  165,  165,  165,  165,  166,  166,  166,
      166,  166,  167,  167,  167,  167,  167,  167,  167,  168,
      168,  168,  168,  168,  168,  168,  169,  169,  169,  169,
      169,  169,  169,  170,  170,  170,  170,  170,  170,  170,
      171,  171,  171,  172,  171,  180,  180,  180,    0,  180,
      204,  204,  204,    0,  172,  173,  173,  173,  173,  173,

      173,  173,  174,  174,  174,  174,  174,  174,  174,  175,
      175,  175,  175,  175,  176,  176,  176,  176,  176,  176,
      176,  177,  177,  177,  177,  177,  177,  177,  178,  178,
      178,  178,  178,  178,  178,  179,  179,  179,  179,  179,
      181,  181,  181,  220,  181,  182,  182,  182,    0,  182,
      183,  183,  183,  220,  183,  184,  184,  184,  185,  184,
      184,  184,    0,  192,  192,  192,  185,  192,  185,  186,
      186,  186,  186,  186,  187,  187,  193,  193,  193,    0,
      193,    0,  187,  188,  188,  188,  188,  188,  188,  188,
      189,  189,  189,  189,  189,  189,  189,  190,  190,  190,

      190,  190,  190,  190,  191,  191,  191,  191,  191,  194,
      194,  194,    0,  194,  195,  195,  195,    0,  195,  196,
      196,  196,  197,  196,  196,  196,  211,  211,  211,  227,
      197,  199,  197,  198,  198,  198,  198,  198,  199,  227,
      199,  200,  200,  200,  200,  200,  200,  200,  201,  201,
      201,  201,  201,  201,  201,  202,    0,    0,  202,  202,
      202,  202,  202,  202,  202,  203,  203,  203,  203,  203,
      203,  203,  205,  205,  205,  205,  205,  205,  205,  206,
      206,    0,    0,  206,  214,  214,  214,    0,  206,  207,
      207,  207,  207,  207,  207,  207,  208,  208,  208,  208,

      208,  208,  208,  209,    0,    0,  209,  209,  209,  209,
      209,  209,  209,  210,  210,  210,  210,  210,  210,  210,
      212,  212,  212,  212,  212,  212,  212,  213,  213,    0,
        0,  213,  215,  215,  215,    0,  213,  216,    0,    0,
      216,  216,  216,    0,    0,  217,    0,  216,  217,  217,
      217,  218,  218,  218,  219,  219,  219,    0,    0,  219,
      219,  221,  221,  221,  222,  222,  222,  223,    0,    0,
      223,  223,  223,    0,    0,  224,    0,  223,  224,  224,
      224,  225,  225,  225,  226,  226,  226,    0,    0,  226,
      226,  229,  229,  228,  228,  228,  228,  228,  228,  228,

      228,  228,  228,  228,  228,  228,  228,  228,  228,  228,
      228,  228,  228,  228,  228,  228,  228,  228,  228,  228,
      228,  228,  228,  228,  228
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int aggr_mtd_flex_debug;
int aggr_mtd_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *aggr_mtdtext;
#line 1 "aggr_mtd.l"
#line 2 "aggr_mtd.l"
/*
  filename: aggr_mtd.l

  description:
    Defines the tokenizer for an RPSL aggr-mtd attribute.  It was mostly
    stolen from the IRRToolSet, simplified by removing ability to parse
    things defined by a dictionary (we use XML for extensibility rather
    than a dictionary).

  notes:
    Tokens are defined in the associated grammar, aggr_mtd.y.

  $Id: aggr_mtd.l,v 1.1.14.1 2006/09/29 12:32:29 katie Exp $
*/
#line 26 "aggr_mtd.l"
#include <stdlib.h>
#include <ctype.h>

/* tokens defined in the grammar */
#include "aggr_mtd.tab.h"

void syntax_error(char *fmt, ...);
void yy_input(char *buf, int *result, int max_size);
#undef YY_INPUT
#define YY_INPUT(buf,result,max_size) yy_input(buf,&result,max_size)
#line 803 "aggr_mtd.lex.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int aggr_mtdwrap (void );
#else
extern int aggr_mtdwrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( aggr_mtdtext, aggr_mtdleng, 1, aggr_mtdout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( aggr_mtdin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( aggr_mtdin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, aggr_mtdin))==0 && ferror(aggr_mtdin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(aggr_mtdin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int aggr_mtdlex (void);

#define YY_DECL int aggr_mtdlex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after aggr_mtdtext and aggr_mtdleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 38 "aggr_mtd.l"


#line 959 "aggr_mtd.lex.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! aggr_mtdin )
			aggr_mtdin = stdin;

		if ( ! aggr_mtdout )
			aggr_mtdout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			aggr_mtdensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				aggr_mtd_create_buffer(aggr_mtdin,YY_BUF_SIZE );
		}

		aggr_mtd_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of aggr_mtdtext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 229 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1094 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 40 "aggr_mtd.l"
{ ; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 42 "aggr_mtd.l"
{ return KEYW_INBOUND; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 43 "aggr_mtd.l"
{ return KEYW_OUTBOUND; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 44 "aggr_mtd.l"
{ return KEYW_EXCEPT; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 46 "aggr_mtd.l"
{ return OP_OR; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 47 "aggr_mtd.l"
{ return OP_AND; }
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 49 "aggr_mtd.l"
{
    syntax_error("The RIPE Database currently represents 16-bit AS numbers in \'ASn\' notation");
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 53 "aggr_mtd.l"
{
    return TKN_ASNO;
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 57 "aggr_mtd.l"
{
    return TKN_ASNAME;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 61 "aggr_mtd.l"
{ return aggr_mtdtext[0]; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 63 "aggr_mtd.l"
ECHO;
	YY_BREAK
#line 1105 "aggr_mtd.lex.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed aggr_mtdin at a new source and called
			 * aggr_mtdlex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = aggr_mtdin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( aggr_mtdwrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * aggr_mtdtext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of aggr_mtdlex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					aggr_mtdrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			aggr_mtdrestart(aggr_mtdin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 229 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 229 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 228);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up aggr_mtdtext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					aggr_mtdrestart(aggr_mtdin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( aggr_mtdwrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve aggr_mtdtext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void aggr_mtdrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        aggr_mtdensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            aggr_mtd_create_buffer(aggr_mtdin,YY_BUF_SIZE );
	}

	aggr_mtd_init_buffer(YY_CURRENT_BUFFER,input_file );
	aggr_mtd_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void aggr_mtd_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		aggr_mtdpop_buffer_state();
	 *		aggr_mtdpush_buffer_state(new_buffer);
     */
	aggr_mtdensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	aggr_mtd_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (aggr_mtdwrap()) processing, but the only time this flag
	 * is looked at is after aggr_mtdwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void aggr_mtd_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	aggr_mtdin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE aggr_mtd_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) aggr_mtdalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in aggr_mtd_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) aggr_mtdalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in aggr_mtd_create_buffer()" );

	b->yy_is_our_buffer = 1;

	aggr_mtd_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with aggr_mtd_create_buffer()
 * 
 */
    void aggr_mtd_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		aggr_mtdfree((void *) b->yy_ch_buf  );

	aggr_mtdfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a aggr_mtdrestart() or at EOF.
 */
    static void aggr_mtd_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	aggr_mtd_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then aggr_mtd_init_buffer was _probably_
     * called from aggr_mtdrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void aggr_mtd_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		aggr_mtd_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void aggr_mtdpush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	aggr_mtdensure_buffer_stack();

	/* This block is copied from aggr_mtd_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from aggr_mtd_switch_to_buffer. */
	aggr_mtd_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void aggr_mtdpop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	aggr_mtd_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		aggr_mtd_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void aggr_mtdensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)aggr_mtdalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)aggr_mtdrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE aggr_mtd_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) aggr_mtdalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in aggr_mtd_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	aggr_mtd_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to aggr_mtdlex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       aggr_mtd_scan_bytes() instead.
 */
YY_BUFFER_STATE aggr_mtd_scan_string (yyconst char * yystr )
{
    
	return aggr_mtd_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to aggr_mtdlex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE aggr_mtd_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) aggr_mtdalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in aggr_mtd_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = aggr_mtd_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in aggr_mtd_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up aggr_mtdtext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		aggr_mtdtext[aggr_mtdleng] = (yy_hold_char); \
		(yy_c_buf_p) = aggr_mtdtext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		aggr_mtdleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int aggr_mtdget_lineno  (void)
{
        
    return aggr_mtdlineno;
}

/** Get the input stream.
 * 
 */
FILE *aggr_mtdget_in  (void)
{
        return aggr_mtdin;
}

/** Get the output stream.
 * 
 */
FILE *aggr_mtdget_out  (void)
{
        return aggr_mtdout;
}

/** Get the length of the current token.
 * 
 */
int aggr_mtdget_leng  (void)
{
        return aggr_mtdleng;
}

/** Get the current token.
 * 
 */

char *aggr_mtdget_text  (void)
{
        return aggr_mtdtext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void aggr_mtdset_lineno (int  line_number )
{
    
    aggr_mtdlineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see aggr_mtd_switch_to_buffer
 */
void aggr_mtdset_in (FILE *  in_str )
{
        aggr_mtdin = in_str ;
}

void aggr_mtdset_out (FILE *  out_str )
{
        aggr_mtdout = out_str ;
}

int aggr_mtdget_debug  (void)
{
        return aggr_mtd_flex_debug;
}

void aggr_mtdset_debug (int  bdebug )
{
        aggr_mtd_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from aggr_mtdlex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    aggr_mtdin = stdin;
    aggr_mtdout = stdout;
#else
    aggr_mtdin = (FILE *) 0;
    aggr_mtdout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * aggr_mtdlex_init()
     */
    return 0;
}

/* aggr_mtdlex_destroy is for both reentrant and non-reentrant scanners. */
int aggr_mtdlex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		aggr_mtd_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		aggr_mtdpop_buffer_state();
	}

	/* Destroy the stack itself. */
	aggr_mtdfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * aggr_mtdlex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *aggr_mtdalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *aggr_mtdrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void aggr_mtdfree (void * ptr )
{
	free( (char *) ptr );	/* see aggr_mtdrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 63 "aggr_mtd.l"



void
aggr_mtd_reset ()
{
    aggr_mtd_flush_buffer(YY_CURRENT_BUFFER);
}


int
aggr_mtdwrap()
{
    return 1;
}


