#define yy_create_buffer components_r6_create_buffer
#define yy_delete_buffer components_r6_delete_buffer
#define yy_scan_buffer components_r6_scan_buffer
#define yy_scan_string components_r6_scan_string
#define yy_scan_bytes components_r6_scan_bytes
#define yy_flex_debug components_r6_flex_debug
#define yy_init_buffer components_r6_init_buffer
#define yy_flush_buffer components_r6_flush_buffer
#define yy_load_buffer_state components_r6_load_buffer_state
#define yy_switch_to_buffer components_r6_switch_to_buffer
#define yyin components_r6in
#define yyleng components_r6leng
#define yylex components_r6lex
#define yyout components_r6out
#define yyrestart components_r6restart
#define yytext components_r6text
#define yywrap components_r6wrap

#line 20 "components_r6.lex.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 51
#define YY_END_OF_BUFFER 52
static yyconst short int yy_accept[447] =
    {   0,
        0,    0,   52,   50,    1,    1,   50,   49,   50,    5,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   50,    1,    7,    0,   49,
        0,    0,    0,    6,    9,    8,   10,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    2,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   31,   32,    0,
        0,   49,    0,   48,    0,    0,    0,    0,    3,   13,
        0,    0,   38,   38,   38,    0,    0,    0,   37,    0,
        0,    0,    0,   26,    0,    0,    0,    0,    0,    0,

       25,    0,    0,    0,    0,    4,    0,    0,    0,    0,
        0,   37,    0,    0,    0,    0,    0,   49,    0,   48,
        0,    0,   44,    0,    0,   11,    0,    0,   40,   38,
        0,   38,   38,   38,    0,    0,    0,    0,   30,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   24,    0,    0,    0,    0,   41,   16,    0,
        0,    0,   49,   48,    0,    0,    0,    0,    0,    0,
        0,   38,    0,    0,    0,    0,   38,   38,   38,   38,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   33,

        0,    0,   48,    0,    0,    0,   47,   47,    0,    0,
        0,   18,    0,    0,   38,    0,    0,   38,   38,   38,
       38,   38,   27,   12,    0,    0,   19,    0,   39,    0,
        0,    0,    0,    0,   14,    0,    0,    0,    0,    0,
        0,   35,    0,   48,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   17,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   47,    0,    0,    0,    0,   40,   40,
       40,    0,    0,    0,    0,    0,    0,    0,   20,    0,
        0,    0,   15,   21,   29,    0,    0,   36,   41,   41,

       41,    0,    0,    0,   42,    0,    0,    0,    0,    0,
       40,   40,   40,   40,   40,    0,    0,    0,    0,    0,
        0,    0,   28,    0,    0,    0,    0,   22,   41,   41,
       41,   41,    0,    0,   41,   34,    0,    0,    0,    0,
        0,    0,    0,   40,   40,   40,   40,   40,    0,    0,
        0,    0,    0,    0,    0,   39,   39,   39,    0,    0,
        0,   41,   41,   41,   41,   41,    0,   45,   45,    0,
        0,    0,    0,   40,   40,   40,   40,   40,   40,   39,
       39,   39,   39,    0,    0,    0,   41,   41,   41,   41,
       41,   41,    0,    0,    0,    0,    0,    0,    0,   39,

       39,   39,   39,   39,    0,    0,   23,   45,    0,    0,
        0,    0,   39,   39,   39,   39,   39,   39,    0,   39,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   43,    0,    0,    0,    0,
        0,   46,   46,    0,   46,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,   10,   11,   11,
       12,   13,   14,   15,   16,   16,   16,   17,    1,    1,
       18,    1,    1,    1,   21,   22,   23,   24,   25,   26,
       27,   28,   29,   30,   30,   31,   32,   33,   34,   35,
       30,   36,   37,   38,   39,   40,   30,   41,   42,   30,
        1,    1,    1,   19,   20,    1,   21,   22,   23,   24,

       25,   26,   27,   28,   29,   30,   30,   31,   32,   33,
       34,   35,   30,   36,   37,   38,   39,   40,   30,   41,
       42,   30,   43,    1,   44,   45,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[46] =
    {   0,
        1,    1,    1,    1,    2,    1,    3,    4,    5,    6,
        6,    6,    6,    6,    6,    6,    7,    1,    1,    8,
        9,    9,    9,    9,    9,    9,    8,    8,    8,    8,
        8,    8,   10,    8,   10,    8,   10,   10,    8,    8,
        8,    8,    1,    1,    1
    } ;

static yyconst short int yy_base[564] =
    {   0,
        0,    0, 1115, 1116,   44,   46, 1096,   42, 1096, 1094,
       55,   44,   53,   49,   60, 1084,   42,   65,   59,   71,
       38,   72,   70,   78, 1081,  105,  109, 1116,    0,  141,
      158, 1092, 1099, 1116, 1116, 1116,   99,  175,   89, 1072,
      185, 1072, 1070,   34,   82,  101, 1083, 1071, 1064,   85,
     1063, 1093, 1075, 1061, 1075, 1055,   97, 1116, 1060, 1069,
     1061,   99, 1057, 1084, 1059, 1068, 1055, 1116, 1116, 1058,
     1078,  213, 1068,  230,  247,    0,  113,    0, 1116, 1116,
     1059,  116, 1066,  254, 1065, 1060, 1048, 1066, 1116, 1046,
     1039, 1038, 1050, 1116, 1038, 1037, 1052, 1036, 1045, 1040,

     1116, 1033, 1040, 1028,  104, 1116, 1039, 1028, 1056,  102,
     1024, 1028,  119, 1034, 1021, 1020,    0,  126, 1040,  262,
     1039,  279, 1036,  129,    0,    0, 1021,  120,  186, 1036,
      124, 1035,  286, 1034, 1012, 1020, 1009, 1026, 1116, 1008,
     1010, 1037, 1020, 1006, 1004, 1014, 1004, 1018, 1013,  995,
     1014,  170, 1116, 1009,  999, 1005,  188,  195, 1116, 1002,
      170, 1022,  196,  294,  311, 1012,  137,  200,  201, 1004,
      126, 1010,  989,  994,  999,  986, 1005, 1004,  318,  221,
      992,  996,  985,  988,  991,  329,  981,  981,  985,  972,
      976,  973,  977,  976,  974,  983,  316,  982,  309, 1116,

        0,    0,  987,  986,  985,  984, 1116,  243,  202,  330,
        0, 1116,  963,  974,    0,  347,  973,    0,    0,    0,
      331,  980, 1116, 1116,  967,  962, 1116,  348,  349,  957,
      968,  958,  966,  955,  971,  960,  949,  942,  953,  937,
      940, 1116,  960,    0,  951,  947,    0,  348,  355,  366,
      938,  942,  373,  937,  917,  911,  908,  370,  906,  903,
      901,  896,  892, 1116,  892,  386,  893,  907,  870,    0,
      889,  888,  879,    0,  358,  386,    0,  386,  878,  397,
      875,  851,  866,  856,  405,  851,  842,  817, 1116,  802,
      807,  810, 1116, 1116, 1116,  792,  788, 1116,  805,  413,

      804,  763,  424,  750,  770,  768,  762,  423,  424,  427,
      428,  760,  759,  439,  740,  734,  737,  734,  733,  447,
      270,  710, 1116,  454,  704,  713,  701, 1116,  708,  703,
      461,  699,  691,  472,  473, 1116,  307,  694,  691,  686,
      429,  472,    0,  682,  676,  674,  484,  472,  653,    0,
        0,    0,    0,  492,  664,  659,  500,  654,  634,  630,
      619,  638,  635,  630,  508,  475,  605, 1116,  369,  620,
      618,  517,  518,    0,    0,    0,    0,  519,  617,  608,
      606,  527,  605,  612,  593,  585,    0,    0,    0,    0,
      535,  592,    0,  588,  583,  579,  540,  541,    0,  578,

      574,  569,  549,  496,  547,  543, 1116,    0,  539,  538,
      559,  560,    0,    0,    0,    0,  561,  536,  563,  568,
      534,  516,  511,  570,  572,    0,  474,  479,  573,  434,
      425,    0,  427,  575,  395,  352,  361,  341,  387,  337,
      336, 1116,  432,    0,    0, 1116,  591,  592,  334,  597,
      602,  606,  307,  611,  243,  618,  623,  625,  630,  216,
      637,  639,  644,  648,  652,  654,  656,  658,  666,  668,
      673,  677,  679,  681,  686,  210,  199,  691,  695,  700,
      704,  708,  712,  172,  717,  722,  726,  728,  171,  730,
      734,  739,  743,  750,  755,  757,  759,  761,  763,  765,

      767,  772,  777,  781,  786,  791,  795,  797,  799,  801,
      803,  805,  807,  809,  811,  817,  818,  822,  827,  831,
      835,  837,  839,  841,  843,  845,  847,  849,  851,  855,
      860,  865,  869,  871,  873,  135,  875,  879,  884,  888,
      892,  894,  896,  901,  906,  910,  915,  920,  924,  928,
      933,  937,  941,  946,  951,  956,   83,  961,  966,  971,
      976,  984,   72
    } ;

static yyconst short int yy_def[564] =
    {   0,
      446,    1,  446,  446,  446,  446,  446,  446,  446,  446,
      447,  448,  448,   13,   13,   13,   13,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  449,  446,
      446,  450,  451,  446,  446,  446,  447,   31,  446,  446,
      446,  446,  446,  450,  446,  450,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      449,  446,  452,  446,   74,  453,  454,  455,  446,  446,
      446,  456,  457,  446,  458,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,

      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  459,  446,  446,  446,  460,  461,  446,  446,
      462,  120,  453,  463,  464,  455,  446,  456,  456,  465,
      446,  466,  446,  467,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  459,  459,  446,  446,
      446,  460,  461,  446,  164,  468,  469,  470,  471,  446,
      446,  472,  446,  446,  446,  446,  473,  474,  446,  179,
      446,  446,  446,  446,  446,  475,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,

      476,  477,  477,  446,  478,  479,  446,  469,  446,  480,
      481,  446,  446,  446,  180,  446,  446,  180,  180,  180,
      446,  446,  446,  446,  446,  446,  446,  475,  475,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  476,  477,  482,  483,  484,  485,  486,  446,
      446,  487,  446,  488,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  489,
      446,  490,  491,  484,  446,  492,  493,  494,  495,  446,
      496,  446,  497,  498,  446,  499,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  500,  446,

      501,  446,  502,  446,  489,  503,  504,  505,  506,  494,
      494,  507,  508,  446,  509,  446,  510,  511,  512,  446,
      320,  446,  446,  446,  446,  446,  446,  446,  513,  514,
      446,  515,  446,  502,  502,  446,  516,  446,  517,  518,
      446,  519,  520,  521,  522,  523,  446,  347,  446,  321,
      321,  321,  321,  446,  446,  524,  446,  525,  446,  446,
      446,  526,  527,  528,  446,  365,  446,  446,  516,  529,
      530,  531,  532,  348,  348,  348,  348,  446,  446,  533,
      534,  446,  535,  446,  446,  446,  366,  366,  366,  366,
      446,  446,  536,  446,  537,  538,  446,  539,  540,  541,

      542,  543,  446,  403,  544,  446,  446,  536,  545,  546,
      547,  548,  404,  404,  404,  404,  446,  446,  544,  544,
      446,  549,  550,  446,  551,  552,  553,  554,  555,  556,
      446,  557,  558,  446,  559,  557,  560,  561,  562,  446,
      446,  446,  562,  563,  563,    0,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,

      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446
    } ;

static yyconst short int yy_nxt[1162] =
    {   0,
        4,    5,    6,    4,    4,    4,    4,    7,    4,    8,
        8,    8,    8,    8,    8,    8,    9,   10,   11,    4,
       12,   13,   14,   15,   16,   17,    4,    4,   18,    4,
        4,   19,   20,   21,   22,   23,   24,    4,    4,    4,
        4,    4,   25,    4,   26,   27,   27,   27,   27,   29,
       38,   30,   30,   30,   30,   30,   30,   30,   31,   35,
       38,   36,   32,   32,   32,   32,   32,   32,  446,   38,
       44,   89,   49,   58,   59,  446,   39,  445,   40,   43,
       41,   42,   45,   53,   46,  446,  446,  446,  436,  446,
      446,   50,   54,   55,   47,   56,   60,   51,   63,   48,

       61,   52,   65,  446,   57,   78,   64,   62,   68,   69,
       27,   27,   79,   90,   91,   66,  105,   38,   92,   97,
       98,   76,  128,  110,  149,  157,  128,  153,  150,  125,
       80,   93,  111,   29,  106,  128,  154,   76,  157,  128,
      408,  207,   31,  207,  173,  125,  213,   70,   29,  174,
       72,   72,   72,   72,   72,   72,   72,   31,  175,  176,
      214,   73,   73,   73,   73,   73,   73,   74,   74,   74,
       74,   74,   74,   74,   33,  199,  305,  274,   75,   75,
       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   82,  128,  193,  157,   83,   83,   83,   83,   84,

       85,  157,  171,   29,  244,  128,  194,  157,   76,   76,
       76,  197,  202,  200,  157,  243,  125,  211,  125,   86,
       29,  162,  118,  118,  118,  118,  118,  118,  118,   31,
      222,  222,  222,  119,  119,  119,  119,  119,  119,  120,
      120,  120,  120,  120,  120,  120,  121,  446,  126,  247,
      122,  122,  122,  122,  122,  122,  122,  122,  122,  122,
      122,  122,  122,  132,  132,  132,  132,  133,  134,  134,
      131,  164,  164,  164,  164,  164,  164,  164,  121,  355,
      355,  355,  165,  165,  165,  165,  165,  165,  165,  165,
      165,  165,  165,  165,  165,  178,  178,  178,  178,  179,

      180,  180,  131,  203,  203,  203,  203,  203,  203,  203,
      121,  368,  123,  368,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  220,  220,  221,
      222,  222,  222,  222,  131,  228,  238,  241,   76,   71,
      222,  222,  222,  222,   76,  432,  211,  131,  228,   76,
      239,  240,  242,   82,  228,  228,   76,  252,  252,  252,
      252,  253,  254,   76,  211,  258,   76,  228,  228,  432,
      439,  277,  278,  446,  211,  393,  279,  279,  279,  279,
      280,  281,  284,  284,  284,  284,  285,  286,  286,  131,
      290,  442,  310,  442,   76,  291,  299,  299,  299,  299,

      300,  301,  277,   76,  292,  310,  313,  313,  313,  313,
      314,  315,  315,  171,  319,  319,  319,  319,  320,  321,
      321,  131,  330,  330,  330,  330,  331,  332,  332,  197,
      334,   76,   76,  310,  310,  432,  446,   76,  444,  277,
      343,  423,   76,  334,  171,  277,  310,  310,  346,  346,
      346,  346,  347,  348,  348,  171,  353,  353,  354,  355,
      355,  355,  355,  131,  356,  356,  356,  356,  357,  358,
      364,  364,  364,  364,  365,  366,  366,  197,  334,  334,
       76,  379,  379,  379,  392,  392,  392,  432,  343,  197,
      423,  334,  334,  377,  377,  378,  379,  379,  379,  379,

      171,  355,  355,  355,  355,  418,  418,  418,  131,  381,
      381,  381,  381,  382,  383,  383,  258,  390,  390,  391,
      392,  392,  392,  392,  197,   76,   76,   33,  379,  379,
      379,  379,  423,  343,  399,  171,  402,  402,  402,  402,
      403,  404,  404,  258,  392,  392,  392,  392,   76,   76,
      396,  197,  258,  419,  423,  396,  343,  399,  416,  416,
      417,  418,  418,  418,  418,  258,  419,   76,   76,  419,
      418,  418,  418,  418,  419,  399,  426,  258,   76,  418,
       76,   76,  419,   76,  258,  258,  399,  419,  426,  426,
      258,  426,   37,   37,  258,   33,   37,   32,   32,  396,

       32,   32,   73,   73,  340,   73,   77,   77,  197,  407,
       77,  119,  119,  406,  119,  124,  124,  124,  405,  124,
      129,  258,  258,  129,  258,  129,  129,  129,  130,  130,
      134,  134,  158,  171,  396,  158,  340,  158,  158,  158,
      163,  392,  163,  163,  166,  166,  197,  166,  168,  168,
      168,  197,  168,  169,  197,  386,  169,  172,  172,  177,
      177,  180,  180,  205,  205,  385,  205,  208,  208,  384,
      258,  208,  209,  209,  209,  258,  209,  210,  210,  210,
      131,  210,  215,  215,  218,  218,  219,  219,  229,  379,
      171,  229,  171,  229,  229,  229,  245,  245,  171,  245,

      246,  246,   33,  246,  248,  248,  248,  340,  248,  249,
      273,  367,  249,  271,  271,  197,  271,  272,  272,  197,
      272,  275,  275,  275,  197,  275,  276,  276,  276,  361,
      276,  283,  283,  286,  286,  306,  306,  360,  306,  307,
      307,  359,  307,  308,  308,  308,  355,  308,  309,  131,
      131,  309,  311,  131,  349,  311,  171,  311,  311,  311,
      312,  312,  315,  315,  317,  317,  318,  318,  321,  321,
      329,  329,  332,  332,  335,  171,  171,  335,  340,  335,
      335,  335,  338,  338,  273,  338,  339,  339,  337,  339,
      341,  341,  341,  336,  341,  342,  342,  342,  333,  342,

      344,  344,  345,  345,  348,  348,  350,  350,  351,  351,
      352,  352,  362,  362,  363,  363,  366,  366,  369,  369,
      197,  197,  369,  370,  370,  328,  370,  371,  371,  327,
      371,  372,  372,  372,  326,  372,  373,  325,  324,  373,
      374,  374,  375,  375,  376,  376,  380,  380,  383,  383,
      387,  387,  388,  388,  389,  389,  394,  394,  323,  394,
      395,  395,  322,  395,  397,  397,  397,  131,  397,  398,
      398,  398,  131,  398,  400,  400,  401,  401,  404,  404,
      409,  409,  131,  409,  410,  410,  316,  410,  411,  411,
      411,  171,  411,  412,  171,   33,  412,  413,  413,  414,

      414,  415,  415,  420,  273,  206,  420,  304,  420,  420,
      420,  421,  421,  303,  421,  422,  422,  302,  422,  424,
      424,  424,  298,  424,  425,  425,  425,  297,  425,  427,
      427,  296,  427,  428,  428,  295,  428,  429,  429,  429,
      294,  429,  430,  293,  289,  430,  431,  431,  288,  431,
      433,  433,  287,  131,  433,  434,  434,  434,  131,  434,
      435,  435,  282,  273,  435,  437,  437,  206,  270,  437,
      438,  438,  269,  268,  438,  440,  440,  267,  266,  440,
      441,  441,  265,  264,  441,  443,  443,  131,  263,  443,
      262,  261,  260,  259,  257,  256,  131,  255,  251,  250,

       33,  206,  121,  121,   89,  237,  236,   89,   89,  235,
      234,  233,  232,  231,  230,  227,  226,  225,  224,  223,
      131,  131,   64,  217,   49,  216,  131,  212,  206,  201,
      198,   89,  196,  195,  192,  191,  190,  189,   89,   89,
       89,  188,  187,  186,   89,  185,  184,  183,  182,  181,
      131,  131,  131,  170,  167,   33,   38,  161,  160,  159,
      156,  155,  152,  151,   89,  148,  147,  146,  145,  144,
       89,  143,  142,  141,  140,  139,  138,  137,   89,  136,
      135,  131,  131,  127,   38,  117,   67,  116,  115,  114,
      113,  112,  109,  108,  107,  104,  103,  102,  101,  100,

       99,   96,   95,   94,   88,   87,   81,   76,   38,   67,
      446,   34,   33,   28,  446,    3,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446
    } ;

static yyconst short int yy_chk[1162] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    5,    5,    6,    6,    8,
       44,    8,    8,    8,    8,    8,    8,    8,    8,   11,
       12,   11,    8,    8,    8,    8,    8,    8,   17,   13,
       14,   44,   17,   21,   21,   14,   12,  563,   12,   13,
       12,   12,   14,   19,   15,   13,   15,   13,  557,   13,
       13,   18,   19,   19,   15,   20,   22,   18,   23,   15,

       22,   18,   24,   37,   20,   37,   23,   22,   26,   26,
       27,   27,   39,   45,   45,   24,   57,   46,   45,   50,
       50,   77,   82,   62,  105,  113,  128,  110,  105,   77,
       39,   46,   62,  118,   57,   82,  110,  124,  113,  128,
      536,  167,  118,  167,  131,  124,  171,   26,   30,  131,
       30,   30,   30,   30,   30,   30,   30,   30,  131,  131,
      171,   30,   30,   30,   30,   30,   30,   31,   31,   31,
       31,   31,   31,   31,   31,  161,  489,  484,   31,   31,
       31,   31,   31,   31,   38,   38,   38,   38,   38,   38,
       38,   41,  129,  152,  157,   41,   41,   41,   41,   41,

       41,  158,  129,  163,  477,  129,  152,  157,  168,  169,
      209,  158,  163,  161,  158,  476,  168,  169,  209,   41,
       72,  460,   72,   72,   72,   72,   72,   72,   72,   72,
      180,  180,  180,   72,   72,   72,   72,   72,   72,   74,
       74,   74,   74,   74,   74,   74,   74,  208,  455,  208,
       74,   74,   74,   74,   74,   74,   75,   75,   75,   75,
       75,   75,   75,   84,   84,   84,   84,   84,   84,   84,
       84,  120,  120,  120,  120,  120,  120,  120,  120,  321,
      321,  321,  120,  120,  120,  120,  120,  120,  122,  122,
      122,  122,  122,  122,  122,  133,  133,  133,  133,  133,

      133,  133,  133,  164,  164,  164,  164,  164,  164,  164,
      164,  337,  453,  337,  164,  164,  164,  164,  164,  164,
      165,  165,  165,  165,  165,  165,  165,  179,  179,  179,
      179,  179,  179,  179,  179,  186,  197,  199,  210,  449,
      221,  221,  221,  221,  441,  440,  210,  221,  186,  438,
      197,  197,  199,  216,  228,  229,  248,  216,  216,  216,
      216,  216,  216,  249,  248,  229,  275,  228,  229,  437,
      436,  249,  250,  369,  275,  369,  250,  250,  250,  250,
      250,  250,  253,  253,  253,  253,  253,  253,  253,  253,
      258,  439,  278,  439,  276,  258,  266,  266,  266,  266,

      266,  266,  276,  435,  258,  278,  280,  280,  280,  280,
      280,  280,  280,  280,  285,  285,  285,  285,  285,  285,
      285,  285,  300,  300,  300,  300,  300,  300,  300,  300,
      303,  308,  309,  310,  311,  433,  443,  341,  443,  308,
      309,  431,  430,  303,  311,  341,  310,  311,  314,  314,
      314,  314,  314,  314,  314,  314,  320,  320,  320,  320,
      320,  320,  320,  320,  324,  324,  324,  324,  324,  324,
      331,  331,  331,  331,  331,  331,  331,  331,  334,  335,
      342,  348,  348,  348,  366,  366,  366,  428,  342,  335,
      427,  334,  335,  347,  347,  347,  347,  347,  347,  347,

      347,  354,  354,  354,  354,  404,  404,  404,  354,  357,
      357,  357,  357,  357,  357,  357,  357,  365,  365,  365,
      365,  365,  365,  365,  365,  372,  373,  423,  378,  378,
      378,  378,  422,  372,  373,  378,  382,  382,  382,  382,
      382,  382,  382,  382,  391,  391,  391,  391,  397,  398,
      421,  391,  418,  405,  410,  409,  397,  398,  403,  403,
      403,  403,  403,  403,  403,  403,  405,  411,  412,  419,
      417,  417,  417,  417,  420,  411,  412,  417,  424,  406,
      425,  429,  419,  434,  420,  402,  424,  420,  425,  429,
      401,  434,  447,  447,  400,  396,  447,  448,  448,  395,

      448,  448,  450,  450,  394,  450,  451,  451,  392,  386,
      451,  452,  452,  385,  452,  454,  454,  454,  384,  454,
      456,  383,  381,  456,  380,  456,  456,  456,  457,  457,
      458,  458,  459,  379,  371,  459,  370,  459,  459,  459,
      461,  367,  461,  461,  462,  462,  364,  462,  463,  463,
      463,  363,  463,  464,  362,  361,  464,  465,  465,  466,
      466,  467,  467,  468,  468,  360,  468,  469,  469,  359,
      358,  469,  470,  470,  470,  356,  470,  471,  471,  471,
      355,  471,  472,  472,  473,  473,  474,  474,  475,  349,
      346,  475,  345,  475,  475,  475,  478,  478,  344,  478,

      479,  479,  340,  479,  480,  480,  480,  339,  480,  481,
      338,  333,  481,  482,  482,  332,  482,  483,  483,  330,
      483,  485,  485,  485,  329,  485,  486,  486,  486,  327,
      486,  487,  487,  488,  488,  490,  490,  326,  490,  491,
      491,  325,  491,  492,  492,  492,  322,  492,  493,  319,
      318,  493,  494,  317,  316,  494,  315,  494,  494,  494,
      495,  495,  496,  496,  497,  497,  498,  498,  499,  499,
      500,  500,  501,  501,  502,  313,  312,  502,  307,  502,
      502,  502,  503,  503,  306,  503,  504,  504,  305,  504,
      505,  505,  505,  304,  505,  506,  506,  506,  302,  506,

      507,  507,  508,  508,  509,  509,  510,  510,  511,  511,
      512,  512,  513,  513,  514,  514,  515,  515,  516,  516,
      301,  299,  516,  517,  517,  297,  517,  518,  518,  296,
      518,  519,  519,  519,  292,  519,  520,  291,  290,  520,
      521,  521,  522,  522,  523,  523,  524,  524,  525,  525,
      526,  526,  527,  527,  528,  528,  529,  529,  288,  529,
      530,  530,  287,  530,  531,  531,  531,  286,  531,  532,
      532,  532,  284,  532,  533,  533,  534,  534,  535,  535,
      537,  537,  283,  537,  538,  538,  282,  538,  539,  539,
      539,  281,  539,  540,  279,  273,  540,  541,  541,  542,

      542,  543,  543,  544,  272,  271,  544,  269,  544,  544,
      544,  545,  545,  268,  545,  546,  546,  267,  546,  547,
      547,  547,  265,  547,  548,  548,  548,  263,  548,  549,
      549,  262,  549,  550,  550,  261,  550,  551,  551,  551,
      260,  551,  552,  259,  257,  552,  553,  553,  256,  553,
      554,  554,  255,  254,  554,  555,  555,  555,  252,  555,
      556,  556,  251,  246,  556,  558,  558,  245,  243,  558,
      559,  559,  241,  240,  559,  560,  560,  239,  238,  560,
      561,  561,  237,  236,  561,  562,  562,  235,  234,  562,
      233,  232,  231,  230,  226,  225,  222,  217,  214,  213,

      206,  205,  204,  203,  198,  196,  195,  194,  193,  192,
      191,  190,  189,  188,  187,  185,  184,  183,  182,  181,
      178,  177,  176,  175,  174,  173,  172,  170,  166,  162,
      160,  156,  155,  154,  151,  150,  149,  148,  147,  146,
      145,  144,  143,  142,  141,  140,  138,  137,  136,  135,
      134,  132,  130,  127,  123,  121,  119,  116,  115,  114,
      112,  111,  109,  108,  107,  104,  103,  102,  100,   99,
       98,   97,   96,   95,   93,   92,   91,   90,   88,   87,
       86,   85,   83,   81,   73,   71,   70,   67,   66,   65,
       64,   63,   61,   60,   59,   56,   55,   54,   53,   52,

       51,   49,   48,   47,   43,   42,   40,   33,   32,   25,
       16,   10,    9,    7,    3,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "components_r6.l"
#define INITIAL 0
#line 2 "components_r6.l"
/*
  filename: components_r6.l

  description:
    Defines the tokenizer for an RPSLng route6 components attribute.  It is
    derived from components.l.

  notes:
    Tokens are defined in the associated grammar, components.l.

  $Id: components_r6.l,v 1.1 2004/12/27 17:52:37 can Exp $
*/
#line 35 "components_r6.l"
#include <stdlib.h>
#include <ctype.h>
#include <string.h>

/* tokens defined in the grammar */
#include "components_r6.tab.h"

#define components_r6wrap yywrap
void syntax_error(char *fmt, ...);
void yy_input(char *buf, int *result, int max_size);
#undef YY_INPUT
#define YY_INPUT(buf,result,max_size) yy_input(buf,&result,max_size)
#line 836 "components_r6.lex.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 49 "components_r6.l"


#line 990 "components_r6.lex.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 447 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1116 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 51 "components_r6.l"
{ ; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 53 "components_r6.l"
{ return OP_OR; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 54 "components_r6.l"
{ return OP_AND; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 55 "components_r6.l"
{ return OP_NOT; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 56 "components_r6.l"
{ return OP_EQUAL; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 57 "components_r6.l"
{ return OP_COMPARE; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 58 "components_r6.l"
{ return OP_APPEND; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 60 "components_r6.l"
{ return OP_MS; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 61 "components_r6.l"
{ return OP_MS; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 62 "components_r6.l"
{ 
    long int val;
    val = strtol(yytext+1, NULL, 10);
    if ((val < 0) || (val > 128)) {
        syntax_error("more specifics operator \"%s\" not 0 to 128 bits",
                     yytext);
    }
    if (val <= 32) {
      return OP_MS;
    }
    return OP_MS_V6;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 74 "components_r6.l"
{
    long int val1, val2;
    char *p;
    val1 = strtol(yytext+1, &p, 10);
    if ((val1 < 0) || (val1 > 128)) {
        syntax_error("more specifics operator \"%s\" not 0 to 128 bits",
                     yytext);
    }
    val2 = strtol(p+1, NULL, 10);
    if ((val2 < 0) || (val2 > 128)) {
        syntax_error("more specifics operator \"%s\" not 0 to 128 bits",
                     yytext);
    }
    if (val2 < val1) {
        syntax_error("more specifics range operator \"%s\" is invalid, range end less than range beginning",
                     yytext);
    }
    if(val2 <= 32) {
      return OP_MS;
    }
    return OP_MS_V6;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 98 "components_r6.l"
{ return KEYW_ATOMIC; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 99 "components_r6.l"
{ return KEYW_ANY; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 100 "components_r6.l"
{ return KEYW_PEERAS; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 102 "components_r6.l"
{ return KEYW_IGP_COST; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 103 "components_r6.l"
{ return KEYW_SELF; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 104 "components_r6.l"
{ return KEYW_PREPEND; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 105 "components_r6.l"
{ return KEYW_APPEND; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 106 "components_r6.l"
{ return KEYW_DELETE; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 107 "components_r6.l"
{ return KEYW_CONTAINS; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 109 "components_r6.l"
{ return KEYW_INTERNET; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 110 "components_r6.l"
{ return KEYW_NO_EXPORT; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 111 "components_r6.l"
{ return KEYW_NO_ADVERTISE; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 113 "components_r6.l"
{ return TKN_PREF; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 114 "components_r6.l"
{ return TKN_MED; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 115 "components_r6.l"
{ return TKN_DPA; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 116 "components_r6.l"
{ return TKN_ASPATH; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 117 "components_r6.l"
{ return TKN_COMMUNITY; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 118 "components_r6.l"
{ return TKN_NEXT_HOP; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 119 "components_r6.l"
{ return TKN_COST; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 121 "components_r6.l"
{ return ASPATH_POSTFIX; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 122 "components_r6.l"
{ return ASPATH_POSTFIX; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 123 "components_r6.l"
{ return ASPATH_POSTFIX; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 124 "components_r6.l"
{ return ASPATH_POSTFIX; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 125 "components_r6.l"
{ return ASPATH_POSTFIX; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 127 "components_r6.l"
{ return KEYW_PROTOCOL; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 128 "components_r6.l"
{ return TKN_PROTOCOL; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 130 "components_r6.l"
{
    return TKN_ASNO;
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 134 "components_r6.l"
{
    return TKN_FLTRNAME;
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 138 "components_r6.l"
{
    return TKN_ASNAME;
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 142 "components_r6.l"
{
    return TKN_RSNAME;
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 146 "components_r6.l"
{
    /* check each number of 1.2.3.4/5 in prefix is valid */
    long int val;
    char *s, *p;
    p = s = yytext;
    while (*s != '/') {
        val = strtol(p, &s, 10);
        if ((val < 0) || (val > 255)) {
             syntax_error("IP prefix \"%s\" contains an invalid octet", 
                          yytext);
        }
        p = s + 1;
    }
    val = strtol(p, NULL, 10);
    if ((val < 0) || (val > 32)) {
        syntax_error("IP prefix \"%s\" contains an invalid prefix length", 
                     yytext);
    }
    return TKN_PRFXV4;
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 167 "components_r6.l"
{
    /* check each quad of 1A:3:7:8:AAAA:BBBB:DEAD:BEEF/55 in prefix is valid */
    long int val;
    char *s, *p;
    p = s = yytext;
    while (*s != '/') {
        val = strtol(p, &s, 16);
        if ((val < 0) || (val > 65535)) {
             syntax_error("IPv6 prefix \"%s\" contains an invalid quad",
                          yytext);
        }
        p = s + 1;
    }
    val = strtol(p, NULL, 10);
    if ((val < 0) || (val > 128)) {
        syntax_error("IPv6 prefix \"%s\" contains an invalid prefix length",
                     yytext);
    }
    return TKN_PRFXV6;
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 188 "components_r6.l"
{
    /* check each quad of 1A::AAAA:BBBB:DEAD:BEEF/55 in prefix is valid */
    long int val;
    char *s, *p, *r;
    int leftquads = 0;
    int rightquads = 0;

    r = p = s = yytext;
    while (*s != '/') {
        val = strtol(p, &s, 16);
        if ((val < 0) || (val > 65535)) {
             syntax_error("IPv6 prefix \"%s\" contains an invalid quad",
                          yytext);
        }
        p = s + 1;
    }
    val = strtol(p, NULL, 10);
    if ((val < 0) || (val > 128)) {
        syntax_error("IPv6 prefix \"%s\" contains an invalid prefix length",
                     yytext);
    }

    /* And now, count colons to the left of "::" - this is
       one less then the number of left quads */

    r = strchr(yytext, ':');
    leftquads++;
    while (r[1] != ':') {
        leftquads++;
        r = strchr(r+1, ':');
    }
    /* skip "::" */
    r += 2;
    /* count colons to the right of "::" - one less then the number of right quads */
    if (r[0] != '\0') {
        do {
            rightquads++;
            r = strchr(r+1, ':');
        } while (r != NULL);
    }
    /* check for too many quads */
    if ((leftquads + rightquads) > 8) {
        syntax_error("IPv6 address \"%s\" contains too many digits", yytext);
    }

    return TKN_PRFXV6DC;
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 236 "components_r6.l"
{
    /* check each number of 1.2.3.4/5 in prefix is valid, as
       well as any bit ranges specified */
    long int val;
    long int endval;
    char *s, *p;
    p = s = yytext;
    while (*s != '/') {
        val = strtol(p, &s, 10);
        if ((val < 0) || (val > 255)) {
             syntax_error("IP prefix \"%s\" contains an invalid octet", 
                          yytext);
        }
        p = s + 1;
    }
    val = strtol(p, &s, 10);
    if ((val < 0) || (val > 32)) {
        syntax_error("IP prefix range \"%s\" contains an invalid prefix length",
                     yytext);
    }
    p = s + 1;
    if (isdigit((int)*p)) {
        val = strtol(p, &s, 10);
        if ((val < 0) || (val > 32)) {
            syntax_error("IP prefix range \"%s\" contains an invalid range",
                         yytext);
        }
        p = s + 1;
        if (isdigit((int)*p)) {
            endval = strtol(p, NULL, 10);
            if ((endval < 0) || (endval > 32)) {
                syntax_error("IP prefix \"%s\" contains an invalid prefix range", 
                             yytext);
            }
            if (endval < val) {
                syntax_error("IP prefix \"%s\" range end is less than range start",
                             yytext);
            }
        }
    }
    return TKN_PRFXV4RNG;
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 279 "components_r6.l"
{
    /* check each quad of 1A:3:7:8:AAAA:BBBB:DEAD:BEEF/55 in prefix is valid, as
       well as any bit ranges specified */
    long int val;
    long int endval;
    char *s, *p;
    p = s = yytext;
    while (*s != '/') {
        val = strtol(p, &s, 16);
        if ((val < 0) || (val > 65535)) {
             syntax_error("IPv6 prefix \"%s\" contains an invalid quad",
                          yytext);
        }
        p = s + 1;
    }
    val = strtol(p, &s, 10);
    if ((val < 0) || (val > 128)) {
        syntax_error("IPv6 prefix range \"%s\" contains an invalid prefix length",
                     yytext);
    }
    p = s + 1;
    if (isdigit((int)*p)) {
        val = strtol(p, &s, 10);
        if ((val < 0) || (val > 128)) {
            syntax_error("IPv6 prefix range \"%s\" contains an invalid range",
                         yytext);
        }
        p = s + 1;
        if (isdigit((int)*p)) {
            endval = strtol(p, NULL, 10);
            if ((endval < 0) || (endval > 128)) {
                syntax_error("IPv6 prefix \"%s\" contains an invalid prefix range",
                             yytext);
            }
            if (endval < val) {
                syntax_error("IPv6 prefix \"%s\" range end is less than range start",
                             yytext);
            }
        }
    }
    return TKN_PRFXV6RNG;
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 322 "components_r6.l"
{
    /* check each quad of 1A:3:7:8:AAAA:BBBB:DEAD:BEEF/55 in prefix is valid, as
       well as any bit ranges specified */
    long int val;
    long int endval;
    char *s, *p, *r;
    int leftquads = 0;
    int rightquads = 0;

    p = s = yytext;
    while (*s != '/') {
        val = strtol(p, &s, 16);
        if ((val < 0) || (val > 65535)) {
             syntax_error("IPv6 prefix \"%s\" contains an invalid quad",
                          yytext);
        }
        p = s + 1;
    }
    val = strtol(p, &s, 10);
    if ((val < 0) || (val > 128)) {
        syntax_error("IPv6 prefix range \"%s\" contains an invalid prefix length",
                     yytext);
    }
    p = s + 1;
    if (isdigit((int)*p)) {
        val = strtol(p, &s, 10);
        if ((val < 0) || (val > 128)) {
            syntax_error("IPv6 prefix range \"%s\" contains an invalid range",
                         yytext);
        }
        p = s + 1;
        if (isdigit((int)*p)) {
            endval = strtol(p, NULL, 10);
            if ((endval < 0) || (endval > 128)) {
                syntax_error("IPv6 prefix \"%s\" contains an invalid prefix range",
                             yytext);
            }
            if (endval < val) {
                syntax_error("IPv6 prefix \"%s\" range end is less than range start",
                             yytext);
            }
        }
    }

    /* And now, count colons to the left of "::" - this is
       one less than the number of left quads */

    r = strchr(yytext, ':');
    leftquads++;
    while (r[1] != ':') {
        leftquads++;
        r = strchr(r+1, ':');
    }
    /* skip "::" */
    r += 2;
    /* count colons to the right of "::" - one less than the number of right quads */
    if (r[0] != '\0') {
        do {
            rightquads++;
            r = strchr(r+1, ':');
        } while (r != NULL);
    }
    /* check for too many quads */
    if ((leftquads + rightquads) > 8) {
        syntax_error("IPv6 address \"%s\" contains too many digits", yytext);
    }

    return TKN_PRFXV6DCRNG;
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 392 "components_r6.l"
{
    /* verify each part is a 16-bit number */
    long int val;
    char *s, *p;
    p = s = yytext;
    while (*s != '\0') {
        val = strtol(p, &s, 10);
        if ((val < 0) || (val > 65535)) {
             syntax_error("Community number \"%s\" contains an invalid number",
                           yytext);
        }
        p = s + 1;
    }
    return TKN_COMM_NO;
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 408 "components_r6.l"
{
    components_r6lval.sval = yytext;
    return TKN_INT;
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 413 "components_r6.l"
{ return yytext[0]; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 415 "components_r6.l"
ECHO;
	YY_BREAK
#line 1619 "components_r6.lex.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 447 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 447 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 446);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 415 "components_r6.l"


void
components_r6_reset ()
{
    yy_flush_buffer(YY_CURRENT_BUFFER);
}


