#define yy_create_buffer filter_create_buffer
#define yy_delete_buffer filter_delete_buffer
#define yy_scan_buffer filter_scan_buffer
#define yy_scan_string filter_scan_string
#define yy_scan_bytes filter_scan_bytes
#define yy_flex_debug filter_flex_debug
#define yy_init_buffer filter_init_buffer
#define yy_flush_buffer filter_flush_buffer
#define yy_load_buffer_state filter_load_buffer_state
#define yy_switch_to_buffer filter_switch_to_buffer
#define yyin filterin
#define yyleng filterleng
#define yylex filterlex
#define yyout filterout
#define yyrestart filterrestart
#define yytext filtertext
#define yywrap filterwrap

#line 20 "filter.lex.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 45
#define YY_END_OF_BUFFER 46
static yyconst short int yy_accept[307] =
    {   0,
        0,    0,   46,   44,    1,    1,   44,   43,    5,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,    1,    7,    0,   43,    0,    6,    9,
        8,   10,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    2,    0,    0,    0,    0,    0,
       30,   31,    0,    0,   42,    0,    3,   12,    0,    0,
       35,   35,   35,    0,    0,    0,    0,    0,   25,    0,
        0,    0,   24,    0,    0,    4,    0,    0,    0,    0,
        0,    0,   11,    0,    0,   37,   35,    0,   35,   35,
       35,    0,    0,    0,   29,    0,    0,    0,    0,    0,

        0,    0,    0,   23,    0,    0,   38,   15,    0,    0,
        0,    0,   35,    0,    0,    0,    0,   35,   35,   35,
       35,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   32,    0,   17,    0,    0,
       35,    0,    0,   35,   35,   35,   35,   35,   26,    0,
        0,   18,    0,   36,    0,    0,    0,    0,    0,   13,
        0,    0,    0,    0,    0,   34,   41,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   16,    0,    0,    0,    0,    0,    0,   37,   37,
       37,    0,    0,    0,    0,    0,    0,    0,   19,    0,

        0,    0,   14,   20,   28,    0,    0,   38,   38,   38,
        0,    0,    0,   39,    0,   37,   37,   37,   37,   37,
        0,    0,    0,    0,    0,    0,    0,   27,    0,    0,
        0,    0,   21,   38,   38,   38,   38,    0,    0,   38,
       33,    0,   37,   37,   37,   37,   37,    0,    0,    0,
        0,    0,    0,    0,   36,   36,   36,    0,    0,    0,
       38,   38,   38,   38,   38,    0,   40,   40,   37,   37,
       37,   37,   37,   37,   36,   36,   36,   36,    0,    0,
        0,   38,   38,   38,   38,   38,   38,    0,   36,   36,
       36,   36,   36,    0,    0,   22,   40,   36,   36,   36,

       36,   36,   36,    0,   36,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,   10,   11,   11,
       12,   13,   14,   15,   16,   16,   16,   17,    1,    1,
       18,    1,    1,    1,   21,   22,   23,   24,   25,   26,
       27,   28,   29,   22,   22,   30,   31,   32,   33,   34,
       22,   35,   36,   37,   38,   39,   22,   40,   41,   22,
        1,    1,    1,   19,   20,    1,   21,   22,   23,   24,

       25,   26,   27,   28,   29,   22,   22,   30,   31,   32,
       33,   34,   22,   35,   36,   37,   38,   39,   22,   40,
       41,   22,   42,    1,   43,   44,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[45] =
    {   0,
        1,    1,    1,    1,    2,    1,    3,    4,    1,    5,
        5,    5,    5,    5,    5,    5,    6,    1,    1,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    1,    1,    1
    } ;

static yyconst short int yy_base[363] =
    {   0,
        0,    0,  621,  622,   43,   45,  602,   41,  601,   45,
       19,  585,   29,  587,   29,  591,   32,  580,   34,  578,
      588,  583,   62,   68,  622,    0,   56,    0,  622,  622,
      622,   55,   44,  577,   98,   43,  580,  588,  571,  573,
      569,  581,  564,   52,  622,  578,  577,  594,  570,  567,
      622,  622,  569,  589,    0,    0,  622,  622,  571,   70,
      578,  123,  577,  572,  561,  554,  553,  564,  622,  553,
      567,  561,  622,  548,   55,  622,  549,   52,   74,  557,
      545,    0,    0,  549,   75,   76,  563,   66,  562,  131,
      561,  540,  538,  554,  622,  537,  566,  549,  536,  550,

      545,  528,  546,  622,  541,   77,   99,  622,   82,  557,
      540,   81,  546,  526,  531,  535,  523,  541,  540,  139,
      110,  528,  523,  525,  528,  110,  519,  519,  522,  510,
      514,  511,  514,  136,  129,  622,    0,  622,  509,  519,
        0,  166,  518,    0,    0,    0,  149,  525,  622,  512,
      508,  622,  111,  167,  503,  513,  504,  511,  502,  517,
      509,  496,  506,  494,  497,  622,  519,  181,  502,  509,
      188,  508,  489,  486,  486,  142,  484,  483,  485,  483,
      482,  622,  195,  491,  508,  477,    0,  205,  496,  216,
      495,  476,  493,  492,  224,  491,  486,  465,  622,  469,

      474,  478,  622,  622,  622,  465,  464,  483,  232,  482,
      463,  243,  454,  477,  244,  245,  478,  477,  256,  475,
      469,  442,  420,  418,  264,  116,  382,  622,  202,  379,
      384,  378,  622,  375,  373,  272,  366,  360,  283,  284,
      622,  160,  361,  354,  353,  295,  179,  332,    0,    0,
        0,    0,  243,  350,  348,  303,  347,  328,  326,  324,
      326,  325,  285,  311,  209,  264,  622,  178,    0,    0,
        0,    0,  282,  281,  280,  279,  319,  244,  252,  237,
      232,    0,    0,    0,    0,  327,  169,    0,  158,  152,
      147,  335,  212,  334,   93,  622,    0,    0,    0,    0,

        0,  345,  107,  346,  352,  622,  369,  374,  118,  103,
      102,  377,  380,  382,  386,   98,  389,  391,  393,  395,
      397,  399,  403,   94,  406,  408,   93,  412,  415,  417,
      419,  421,  423,  425,  427,  431,  434,  436,  438,  440,
      442,  444,  446,  448,  450,  455,  456,  458,  460,  462,
      464,  466,  468,  470,  472,  474,  476,   86,  478,  480,
      482,  486
    } ;

static yyconst short int yy_def[363] =
    {   0,
      306,    1,  306,  306,  306,  306,  306,  307,  306,  308,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  309,  307,  310,  306,  306,
      306,  308,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  309,  310,  311,  306,  306,  306,  312,
      313,  306,  314,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  315,  306,
      306,  316,  311,  306,  312,  312,  317,  306,  318,  306,
      319,  306,  306,  306,  306,  306,  306,  306,  306,  306,

      306,  306,  306,  306,  306,  315,  315,  306,  306,  316,
      306,  306,  320,  306,  306,  306,  306,  321,  322,  306,
      120,  306,  306,  306,  306,  323,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  324,  306,  306,  306,
      121,  306,  306,  121,  121,  121,  306,  306,  306,  306,
      306,  306,  323,  323,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  324,  306,  306,  325,
      306,  326,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  327,  328,  329,  306,
      330,  306,  331,  332,  306,  333,  306,  306,  306,  306,

      306,  306,  306,  306,  306,  306,  306,  334,  306,  335,
      306,  336,  306,  327,  328,  328,  337,  338,  306,  339,
      306,  340,  341,  342,  306,  225,  306,  306,  306,  306,
      306,  306,  306,  343,  344,  306,  345,  306,  336,  336,
      306,  346,  347,  348,  349,  306,  246,  306,  226,  226,
      226,  226,  306,  306,  350,  306,  351,  306,  306,  306,
      352,  353,  354,  306,  264,  306,  306,  346,  247,  247,
      247,  247,  306,  306,  355,  356,  306,  357,  306,  306,
      306,  265,  265,  265,  265,  306,  306,  358,  359,  360,
      361,  306,  292,  362,  306,  306,  358,  293,  293,  293,

      293,  306,  306,  362,  362,    0,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306
    } ;

static yyconst short int yy_nxt[667] =
    {   0,
        4,    5,    6,    4,    4,    4,    4,    7,    4,    8,
        8,    8,    8,    8,    8,    8,    4,    9,   10,    4,
       11,    4,   12,   13,    4,   14,    4,    4,   15,    4,
       16,   17,   18,   19,   20,   21,    4,    4,    4,    4,
        4,   22,    4,   23,   24,   24,   24,   24,   26,   30,
       33,   31,   34,   37,   35,   40,   43,   28,   46,  306,
       41,   56,   38,   26,   44,   51,   52,   57,   47,   24,
       24,   75,   28,   65,   66,  101,   85,  104,   67,  102,
      106,   85,   85,  106,   58,  105,  114,  135,   76,   85,
      297,  115,  112,  106,   85,   85,  106,  214,  167,  116,

      117,  139,  110,   53,   60,  106,   83,   55,   61,   61,
       61,   61,   62,   63,  140,  134,  153,  153,  106,  148,
      148,  148,   54,  176,  136,  254,  254,  254,  303,  153,
      153,   64,   89,   89,   89,   89,   90,   91,   91,   88,
      119,  119,  119,  119,  120,  121,  121,   88,  146,  146,
      147,  148,  148,  148,  148,   88,  162,  165,  148,  148,
      148,  148,  200,  176,  267,   88,  267,  201,  176,  163,
      164,  166,   60,  153,  176,  202,  170,  170,  170,  170,
      171,  172,  306,  176,  288,  134,  153,  188,  274,  274,
      274,  189,  189,  189,  189,  190,  191,  194,  194,  194,

      194,  195,  196,  196,   88,  208,  208,  208,  208,  209,
      210,  215,  255,  255,  255,  255,  256,  257,  287,  287,
      287,  303,  303,  303,  215,  218,  218,  218,  218,  219,
      220,  220,  112,  224,  224,  224,  224,  225,  226,  226,
       88,  235,  235,  235,  235,  236,  237,  237,  134,  239,
      215,  215,  254,  254,  254,  254,  296,  295,  294,   88,
      176,  112,  239,  215,  215,  245,  245,  245,  245,  246,
      247,  247,  112,  252,  252,  253,  254,  254,  254,  254,
       88,  263,  263,  263,  263,  264,  265,  265,  134,  239,
      239,  274,  274,  274,  274,  176,  176,  112,  112,  287,

      134,  134,  239,  239,  272,  272,  273,  274,  274,  274,
      274,  112,  276,  276,  276,  276,  277,  278,  278,  176,
      285,  285,  286,  287,  287,  287,  287,  134,  291,  291,
      291,  291,  292,  293,  293,  176,  287,  287,  287,  287,
      304,  134,  134,  134,  301,  301,  302,  303,  303,  303,
      303,  176,  304,  304,  303,  303,  303,  303,  304,  281,
      280,  176,  279,  176,  176,  304,   88,  274,  176,  112,
      112,  304,   27,   27,   27,   32,   32,  112,   32,   86,
      266,   86,  134,   86,   87,   87,   91,   91,  107,  134,
      107,  134,  107,  113,  113,  118,  118,  121,  121,  141,

      141,  144,  144,  145,  145,  154,  260,  154,  259,  154,
      193,  193,  196,  196,  216,  258,  216,  254,  216,  217,
      217,  220,  220,  222,  222,  223,  223,  226,  226,  234,
      234,  237,  237,  240,   88,  240,   88,  240,  243,  243,
      244,  244,  247,  247,  249,  249,  250,  250,  251,  251,
      261,  261,  262,  262,  265,  265,  268,  268,   88,  268,
      269,  269,  270,  270,  271,  271,  275,  275,  278,  278,
      282,  282,  283,  283,  284,  284,  289,  289,  290,  290,
      293,  293,  298,  298,  299,  299,  300,  300,  305,  248,
      305,  112,  305,  112,  112,  242,  241,  238,  134,  134,

      233,  232,  231,  230,  229,  228,  227,   88,   88,   88,
      221,  112,  112,  213,  212,  211,  207,  206,  205,  204,
      203,  199,  198,  197,   88,   88,  192,  187,  186,  185,
      184,  183,  182,   88,  181,  180,  179,  178,  177,  175,
      174,   88,  173,  169,  168,  161,  160,  159,  158,  157,
      156,  155,  152,  151,  150,  149,   88,   88,   48,  143,
       39,  142,   88,  138,  137,  133,  132,  131,  130,  129,
      128,  127,  126,  125,  124,  123,  122,   88,   88,   88,
      111,  109,  108,  103,  100,   99,   98,   97,   96,   95,
       94,   93,   92,   88,   88,   84,   82,   50,   81,   80,

       79,   78,   77,   74,   73,   72,   71,   70,   69,   68,
       59,   50,   49,   48,   45,   42,   39,   36,   29,   25,
      306,    3,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306
    } ;

static yyconst short int yy_chk[667] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    5,    5,    6,    6,    8,   10,
       11,   10,   11,   13,   11,   15,   17,    8,   19,   32,
       15,   32,   13,   27,   17,   23,   23,   33,   19,   24,
       24,   44,   27,   36,   36,   75,   60,   78,   36,   75,
       79,   85,   86,  106,   33,   78,   88,  109,   44,   60,
      358,   88,   86,   79,   85,   86,  106,  327,  324,   88,

       88,  112,  316,   23,   35,  107,  311,  310,   35,   35,
       35,   35,   35,   35,  112,  107,  126,  153,  107,  121,
      121,  121,  309,  303,  109,  226,  226,  226,  295,  126,
      153,   35,   62,   62,   62,   62,   62,   62,   62,   62,
       90,   90,   90,   90,   90,   90,   90,   90,  120,  120,
      120,  120,  120,  120,  120,  120,  134,  135,  147,  147,
      147,  147,  176,  291,  242,  147,  242,  176,  290,  134,
      134,  135,  142,  154,  289,  176,  142,  142,  142,  142,
      142,  142,  268,  154,  268,  287,  154,  168,  247,  247,
      247,  168,  168,  168,  168,  168,  168,  171,  171,  171,

      171,  171,  171,  171,  171,  183,  183,  183,  183,  183,
      183,  188,  229,  229,  229,  229,  229,  229,  265,  265,
      265,  293,  293,  293,  188,  190,  190,  190,  190,  190,
      190,  190,  190,  195,  195,  195,  195,  195,  195,  195,
      195,  209,  209,  209,  209,  209,  209,  209,  209,  212,
      215,  216,  253,  253,  253,  253,  281,  280,  279,  253,
      278,  216,  212,  215,  216,  219,  219,  219,  219,  219,
      219,  219,  219,  225,  225,  225,  225,  225,  225,  225,
      225,  236,  236,  236,  236,  236,  236,  236,  236,  239,
      240,  273,  273,  273,  273,  276,  275,  274,  273,  266,

      240,  263,  239,  240,  246,  246,  246,  246,  246,  246,
      246,  246,  256,  256,  256,  256,  256,  256,  256,  256,
      264,  264,  264,  264,  264,  264,  264,  264,  277,  277,
      277,  277,  277,  277,  277,  277,  286,  286,  286,  286,
      294,  262,  261,  286,  292,  292,  292,  292,  292,  292,
      292,  292,  304,  294,  302,  302,  302,  302,  305,  260,
      259,  302,  258,  257,  255,  304,  254,  248,  305,  245,
      244,  305,  307,  307,  307,  308,  308,  243,  308,  312,
      238,  312,  237,  312,  313,  313,  314,  314,  315,  235,
      315,  234,  315,  317,  317,  318,  318,  319,  319,  320,

      320,  321,  321,  322,  322,  323,  232,  323,  231,  323,
      325,  325,  326,  326,  328,  230,  328,  227,  328,  329,
      329,  330,  330,  331,  331,  332,  332,  333,  333,  334,
      334,  335,  335,  336,  224,  336,  223,  336,  337,  337,
      338,  338,  339,  339,  340,  340,  341,  341,  342,  342,
      343,  343,  344,  344,  345,  345,  346,  346,  222,  346,
      347,  347,  348,  348,  349,  349,  350,  350,  351,  351,
      352,  352,  353,  353,  354,  354,  355,  355,  356,  356,
      357,  357,  359,  359,  360,  360,  361,  361,  362,  221,
      362,  220,  362,  218,  217,  214,  213,  211,  210,  208,

      207,  206,  202,  201,  200,  198,  197,  196,  194,  193,
      192,  191,  189,  186,  185,  184,  181,  180,  179,  178,
      177,  175,  174,  173,  172,  170,  169,  167,  165,  164,
      163,  162,  161,  160,  159,  158,  157,  156,  155,  151,
      150,  148,  143,  140,  139,  133,  132,  131,  130,  129,
      128,  127,  125,  124,  123,  122,  119,  118,  117,  116,
      115,  114,  113,  111,  110,  105,  103,  102,  101,  100,
       99,   98,   97,   96,   94,   93,   92,   91,   89,   87,
       84,   81,   80,   77,   74,   72,   71,   70,   68,   67,
       66,   65,   64,   63,   61,   59,   54,   53,   50,   49,

       48,   47,   46,   43,   42,   41,   40,   39,   38,   37,
       34,   22,   21,   20,   18,   16,   14,   12,    9,    7,
        3,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "filter.l"
#define INITIAL 0
#line 2 "filter.l"
/*
  filename: filter.l

  description:
    Defines the tokenizer for an RPSL filter attribute.  It was mostly
    stolen from the IRRToolSet, simplified by removing ability to parse
    things defined by a dictionary (we use XML for extensibility rather
    than a dictionary).

  notes:
    Tokens are defined in the associated grammar, filter.y.

  $Id: filter.l,v 1.1 2004/12/27 17:52:38 can Exp $
*/
#line 34 "filter.l"
#include <stdlib.h>
#include <ctype.h>

/* tokens defined in the grammar */
#include "filter.tab.h"

#define filterwrap yywrap
void syntax_error(char *fmt, ...);
void yy_input(char *buf, int *result, int max_size);
#undef YY_INPUT
#define YY_INPUT(buf,result,max_size) yy_input(buf,&result,max_size)
#line 668 "filter.lex.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 47 "filter.l"


#line 822 "filter.lex.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 307 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 622 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 49 "filter.l"
{ ; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 51 "filter.l"
{ return OP_OR; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 52 "filter.l"
{ return OP_AND; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 53 "filter.l"
{ return OP_NOT; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 54 "filter.l"
{ return OP_EQUAL; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 55 "filter.l"
{ return OP_COMPARE; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 56 "filter.l"
{ return OP_APPEND; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 59 "filter.l"
{ return OP_MS; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 60 "filter.l"
{ return OP_MS; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 61 "filter.l"
{ 
    long int val;
    val = strtol(yytext+1, NULL, 10);
    if ((val < 0) || (val > 32)) {
        syntax_error("more specifics operator \"%s\" not 0 to 32 bits", 
                     yytext);
    }
    return OP_MS;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 70 "filter.l"
{
    long int val1, val2;
    char *p;
    val1 = strtol(yytext+1, &p, 10);
    if ((val1 < 0) || (val1 > 32)) {
        syntax_error("more specifics operator \"%s\" not 0 to 32 bits", 
                     yytext);
    }
    val2 = strtol(p+1, NULL, 10);
    if ((val2 < 0) || (val2 > 32)) {
        syntax_error("more specifics operator \"%s\" not 0 to 32 bits", 
                     yytext);
    }
    if (val2 < val1) {
        syntax_error("more specifics operator \"%s\" not 0 to 32 bits", 
                     yytext);
    }
    return OP_MS;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 91 "filter.l"
{ return KEYW_ANY; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 92 "filter.l"
{ return KEYW_PEERAS; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 94 "filter.l"
{ return KEYW_IGP_COST; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 95 "filter.l"
{ return KEYW_SELF; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 96 "filter.l"
{ return KEYW_PREPEND; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 97 "filter.l"
{ return KEYW_APPEND; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 98 "filter.l"
{ return KEYW_DELETE; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 99 "filter.l"
{ return KEYW_CONTAINS; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 101 "filter.l"
{ return KEYW_INTERNET; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 102 "filter.l"
{ return KEYW_NO_EXPORT; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 103 "filter.l"
{ return KEYW_NO_ADVERTISE; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 105 "filter.l"
{ return TKN_PREF; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 106 "filter.l"
{ return TKN_MED; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 107 "filter.l"
{ return TKN_DPA; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 108 "filter.l"
{ return TKN_ASPATH; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 109 "filter.l"
{ return TKN_COMMUNITY; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 110 "filter.l"
{ return TKN_NEXT_HOP; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 111 "filter.l"
{ return TKN_COST; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 113 "filter.l"
{ return ASPATH_POSTFIX; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 114 "filter.l"
{ return ASPATH_POSTFIX; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 115 "filter.l"
{ return ASPATH_POSTFIX; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 116 "filter.l"
{ return ASPATH_POSTFIX; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 117 "filter.l"
{ return ASPATH_POSTFIX; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 119 "filter.l"
{
    return TKN_ASNO;
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 123 "filter.l"
{
    return TKN_FLTRNAME;
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 127 "filter.l"
{
    return TKN_ASNAME;
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 131 "filter.l"
{
    return TKN_RSNAME;
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 135 "filter.l"
{
    /* check each number of 1.2.3.4/5 in prefix is valid */
    long int val;
    char *s, *p;
    p = s = yytext;
    while (*s != '/') {
        val = strtol(p, &s, 10);
        if ((val < 0) || (val > 255)) {
             syntax_error("IP prefix \"%s\" contains an invalid octet", 
                          yytext);
        }
        p = s + 1;
    }
    val = strtol(p, NULL, 10);
    if ((val < 0) || (val > 32)) {
        syntax_error("IP prefix \"%s\" contains an invalid prefix length", 
                     yytext);
    }
    return TKN_PRFXV4;
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 156 "filter.l"
{
    /* check each number of 1.2.3.4/5 in prefix is valid, as
       well as any bit ranges specified */
    long int val;
    long int endval;
    char *s, *p;
    p = s = yytext;
    while (*s != '/') {
        val = strtol(p, &s, 10);
        if ((val < 0) || (val > 255)) {
             syntax_error("IP prefix \"%s\" contains an invalid octet", 
                          yytext);
        }
        p = s + 1;
    }
    val = strtol(p, &s, 10);
    if ((val < 0) || (val > 32)) {
        syntax_error("IP prefix range \"%s\" contains an invalid prefix length",
                     yytext);
    }
    p = s + 1;
    if (isdigit((int)*p)) {
        val = strtol(p, &s, 10);
        if ((val < 0) || (val > 32)) {
            syntax_error("IP prefix range \"%s\" contains an invalid range",
                         yytext);
        }
        p = s + 1;
        if (isdigit((int)*p)) {
            endval = strtol(p, NULL, 10);
            if ((endval < 0) || (endval > 32)) {
                syntax_error("IP prefix \"%s\" contains an invalid prefix range", 
                             yytext);
            }
            if (endval < val) {
                syntax_error("IP prefix \"%s\" range end is less than range start",
                             yytext);
            }
        }
    }
    return TKN_PRFXV4RNG;
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 199 "filter.l"
{
    /* check each number of 1.2.3.4 is valid */
    long int val;
    char *s, *p;
    p = s = yytext;
    while (*s != '\0') {
        val = strtol(p, &s, 10);
        if ((val < 0) || (val > 255)) {
             syntax_error("IP address \"%s\" contains an invalid octet",
                          yytext);
        }
        p = s + 1;
    }
    return TKN_IPV4;
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 215 "filter.l"
{
    /* verify each part is a 16-bit number */
    long int val;
    char *s, *p;
    p = s = yytext;
    while (*s != '\0') {
        val = strtol(p, &s, 10);
        if ((val < 0) || (val > 65535)) {
             syntax_error("Community number \"%s\" contains an invalid number",
                           yytext);
        }
        p = s + 1;
    }
    return TKN_COMM_NO;
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 231 "filter.l"
{
    filterlval.sval = yytext;
    return TKN_INT;
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 236 "filter.l"
{ return yytext[0]; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 238 "filter.l"
ECHO;
	YY_BREAK
#line 1255 "filter.lex.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 307 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 307 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 306);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 238 "filter.l"


void
filter_reset ()
{
    yy_flush_buffer(YY_CURRENT_BUFFER);
}


