#define yy_create_buffer import_create_buffer
#define yy_delete_buffer import_delete_buffer
#define yy_scan_buffer import_scan_buffer
#define yy_scan_string import_scan_string
#define yy_scan_bytes import_scan_bytes
#define yy_flex_debug import_flex_debug
#define yy_init_buffer import_init_buffer
#define yy_flush_buffer import_flush_buffer
#define yy_load_buffer_state import_load_buffer_state
#define yy_switch_to_buffer import_switch_to_buffer
#define yyin importin
#define yyleng importleng
#define yylex importlex
#define yyout importout
#define yyrestart importrestart
#define yytext importtext
#define yywrap importwrap

#line 20 "import.lex.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 56
#define YY_END_OF_BUFFER 57
static yyconst short int yy_accept[326] =
    {   0,
        0,    0,   57,   55,    1,    1,   55,   53,    6,   54,
       55,   54,   54,   54,   54,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   55,   55,    1,    7,    0,    0,
       53,    0,   54,    5,    9,    8,   10,   54,   54,   54,
       54,   25,   54,   54,   54,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,    2,   54,   54,
       54,   54,   54,   54,   54,   54,   54,    0,   39,   40,
        0,    0,   52,    0,   54,   54,    3,   12,   54,    0,
       44,   54,   54,   31,   54,   54,   54,   54,   34,   54,
       54,   54,   54,   54,   54,    0,   33,   54,   54,    0,

        4,   54,   54,   54,   54,   54,   54,   54,   31,    0,
       54,   54,    0,    0,   11,   54,   54,   54,    0,   46,
        0,    0,   54,   54,   54,   38,   54,   54,   54,   30,
        0,   54,   27,   54,   54,   54,    0,    0,   54,    0,
       32,   54,   54,   54,   54,   54,    0,   47,    0,   16,
       54,    0,    0,   54,   54,   54,    0,   46,    0,    0,
        0,    0,   54,   54,   54,   54,   54,    0,    0,   54,
        0,    0,    0,   54,   54,   54,   54,    0,   54,   54,
        0,   47,   54,    0,   41,    0,   21,   14,   18,    0,
        0,    0,    0,    0,    0,    0,   35,   54,   54,   19,

       29,    0,   45,    0,    0,   54,    0,    0,    0,   13,
       54,    0,   48,    0,   54,   28,    0,    0,    0,    0,
       43,   51,    0,    0,    0,    0,    0,    0,    0,    0,
       54,   54,    0,   45,    0,   54,    0,    0,    0,   17,
        0,   48,   54,    0,    0,    0,    0,    0,    0,   46,
        0,    0,    0,    0,   54,   20,    0,    0,    0,   15,
       22,   37,    0,    0,    0,    0,   26,   47,    0,    0,
        0,   50,    0,   46,    0,    0,    0,    0,   36,    0,
        0,    0,    0,   23,    0,    0,    0,    0,    0,   47,
       42,    0,    0,    0,   45,    0,    0,    0,   48,    0,

        0,    0,   49,   49,   46,    0,    0,    0,    0,    0,
       47,    0,    0,    0,   24,    0,    0,   49,    0,   45,
       45,   48,    0,   48,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,   10,   10,   10,
       10,   11,   10,   10,   10,   10,   10,   12,    1,    1,
       13,    1,    1,    1,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   26,   27,   28,   29,   30,   31,
       26,   32,   33,   34,   35,   36,   26,   37,   38,   26,
        1,    1,    1,   15,   16,    1,   17,   18,   19,   20,

       21,   22,   23,   24,   25,   26,   26,   27,   28,   29,
       30,   31,   26,   32,   33,   34,   35,   36,   26,   37,
       38,   26,   39,    1,   40,   41,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[42] =
    {   0,
        1,    1,    1,    1,    1,    1,    2,    3,    1,    2,
        2,    3,    1,    4,    1,    5,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    1,    1,
        1
    } ;

static yyconst short int yy_base[339] =
    {   0,
        0,    0,  902,  903,   40,   42,  888,   39,  887,   45,
       49,   54,   56,   62,   69,   86,   89,   95,  101,  118,
       82,  111,  117,   50,  874,  115,  143,  903,   74,  141,
      148,  151,  156,  903,  903,  903,  159,  164,  166,  172,
      180,  187,  189,  198,  179,  186,  124,  195,  193,  152,
      204,  209,  230,  232,  104,  222,  231,  233,  238,  168,
      225,  247,  253,  259,  274,  280,  286,  869,  903,  903,
      872,  289,  238,  285,  280,  281,  283,  289,  295,   51,
       79,  301,  298,  303,  304,  313,  316,  319,  321,  331,
      333,  334,  348,  336,  349,  350,  351,  363,  364,  200,

      365,  378,  380,  399,  401,  391,  392,  397,  404,  424,
      412,  413,  861,  367,  381,  420,  425,  427,  445,  450,
      386,  446,  442,  450,  457,  458,  459,  466,  493,  495,
      875,  483,  485,  489,  491,  500,  871,  853,  502,  507,
      505,  516,  535,  537,  523,  528,  546,  552,  412,  540,
      533,   49,  459,  549,  549,  556,  300,  568,  854,  859,
      328,  850,  563,  565,  570,  572,  578,  593,  852,  582,
      855,  842,  844,  585,  593,  596,  594,  621,  611,  611,
      614,  626,  628,  233,  903,  406,  627,  629,  630,  841,
      849,  656,  832,  842,  833,  852,  643,  644,  648,  649,

      650,  673,  678,  423,  825,  663,  824,  829,  807,  689,
      691,  686,  698,  697,  708,  710,  779,  780,  739,  720,
      903,  647,  714,  722,  712,  696,  701,  698,  686,  716,
      719,  706,  719,  730,  657,  711,  655,  642,  638,  725,
      467,  740,  728,  749,  620,  632,  586,  752,  757,  755,
      581,  599,  584,  583,  745,  746,  544,  544,  534,  903,
      747,  903,  516,  505,  493,  500,  748,  774,  479,  775,
      469,  777,  782,  783,  479,  786,  461,  787,  777,  786,
      438,  423,  379,  903,  794,  366,  314,  322,  800,  801,
      903,  804,  278,  277,  808,  251,  238,  230,  811,  201,

      208,  190,  903,  817,  165,  160,  148,  114,  112,  110,
      100,  815,  822,   71,  903,   45,  823,  821,  826,  828,
       60,   36,  827,  829,  903,  844,  847,  851,  855,  859,
      863,  867,  871,  875,  879,  883,  887,  891
    } ;

static yyconst short int yy_def[339] =
    {   0,
      325,    1,  325,  325,  325,  325,  325,  326,  325,  326,
      325,  326,  326,  326,  326,  326,  326,  326,  326,  326,
       18,   18,   22,   22,  325,  325,  325,  325,   22,  325,
      326,  325,  326,  325,  325,  325,  325,  326,  326,  326,
      326,  326,  326,  326,   18,   18,   18,   18,   18,   18,
       22,   22,  326,  326,   18,   18,   18,   18,   18,   22,
       22,   22,   22,   22,  326,  326,  326,  325,  325,  325,
      325,  325,  325,  325,   22,   22,   22,   22,   22,  327,
       41,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,  325,

       22,   22,   22,  326,  326,   18,   18,   22,   18,  328,
       18,   18,  325,  325,  325,   18,   18,   18,  327,  327,
      329,  325,   18,   18,   18,   18,   18,   18,  326,  326,
      325,   22,   22,   18,   18,   18,  325,  325,   18,   18,
       18,   22,  326,  326,   18,   18,  328,  328,  330,   18,
       22,  325,  325,   22,   18,   18,  325,  329,  325,  325,
      325,  325,   18,   18,   22,   22,   22,  331,  325,   18,
      325,  325,  325,   18,   18,   18,   18,  332,   18,   22,
      325,  330,   22,  325,  325,  325,   22,   22,   22,  325,
      325,  325,  325,  325,  325,  325,   22,   22,   18,   18,

       18,  331,  331,  333,  325,   22,  325,  325,  325,  326,
      326,  332,  332,  334,  326,  326,  325,  325,  325,  325,
      325,  325,  325,  325,  329,  325,  325,  325,  325,  330,
      326,   18,  325,  333,  325,   18,  325,  325,  325,   18,
      325,  334,   18,  325,  325,  325,  325,  325,  335,  325,
      325,  325,  325,  325,   18,   18,  325,  325,  325,  325,
       18,  325,  325,  325,  325,  325,   18,  325,  325,  336,
      325,  325,  335,  335,  325,  333,  325,  334,   18,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  336,  336,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,

      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  337,  325,  325,  325,  338,  325,  337,  337,
      325,  325,  338,  338,    0,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325
    } ;

static yyconst short int yy_nxt[945] =
    {   0,
        4,    5,    6,    4,    4,    4,    4,    7,    4,    8,
        8,    4,    9,   10,   11,    4,   12,   13,   14,   15,
       16,   17,   10,   10,   18,   10,   10,   19,   20,   21,
       22,   23,   24,   10,   10,   10,   10,   10,   25,    4,
       26,   27,   27,   27,   27,   29,   30,  241,   31,   31,
       32,   29,  325,   35,  184,   36,  325,  119,   37,   37,
       29,  325,   29,  325,   33,  325,  121,  325,   29,  325,
       66,  233,   38,  325,   33,   29,  325,  322,   43,   44,
      325,   33,   39,   67,   40,   29,   41,   42,  185,   46,
      122,   45,   29,  325,   33,   29,  325,  325,   33,   47,

      325,   29,  325,  321,   33,   33,  325,   29,  325,   33,
       33,  181,  325,   58,   59,   49,  317,   51,   69,   70,
       50,   54,   48,   52,   29,  325,   33,   53,  316,  325,
       55,   60,   33,   33,  315,   61,   98,   63,   56,   33,
       89,   64,   62,   33,   27,   27,   33,   57,   33,   65,
       72,   72,   33,   71,   29,   30,   33,   31,   31,   32,
       73,   73,   29,  325,  314,   74,  313,  325,   37,   37,
       29,  325,   29,  325,   33,  325,  157,  325,   29,  325,
       33,   92,   75,  325,   33,   77,   80,  325,  103,   81,
       81,  325,   33,   29,  325,   29,  325,   76,  325,   33,

      325,   33,   79,   78,   29,  325,   85,   86,   33,  325,
       82,   87,   88,   90,   33,   33,  137,   33,   33,   83,
      138,   33,  311,   33,   33,   33,   91,   33,   33,   33,
      310,   84,  309,   33,   93,   94,   96,  325,   29,  325,
       33,  325,   95,  325,   33,   33,  100,   73,   73,   33,
       33,   97,  104,   33,   33,   33,   33,  220,   99,   33,
       33,   33,  308,   33,  101,   33,   33,  105,  102,  307,
       33,   33,  221,   33,  108,  106,  107,   33,   33,   33,
      110,  325,  306,   33,   33,  325,   29,  325,  122,  109,
       33,  325,   29,  325,  115,  115,  114,  325,   72,   72,

      116,   33,  112,   33,   33,  117,  111,   33,   84,   33,
      305,   33,   33,   33,   33,  118,  190,  123,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
      191,  124,   33,   33,   33,   33,   33,   33,  302,  127,
       33,   33,  301,   33,   33,   33,  125,   33,  194,  126,
       33,  128,   33,   33,   33,   33,   33,   33,   33,  195,
       33,  130,   33,  131,  129,   33,   84,   33,   33,  132,
       33,   33,   33,   33,  134,   33,  153,  153,  133,   33,
       33,   33,   33,   33,   33,   33,  300,   33,   33,   33,
      115,  115,  121,  135,   33,   33,   33,  136,   33,   84,

       33,  121,   33,  298,   33,  140,  325,   29,  325,   33,
      325,  139,  325,  143,   33,  222,  222,   33,  149,   33,
       33,  145,  141,   33,   33,  144,   33,  149,   33,  204,
      147,  142,  146,  150,   33,   33,   33,   33,  204,  149,
       33,   33,   33,  297,   33,   33,  151,   33,   33,   33,
      154,  119,   33,   33,  155,  156,  119,   33,   33,   33,
      121,  157,  159,   33,   33,  121,  186,  160,  153,  153,
       33,  296,   33,  165,   33,  163,  161,  162,   33,   33,
       33,   33,   33,  265,  164,   33,   33,   33,   33,   33,
       33,   33,  166,  294,   33,  293,  167,  266,   33,  168,

      325,   29,  325,   33,  325,   33,  325,   33,  291,   33,
      288,   33,   84,   33,  170,  171,   33,   33,  174,   33,
      286,   84,   33,   33,   33,  285,  175,   33,   33,   33,
       33,  287,   33,   33,   33,   33,  177,   33,  284,  176,
       33,  178,  325,   29,  325,   33,  325,   33,  325,  283,
       84,  180,  147,   33,  282,   33,   33,  183,  147,   33,
       33,  149,   33,  181,   33,   33,  179,  149,   33,   33,
      281,   33,   33,   33,  121,  189,  280,  188,   33,  157,
       33,   33,  187,  121,   33,   33,  197,   33,   33,  278,
       33,   33,  200,  198,  199,   33,   33,   33,   33,  202,

      277,   33,   33,   33,   33,  276,   33,   33,  204,   33,
      206,  201,  275,   33,   33,   33,   33,  210,   33,  271,
       84,   33,  211,   84,   33,   33,   33,  212,   33,  215,
      217,  216,  149,   33,   33,   33,  214,  181,  270,   33,
      269,  149,   33,   33,  218,  219,   84,   33,   33,   33,
       33,   33,   33,   33,   33,  248,  222,  222,   33,   33,
       33,   33,  225,   33,   33,  226,  226,   33,  231,  264,
       33,   33,   33,  263,   33,   33,  232,   33,   33,  202,
       33,   33,   33,  236,  202,  262,   33,   33,  204,  233,
      260,   33,  212,  204,   33,   29,  325,   29,  325,   33,

      122,  214,  325,  214,  212,  226,  226,  122,  254,  241,
      240,   33,  214,  214,   29,  325,   29,  325,  121,  325,
      249,  325,  149,  250,  250,   29,  325,  121,   33,  253,
      325,  149,  252,   33,   33,  257,  204,  243,  256,   33,
      258,  233,  251,   33,  261,  204,  214,   33,  247,  259,
       33,  241,  255,   33,  267,  214,   33,   33,  268,  268,
       33,  272,  272,  273,  250,  250,  157,   33,   33,   33,
       33,  246,  273,   33,   33,   33,   33,   33,   33,   33,
       33,  289,  279,  268,  268,  181,  272,  272,  273,  273,
      289,  292,  204,  214,  157,  295,  295,  273,  273,   33,

      245,  204,  214,  299,  299,   33,  289,  289,  303,   33,
      303,  244,  181,  304,  304,  289,  289,  295,  295,  233,
      299,  299,  241,  312,  318,  318,  304,  304,  319,  323,
      318,  318,  319,  323,  319,  323,  239,  319,  323,  233,
      241,  319,  323,  319,  323,   33,   33,   33,  120,  238,
      120,  120,  148,  237,  148,  148,  158,  235,  230,  158,
      182,  229,  228,  182,  203,  227,  203,  203,  213,  224,
      213,  213,  234,  223,  209,  234,  242,  208,  207,  242,
      274,  205,  196,  274,  290,  193,  192,  290,  320,  173,
      172,  320,  324,  169,  152,  324,   68,  113,   68,   34,

       28,  325,    3,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325
    } ;

static yyconst short int yy_chk[945] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    5,    6,    6,    8,    8,  322,    8,    8,
        8,   10,   10,   11,  152,   11,   10,   80,   11,   11,
       12,   12,   13,   13,   80,   12,   80,   13,   14,   14,
       24,  321,   12,   14,   24,   15,   15,  316,   13,   14,
       15,   24,   12,   24,   12,   81,   12,   12,  152,   15,
       81,   14,   16,   16,   29,   17,   17,   16,   29,   15,

       17,   18,   18,  314,   21,   29,   18,   19,   19,   81,
       21,  311,   19,   21,   21,   17,  310,   18,   26,   26,
       17,   19,   16,   18,   20,   20,   55,   18,  309,   20,
       19,   22,   55,   22,  308,   22,   55,   23,   20,   22,
       47,   23,   22,   22,   27,   27,   47,   20,   23,   23,
       30,   30,   47,   26,   31,   31,   47,   31,   31,   31,
       32,   32,   33,   33,  307,   37,  306,   33,   37,   37,
       38,   38,   39,   39,   50,   38,  305,   39,   40,   40,
       50,   50,   38,   40,   50,   39,   41,   41,   60,   41,
       41,   41,   60,   42,   42,   43,   43,   38,   42,   60,

       43,   45,   40,   39,   44,   44,   45,   45,   46,   44,
       41,   45,   46,   48,   46,   49,  100,   48,   46,   43,
      100,   49,  302,   48,   51,   49,   49,   48,   51,   52,
      301,   44,  300,   52,   51,   51,   53,   53,   54,   54,
       52,   53,   52,   54,   56,   61,   57,   73,   73,   61,
       56,   54,   61,   57,   56,   58,   61,  184,   56,   57,
       59,   58,  298,   57,   57,   58,   59,   62,   59,  297,
       59,   62,  184,   63,   63,   62,   62,   63,   62,   64,
       65,   65,  296,   64,   63,   65,   66,   66,  294,   64,
       64,   66,   67,   67,   74,   74,   72,   67,   72,   72,

       75,   76,   67,   77,   75,   76,   66,   77,   83,   78,
      293,   75,   76,   78,   77,   79,  157,   82,   83,   79,
       78,   82,   83,   84,   85,   82,   79,   84,   85,   83,
      157,   85,   82,   86,   84,   85,   87,   86,  288,   88,
       87,   89,  287,   88,   86,   89,   86,   87,  161,   87,
       88,   90,   89,   91,   92,   90,   94,   91,   92,  161,
       94,   92,   90,   93,   91,   92,   94,   94,   93,   95,
       96,   97,   93,   95,   96,   97,  114,  114,   95,   93,
       95,   96,   97,   98,   99,  101,  286,   98,   99,  101,
      115,  115,  121,   98,   98,   99,  101,   99,  102,  102,

      103,  121,  102,  283,  103,  104,  104,  105,  105,  102,
      104,  103,  105,  106,  107,  186,  186,  108,  149,  106,
      107,  108,  105,  106,  107,  107,  109,  149,  108,  204,
      110,  105,  109,  111,  111,  112,  109,  110,  204,  110,
      111,  112,  116,  282,  111,  112,  112,  117,  116,  118,
      116,  119,  116,  117,  117,  118,  120,  117,  119,  118,
      119,  120,  122,  120,  123,  120,  153,  122,  153,  153,
      123,  281,  124,  125,  123,  123,  122,  122,  124,  125,
      126,  127,  124,  241,  124,  125,  126,  127,  128,  125,
      126,  127,  127,  277,  128,  275,  128,  241,  128,  129,

      129,  130,  130,  132,  129,  133,  130,  132,  271,  133,
      269,  134,  135,  135,  132,  136,  133,  134,  139,  135,
      266,  134,  136,  135,  139,  265,  140,  141,  136,  140,
      139,  266,  136,  141,  139,  140,  142,  141,  264,  140,
      142,  143,  143,  144,  144,  145,  143,  142,  144,  263,
      146,  145,  147,  151,  259,  145,  146,  151,  148,  147,
      146,  147,  150,  148,  151,  148,  144,  148,  150,  154,
      258,  155,  150,  154,  158,  156,  257,  155,  156,  158,
      154,  155,  154,  158,  156,  163,  163,  164,  156,  254,
      165,  163,  166,  164,  165,  163,  166,  164,  167,  168,

      253,  165,  167,  166,  170,  252,  168,  174,  168,  167,
      170,  167,  251,  174,  170,  175,  177,  174,  176,  247,
      175,  175,  177,  176,  176,  175,  177,  178,  176,  179,
      181,  180,  182,  179,  178,  180,  178,  182,  246,  179,
      245,  182,  180,  179,  181,  181,  183,  187,  183,  188,
      189,  187,  183,  188,  189,  222,  222,  222,  187,  183,
      188,  189,  192,  197,  198,  192,  192,  197,  198,  239,
      199,  200,  201,  238,  197,  198,  199,  200,  201,  202,
      199,  200,  201,  206,  203,  237,  202,  206,  202,  203,
      235,  203,  212,  203,  206,  210,  210,  211,  211,  212,

      210,  212,  211,  214,  213,  226,  226,  226,  229,  213,
      211,  213,  214,  213,  215,  215,  216,  216,  225,  215,
      223,  216,  230,  223,  223,  231,  231,  225,  232,  228,
      231,  230,  227,  236,  232,  233,  234,  215,  232,  236,
      233,  234,  224,  236,  236,  234,  242,  240,  220,  233,
      243,  242,  231,  240,  243,  242,  243,  240,  244,  244,
      243,  248,  248,  249,  250,  250,  250,  255,  256,  261,
      267,  219,  249,  255,  256,  261,  267,  255,  256,  261,
      267,  270,  255,  268,  268,  268,  272,  272,  273,  274,
      270,  272,  276,  278,  274,  280,  280,  273,  274,  279,

      218,  276,  278,  285,  285,  279,  289,  290,  292,  279,
      292,  217,  290,  292,  292,  289,  290,  295,  295,  295,
      299,  299,  299,  304,  312,  312,  304,  304,  313,  317,
      318,  318,  319,  323,  320,  324,  209,  313,  317,  320,
      324,  319,  323,  320,  324,  326,  326,  326,  327,  208,
      327,  327,  328,  207,  328,  328,  329,  205,  196,  329,
      330,  195,  194,  330,  331,  193,  331,  331,  332,  191,
      332,  332,  333,  190,  173,  333,  334,  172,  171,  334,
      335,  169,  162,  335,  336,  160,  159,  336,  337,  138,
      137,  337,  338,  131,  113,  338,   71,   68,   25,    9,

        7,    3,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "import.l"
#define INITIAL 0
#line 2 "import.l"
/*
  filename: import.l

  description:
    Defines the tokenizer for an RPSL import attribute.  It was mostly
    stolen from the IRRToolSet, simplified by removing ability to parse
    things defined by a dictionary (we use XML for extensibility rather
    than a dictionary).

  notes:
    Tokens are defined in the associated grammar, import.y.

  $Id: import.l,v 1.1 2004/12/27 17:52:38 can Exp $
*/
#line 33 "import.l"
#include <string.h>
#include <stdlib.h>
#include <ctype.h>

/* tokens defined in the grammar */
#include "import.tab.h"

#define importwrap yywrap
void syntax_error(char *fmt, ...);
void yy_input(char *buf, int *result, int max_size);
#undef YY_INPUT
#define YY_INPUT(buf,result,max_size) yy_input(buf,&result,max_size)
#line 727 "import.lex.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 47 "import.l"


#line 881 "import.lex.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 326 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 903 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 49 "import.l"
{ ; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 51 "import.l"
{ return OP_OR; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 52 "import.l"
{ return OP_AND; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 53 "import.l"
{ return OP_NOT; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 54 "import.l"
{ return OP_COMPARE; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 55 "import.l"
{ return OP_EQUAL; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 56 "import.l"
{ return OP_APPEND; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 58 "import.l"
{ return OP_MS; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 59 "import.l"
{ return OP_MS; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 60 "import.l"
{ 
    long int val;
    val = strtol(yytext+1, NULL, 10);
    if ((val < 0) || (val > 32)) {
        syntax_error("more specifics operator \"%s\" not 0 to 32 bits", 
                     yytext);
    }
    return OP_MS;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 69 "import.l"
{
    long int val1, val2;
    char *p;
    val1 = strtol(yytext+1, &p, 10);
    if ((val1 < 0) || (val1 > 32)) {
        syntax_error("more specifics operator \"%s\" not 0 to 32 bits", 
                     yytext);
    }
    val2 = strtol(p+1, NULL, 10);
    if ((val2 < 0) || (val2 > 32)) {
        syntax_error("more specifics operator \"%s\" not 0 to 32 bits", 
                     yytext);
    }
    if (val2 < val1) {
        syntax_error("more specifics operator \"%s\" not 0 to 32 bits", 
                     yytext);
    }
    return OP_MS;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 90 "import.l"
{ return KEYW_ANY; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 91 "import.l"
{ return KEYW_PEERAS; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 93 "import.l"
{ return KEYW_ACTION; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 94 "import.l"
{ return KEYW_IGP_COST; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 95 "import.l"
{ return KEYW_SELF; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 96 "import.l"
{ return KEYW_PREPEND; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 97 "import.l"
{ return KEYW_APPEND; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 98 "import.l"
{ return KEYW_DELETE; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 99 "import.l"
{ return KEYW_CONTAINS; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 100 "import.l"
{ return KEYW_ACCEPT; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 102 "import.l"
{ return KEYW_INTERNET; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 103 "import.l"
{ return KEYW_NO_EXPORT; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 104 "import.l"
{ return KEYW_NO_ADVERTISE; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 106 "import.l"
{ return KEYW_AT; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 107 "import.l"
{ return KEYW_PROTOCOL; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 108 "import.l"
{ return KEYW_INTO; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 109 "import.l"
{ return KEYW_REFINE; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 110 "import.l"
{ return KEYW_EXCEPT; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 111 "import.l"
{ return KEYW_FROM; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 113 "import.l"
{
    return TKN_PROTOCOL;
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 117 "import.l"
{ return TKN_PREF; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 118 "import.l"
{ return TKN_MED; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 119 "import.l"
{ return TKN_DPA; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 120 "import.l"
{ return TKN_ASPATH; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 121 "import.l"
{ return TKN_COMMUNITY; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 122 "import.l"
{ return TKN_NEXT_HOP; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 123 "import.l"
{ return TKN_COST; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 125 "import.l"
{ return ASPATH_POSTFIX; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 126 "import.l"
{ return ASPATH_POSTFIX; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 127 "import.l"
{ return ASPATH_POSTFIX; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 128 "import.l"
{ return ASPATH_POSTFIX; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 129 "import.l"
{ return ASPATH_POSTFIX; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 131 "import.l"
{
    long int val;
    char *s;
    val = strtol(yytext+2, &s, 10);
    if ((val < 0) || (val > 65535) || (*s != '\0')) {
        syntax_error("AS number \"%s\" is not between 0 and 65535", yytext);
    }
    return TKN_ASNO;
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 141 "import.l"
{
    return TKN_FLTRNAME;
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 145 "import.l"
{
    return TKN_ASNAME;
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 149 "import.l"
{
    return TKN_RSNAME;
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 153 "import.l"
{ 
    return TKN_PRNGNAME;
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 157 "import.l"
{
    /* check each number of 1.2.3.4/5 in prefix is valid, as
       well as any bit ranges specified */
    long int val;
    long int endval;
    char *s, *p;
    p = s = yytext;
    while (*s != '/') {
        val = strtol(p, &s, 10);
        if ((val < 0) || (val > 255)) {
             syntax_error("IP prefix \"%s\" contains an invalid octet", 
                          yytext);
        }
        p = s + 1;
    }
    val = strtol(p, &s, 10);
    if ((val < 0) || (val > 32)) {
        syntax_error("IP prefix range \"%s\" contains an invalid prefix length",
                     yytext);
    }
    p = s + 1;
    if (isdigit((int)*p)) {
        val = strtol(p, &s, 10);
        if ((val < 0) || (val > 32)) {
            syntax_error("IP prefix range \"%s\" contains an invalid range",
                         yytext);
        }
        p = s + 1;
        if (isdigit((int)*p)) {
            endval = strtol(p, NULL, 10);
            if ((endval < 0) || (endval > 32)) {
                syntax_error("IP prefix \"%s\" contains an invalid prefix range", 
                             yytext);
            }
            if (endval < val) {
                syntax_error("IP prefix \"%s\" range end is less than range start",
                             yytext);
            }
        }
    }
    return TKN_PRFXV4RNG;
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 200 "import.l"
{
    /* check each number of 1.2.3.4/5 in prefix is valid */
    long int val;
    char *s, *p;
    p = s = yytext;
    while (*s != '/') {
        val = strtol(p, &s, 10);
        if ((val < 0) || (val > 255)) {
             syntax_error("IP prefix \"%s\" contains an invalid octet", 
                          yytext);
        }
        p = s + 1;
    }
    val = strtol(p, NULL, 10);
    if ((val < 0) || (val > 32)) {
        syntax_error("IP prefix \"%s\" contains an invalid prefix length", 
                     yytext);
    }
    return TKN_PRFXV4;
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 221 "import.l"
{
    /* check each number of 1.2.3.4 is valid */
    long int val;
    char *s, *p;
    p = s = yytext;
    while (*s != '\0') {
        val = strtol(p, &s, 10);
        if ((val < 0) || (val > 255)) {
             syntax_error("IP address \"%s\" contains an invalid octet", 
                          yytext);
        }
        p = s + 1;
    }
    return TKN_IPV4;
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 237 "import.l"
{
    /* verify each part is a 16-bit number */
    long int val;
    char *s, *p;
    p = s = yytext;
    while (*s != '\0') {
        val = strtol(p, &s, 10);
        if ((val < 0) || (val > 65535)) {
             syntax_error("Community number \"%s\" contains an invalid number", 
                           yytext);
        }
        p = s + 1;
    }
    return TKN_COMM_NO;
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 253 "import.l"
{ 
    importlval.sval = yytext;
    return TKN_INT; 
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 258 "import.l"
{ 
    /* check the length */
    if (strlen(yytext) > 63) {
       syntax_error("Portion of domain name \"%s\" is longer "
                                                           "than 63 characters",
                    yytext); 
    }
    importlval.sval = yytext;
    return TKN_DNS; 
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 269 "import.l"
{ return yytext[0]; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 271 "import.l"
ECHO;
	YY_BREAK
#line 1388 "import.lex.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 326 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 326 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 325);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 271 "import.l"


void 
import_reset ()
{
    yy_flush_buffer(YY_CURRENT_BUFFER);
}

