#define yy_create_buffer inject_r6_create_buffer
#define yy_delete_buffer inject_r6_delete_buffer
#define yy_scan_buffer inject_r6_scan_buffer
#define yy_scan_string inject_r6_scan_string
#define yy_scan_bytes inject_r6_scan_bytes
#define yy_flex_debug inject_r6_flex_debug
#define yy_init_buffer inject_r6_init_buffer
#define yy_flush_buffer inject_r6_flush_buffer
#define yy_load_buffer_state inject_r6_load_buffer_state
#define yy_switch_to_buffer inject_r6_switch_to_buffer
#define yyin inject_r6in
#define yyleng inject_r6leng
#define yylex inject_r6lex
#define yyout inject_r6out
#define yyrestart inject_r6restart
#define yytext inject_r6text
#define yywrap inject_r6wrap

#line 20 "inject_r6.lex.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /srv/pubcvs/cvs/cvsroot/whois-server/src/modules/rpsl/inject_r6.lex.c,v 1.1 2004/12/27 16:38:45 can Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 48
#define YY_END_OF_BUFFER 49
static yyconst short int yy_accept[355] =
    {   0,
        0,    0,   49,   47,    1,    1,   47,   45,   47,    5,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,    1,    6,    0,    0,   45,
        0,   46,   46,   43,    4,    0,   46,   46,   46,   46,
       46,   17,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,    3,   46,   46,   46,   46,   46,
       46,    0,   45,   46,   44,    0,    0,   43,   46,   24,
        2,   46,   33,   46,   46,   46,   46,   46,   28,   46,
       46,   46,   46,   46,   46,   27,   46,    0,   46,   46,
       46,   46,   46,   46,    0,   45,   46,   44,    0,    0,

       40,   43,    0,   46,   46,    0,   46,   46,   46,   32,
       46,   46,   46,   46,    0,   46,   25,   25,   46,   46,
        0,    0,   46,   26,   46,   46,    9,   46,   19,    0,
       45,   44,    0,    0,    0,   43,   43,   46,   46,    0,
        0,    0,   46,   46,   46,   46,   46,   46,    0,    0,
       46,    0,    0,   46,    0,    0,    0,   46,   46,    0,
       46,    0,    0,   44,    0,    0,    0,   37,   37,   43,
       43,    0,    7,   11,    0,    0,    0,   29,   46,   46,
       12,   18,   46,   46,    0,   46,    0,    0,    0,    0,
       46,    0,    0,    0,   46,   46,    0,   34,    0,   20,

       41,   44,    0,    0,    0,   43,   43,    0,    0,    0,
       46,   46,   21,   46,    0,   46,    0,    0,    0,    0,
       23,    0,    0,    0,   10,    0,   34,    0,    0,    0,
        0,   37,   43,   43,    0,    0,    0,   46,   13,   46,
        8,   14,    0,    0,    0,    0,   31,    0,    0,    0,
        0,    0,   38,    0,    0,   43,   43,    0,    0,   30,
       46,    0,    0,    0,    0,    0,   15,    0,    0,    0,
        0,    0,    0,    0,   43,   43,    0,    0,   46,    0,
        0,    0,    0,    0,   34,    0,    0,   35,   35,    0,
        0,   43,   43,   46,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,   43,   43,    0,   46,    0,
       25,    0,   16,    0,    0,   35,    0,    0,   43,   43,
       46,    0,    0,   34,    0,   34,    0,    0,    0,   43,
       43,    0,   46,    0,   42,   43,   43,   22,    0,    0,
       42,   43,   43,   39,   42,   43,    0,   42,   43,   36,
       36,    0,   36,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    4,    1,    5,    6,    7,    8,    8,    8,
        8,    9,    8,   10,    8,    8,    8,   11,    1,    1,
       12,    1,    1,    1,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
       25,   32,   33,   34,   35,   36,   25,   37,   38,   25,
        1,    1,    1,   14,   15,    1,   16,   17,   18,   19,

       20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
       30,   31,   25,   32,   33,   34,   35,   36,   25,   37,
       38,   25,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[39] =
    {   0,
        1,    1,    1,    1,    2,    3,    4,    5,    5,    5,
        6,    1,    7,    1,    8,    5,    5,    5,    5,    5,
        5,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2
    } ;

static yyconst short int yy_base[415] =
    {   0,
        0,    0, 1089, 1090,   37,   39, 1076,   38, 1076, 1074,
       55,   62,   96, 1055,   31, 1047,   58,  113,  116,  120,
      123,  132,  140,  142,  127,   50, 1090,  132,  100,  171,
      157,  164,  188, 1076, 1090, 1071,  194,   96,  187,  179,
      221,  190,  204,  144,  191,  205,  217,  216,  220,  233,
      234,  239,  244,  256,  255,  260,  268,  271,  279,  276,
      282,  308,  311,  327,  314, 1070,  175,  162,  317,  318,
      321,  322,   34,  338,  333,  334,  344,  350,  354,  360,
      364,  375,  372,  390,  383,  386,  389,  195,  397,  403,
      408,  414,  418,  422,  286,  448,  455,  454, 1069, 1068,

      459,  233,    0,  465,  452,  456,  455,  463,  474,  471,
      475,  479,  485,  506, 1060,  513,  516,  520,  523,  527,
     1058, 1039,  530,  538,  542,  546,  549,  553,  560,  564,
     1064,  570, 1063, 1062,  578,  265,  272,  508,  570, 1039,
     1051, 1036,  562,  573,  574,  586,  578,  591,  596, 1039,
      597,  189,  403,  601, 1045, 1031, 1035,  602,  607,  629,
      619,  349,  559,  643, 1054, 1053, 1017, 1090,  650,  435,
      471,    0,  618,  634,  658, 1007,  993,  640,  648,  651,
      652,  656,  664,  667,  991,  670,  935,  940,  932,  937,
      678,  925,  933,  922,  697,  699,  701,  706,  118,  717,

      717,  721,  910,  898,  724,  583,  632,  727,  876,  870,
      734,  736,  738,  745,  851,  747,  857,  850,  844,  845,
      749,  829,  817,  811,  756,  732,  760,  768,  824,  816,
      780,  774,  650,  759,    0,  758,  767,  774,  781,  766,
     1090,  767,  725,  739,  712,  702, 1090,  681,  679,  679,
      674,  657,  791,  677,  665,  783,  795,  642,  155,  782,
      785,  640,  630,  621,  600,  587, 1090,  800,  577,  544,
      813,  564,  552,  550,  813,  818,    0,  545,  797,  522,
      482,  481,  458,  447,  822,  443,  422, 1090,  829,  439,
      437,  829,  834,  822,  417,  393,  406,  382,  393,  394,

      402,  838,  391,  385,  377,  843,  845,    0,  833,  344,
     1090,  341, 1090,  338,  508,  849,  334,  323,  854,  856,
      844,  292,  281,  298,  788,  865,  263,  249,  248,  861,
      870,    0,  857,  246,  234,  876,  218,  860,  203,  884,
      168,  888,  165,  888,  152,  150,  896,  134,  132, 1090,
      902,  905,  908, 1090,  917,  920,  923,  924,  927,  929,
      931,  934,  106,  936,  938,  941,  944,  949,  953,  955,
      958,   98,  963,  967,  969,  972,  975,  977,  979,  982,
       72,  984,  986,  989,  992,  994,  996,  999,   71, 1001,
     1003, 1006, 1009, 1011, 1013, 1016,   63, 1021, 1025, 1027,

     1030, 1033, 1035, 1037, 1040,   45, 1042, 1045, 1047, 1050,
     1052, 1054, 1056, 1058
    } ;

static yyconst short int yy_def[415] =
    {   0,
      354,    1,  354,  354,  354,  354,  354,  355,  354,  354,
      355,  354,  355,   13,   13,   13,  355,  355,  355,  355,
      355,  355,  355,  355,   18,  354,  354,   18,  354,   13,
      356,   18,   30,  357,  354,  356,   30,   37,   18,   18,
       18,   18,   18,   37,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,  354,   30,   63,  358,  358,  354,  359,   18,   18,
       18,   18,   41,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   41,   18,   18,   18,  354,   18,   18,
       18,   18,   18,   18,  354,   41,  355,  360,  361,  360,

      354,  362,  363,  355,   18,  354,   18,   18,   18,   18,
       18,   18,   18,  355,  354,  355,  355,  355,  355,  355,
      354,  354,  355,  355,  355,  355,  355,  355,  355,  354,
       96,  364,  364,  365,  354,  366,  367,   18,   18,  354,
      354,  354,   18,   18,   18,   18,   18,   18,   18,  354,
       18,  354,  354,   18,  354,  354,  354,   18,   18,  368,
       18,  354,  354,  354,  354,  369,  370,  354,  354,  354,
      371,  372,   18,   18,  354,  354,  354,   18,   18,   18,
       18,   18,   18,   18,  354,   18,  354,  354,  354,  354,
       18,  354,  354,  354,  355,  355,  368,  368,  373,  355,

      354,  354,  374,  375,  354,  376,  377,  354,  354,  354,
      355,  355,  355,  355,  354,  355,  354,  354,  354,  354,
      355,  354,  354,  354,  355,  354,  373,  354,  354,  378,
      379,  354,  354,  380,  381,  354,  354,  355,  355,   18,
      354,   18,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  382,  383,  384,  385,  354,  373,   18,
       18,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  386,  387,  354,  388,  389,  354,   18,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  390,
      391,  392,  393,   18,  354,  354,  354,  354,  354,  354,

      354,  354,  354,  394,  395,  354,  396,  397,   18,  354,
      354,  354,  354,  354,  398,  354,  399,  400,  401,  402,
       18,  354,  354,  354,  398,  398,  354,  403,  404,  354,
      405,  406,   18,  407,  408,  409,  410,   18,  354,  354,
      411,  354,  412,  354,  413,  414,  354,  354,  354,  354,
      354,  354,  354,    0,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,

      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354
    } ;

static yyconst short int yy_nxt[1129] =
    {   0,
        4,    5,    6,    4,    4,    7,    4,    8,    8,    8,
        9,   10,   11,    4,    4,   12,   13,   14,   15,   16,
       13,   11,   17,   18,   11,   11,   11,   19,   20,   21,
       22,   23,   24,   11,   25,   11,   11,   11,   26,   26,
       26,   26,   28,   29,  106,   30,   30,   30,   31,  337,
       44,   26,   26,   33,   33,   33,   33,   33,   33,   28,
      354,   45,   28,  354,   32,  354,   28,  320,  354,   33,
       33,   33,   36,   47,   32,  293,  257,   33,   33,   37,
       33,   33,   38,   32,   32,   32,   32,   32,   32,   32,
       39,   32,   40,   32,   41,   42,   32,   32,   32,   32,

       28,  354,  207,   33,   33,   33,   36,   62,   62,   62,
      137,   33,   33,   33,   33,   33,   33,   28,  354,   70,
       28,  354,  199,  354,   28,  354,  354,   28,  354,   32,
      354,   51,  199,  354,   48,   52,   28,  354,   67,   53,
      340,   49,  354,   50,   28,  354,   28,  354,   32,   54,
      354,   56,  354,   32,   55,   32,   67,   61,  340,  199,
       32,   59,   32,   57,   65,   65,   65,   34,   67,  199,
       78,   67,  103,   58,  340,   60,   29,   32,   63,   63,
       63,   31,  101,  101,  101,   32,   64,   64,   64,   64,
       64,   64,   32,  354,   32,   64,   64,   64,   36,  354,

       32,   64,   64,   64,   36,   71,   79,   32,   32,   72,
      121,   32,   32,  329,  122,   32,  187,   32,   32,   32,
       32,   32,   80,  188,   67,   32,   32,   69,   73,   73,
       73,   75,   76,   32,   32,   32,   77,   32,   32,   67,
      340,   32,   32,  103,   32,   32,   82,   32,   32,   32,
       32,   74,   81,   83,   32,   32,  329,   86,   34,  329,
       32,   32,   32,   32,   32,   32,   85,   32,   84,   32,
       88,   67,   32,  305,   32,  103,   32,   32,   67,   89,
       87,   32,  172,   32,   32,   32,   32,   90,   32,   32,
       32,   93,   32,  130,  130,  130,   32,   32,   32,   32,

       32,   32,   91,   32,   32,   92,   32,   32,  226,   32,
       32,   94,   32,   95,  311,   62,   62,   62,   96,   96,
       96,   98,   98,   98,   99,  311,   97,   97,   97,   97,
       97,   97,  354,  329,   97,   97,   97,   36,   32,   32,
      104,  105,   32,   32,  305,   32,   32,   32,   32,   32,
       32,   32,   32,  107,   32,   32,  201,  201,  201,   32,
      108,   32,   32,   32,   32,   32,   32,  109,   32,  111,
      324,   32,   32,  323,   32,   32,  322,  110,   32,  112,
       32,   32,   32,  114,   32,   32,  113,   34,   32,  115,
       32,  116,   32,   32,   32,  305,   32,   32,  117,  118,

       32,  274,   32,   32,   32,   32,  315,   32,  119,  314,
       32,   32,  313,   32,   32,  311,   32,   32,   32,   32,
       32,  312,  120,  124,   32,   32,  311,   32,  123,   32,
      189,   32,  310,  125,  127,   32,   32,  190,   32,   32,
      126,   67,   32,   32,   32,  103,   32,  305,   32,  274,
      129,  128,   32,   29,  301,  131,  131,  131,   31,   28,
      354,  132,  132,  132,   99,   36,  101,  101,  101,   28,
      354,  140,  135,   32,  300,  354,   32,   67,   32,  299,
      139,  172,   32,   32,   32,   32,  141,  142,  143,  145,
      298,   32,   32,   32,  138,   32,   32,  144,  297,   32,

       32,   32,   32,   32,   32,   32,   32,   32,  146,  147,
      149,  354,  325,   32,  296,   32,  354,   28,  354,  148,
       28,  152,  325,  354,   28,  153,  354,   28,  354,   32,
      354,   28,  354,  354,   28,  354,  173,  354,   32,  295,
      354,  155,   28,  354,  151,  158,   28,  354,  354,  154,
      160,  354,  354,   28,  354,  106,  354,   28,  354,  354,
       34,  159,  274,  354,   28,  354,  202,  202,  202,  162,
      354,  130,  130,  130,  231,  287,  161,  164,  164,  164,
       99,  168,  168,   32,  178,  169,  169,  169,  174,   67,
       32,   32,   32,  172,   32,   32,  286,  180,   32,   32,

       32,  179,   32,   32,   32,  181,   32,   32,   32,  183,
      284,  182,   32,  184,   32,  283,   32,   32,   32,   32,
      191,   32,   32,   32,   32,  186,   32,   32,   32,   32,
       32,   32,   32,  197,  195,  196,  200,   32,   67,   32,
       32,   32,  235,  199,  282,  281,   32,   32,   32,   32,
      202,  202,  202,   99,  205,   32,   67,  169,  169,  169,
      172,   32,   32,  280,   32,  208,  208,  208,   32,   32,
       32,  211,   32,   32,  278,  274,   32,   32,   32,  212,
       32,   32,   32,  213,   32,   32,   32,  231,   32,  216,
      270,   32,   32,  269,   32,   32,  214,   32,   32,   32,

       32,   28,  354,   28,  354,  197,  221,  106,   32,  354,
      197,  268,  267,   32,  266,  199,  226,  225,   32,  265,
      199,   28,  354,  228,  201,  201,  201,  354,  202,  202,
      202,  232,  232,  232,  208,  208,  208,  106,   28,  354,
       28,  354,   28,  354,  354,  264,  354,  250,  354,   28,
      354,   28,  354,   28,  354,  354,  263,  354,  262,  354,
       28,  354,  251,  252,  199,   67,  354,  238,  239,  235,
      226,  259,  240,  258,  199,  253,  253,  253,   28,  354,
      242,  232,  232,  232,  354,   28,  354,   32,   32,   67,
       34,  354,  325,  235,   32,   32,  261,   32,  253,  253,

      253,   67,  325,   32,  271,  277,   32,  285,  285,  285,
       32,  260,   32,   32,  279,   32,  288,  288,   32,   67,
      289,  289,  289,  235,   67,  294,  231,   32,  277,  285,
      285,  285,  226,  302,  167,   67,  289,  289,  289,  277,
       67,  309,  249,   32,  308,  316,  316,  316,  248,   67,
       32,   67,   32,  277,   32,  308,  316,  316,  316,  247,
       67,  321,   67,   32,  308,   32,  332,   67,  246,  325,
      245,  308,   32,  244,   32,  226,   67,  333,   32,  325,
      332,   32,   67,  243,  241,   32,  332,   32,   32,  338,
       32,  344,  344,  344,   67,  344,  344,  344,  332,  350,

      350,  347,  237,  351,  351,  351,  352,  236,  231,  351,
      351,  351,  353,  353,  353,  353,  353,  353,   32,   32,
      167,   32,   32,   32,   66,   66,   68,   68,  100,  100,
      102,  102,  102,  133,  133,  134,  134,  136,  136,  136,
      165,  165,  166,  166,  170,  170,  170,  171,  171,  171,
      198,  224,  223,  198,  222,  198,  198,  203,  203,  204,
      204,  206,  206,  206,  227,  220,  219,  227,  218,  217,
      227,  229,  229,  230,  230,  233,  233,  233,  234,  234,
      234,  254,  254,  255,  255,  256,  256,  256,  272,  272,
      273,  273,  275,  275,  275,  276,  276,  276,  290,  290,

      291,  291,  292,  292,  292,  303,  303,  304,  304,  306,
      306,  306,  307,  307,  307,  317,  317,  318,  318,  319,
      319,  319,  326,  215,  210,  326,  209,   34,  326,  327,
      327,  328,  328,  330,  330,  330,  331,  331,  331,  334,
      334,  335,  335,  336,  336,  336,  339,  339,  341,  341,
      342,  342,  342,  343,  343,  345,  345,  346,  346,  348,
      348,  349,  349,  167,   99,  194,  193,  192,  185,  177,
      176,  175,  167,   99,  163,  157,  156,  150,   99,   34,
       99,   34,   67,   46,   43,   35,   34,   27,  354,    3,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,

      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354
    } ;

static yyconst short int yy_chk[1129] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    5,    5,
        6,    6,    8,    8,   73,    8,    8,    8,    8,  406,
       15,   26,   26,    8,    8,    8,    8,    8,    8,   11,
       11,   15,   17,   17,   73,   11,   12,  397,   17,   12,
       12,   12,   12,   17,   12,  389,  381,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,

       13,   13,  372,   13,   13,   13,   13,   29,   29,   29,
      363,   13,   13,   13,   13,   13,   13,   18,   18,   38,
       19,   19,  199,   18,   20,   20,   19,   21,   21,   38,
       20,   19,  199,   21,   18,   19,   22,   22,  349,   20,
      348,   18,   22,   18,   23,   23,   24,   24,   25,   20,
       23,   22,   24,   28,   21,   25,  346,   25,  345,  259,
       28,   24,   28,   22,   31,   31,   31,   31,   68,  259,
       44,  343,   68,   23,  341,   24,   30,   44,   30,   30,
       30,   30,   67,   67,   67,   32,   30,   30,   30,   30,
       30,   30,   32,   33,   32,   33,   33,   33,   33,   37,

       40,   37,   37,   37,   37,   39,   45,   40,   39,   40,
       88,   42,   45,  339,   88,   39,  152,   39,   42,   45,
       42,   45,   46,  152,  337,   43,   46,   37,   41,   41,
       41,   43,   43,   46,   43,   46,   43,   48,   47,  102,
      335,   49,   41,  102,   48,   47,   48,   47,   49,   41,
       49,   41,   47,   49,   50,   51,  334,   52,  329,  328,
       52,   50,   51,   50,   51,   53,   51,   52,   50,   52,
       54,  136,   53,  327,   53,  136,   55,   54,  137,   56,
       53,   56,  137,   55,   54,   55,   54,   57,   56,   57,
       56,   60,   58,   95,   95,   95,   57,   60,   57,   58,

       59,   58,   58,   61,   60,   59,   60,   59,  324,   59,
       61,   61,   61,   62,  323,   62,   62,   62,   63,   63,
       63,   65,   65,   65,   65,  322,   63,   63,   63,   63,
       63,   63,   64,  318,   64,   64,   64,   64,   69,   70,
       69,   72,   71,   72,  317,   69,   70,   69,   70,   71,
       72,   71,   72,   74,   75,   76,  162,  162,  162,   74,
       75,   75,   76,   75,   76,   77,   74,   76,   74,   78,
      314,   78,   77,  312,   77,   79,  310,   77,   78,   80,
       78,   80,   79,   81,   79,   81,   80,  305,   80,   82,
       80,   83,   81,   83,   81,  304,   82,   84,   84,   84,

       83,  303,   83,   82,   85,   82,  301,   86,   85,  300,
       87,   85,  299,   85,   86,  298,   86,   87,   89,   87,
       84,  297,   87,   90,   90,   89,  296,   89,   89,   91,
      153,   90,  295,   90,   92,   92,   91,  153,   91,   93,
       91,  170,   92,   94,   92,  170,   93,  291,   93,  290,
       94,   93,   94,   96,  287,   96,   96,   96,   96,   97,
       97,   98,   98,   98,   98,   97,  101,  101,  101,  104,
      104,  106,  101,  105,  286,  104,  107,  171,   96,  284,
      105,  171,  105,  107,  108,  107,  106,  106,  107,  109,
      283,  108,  110,  108,  104,  109,  111,  108,  282,  110,

      112,  110,  109,  111,  109,  111,  113,  112,  111,  112,
      114,  114,  315,  113,  281,  113,  114,  116,  116,  113,
      117,  117,  315,  116,  118,  118,  117,  119,  119,  138,
      118,  120,  120,  119,  123,  123,  138,  120,  138,  280,
      123,  120,  124,  124,  116,  123,  125,  125,  124,  119,
      126,  126,  125,  127,  127,  278,  126,  128,  128,  127,
      274,  125,  273,  128,  129,  129,  163,  163,  163,  130,
      129,  130,  130,  130,  272,  270,  128,  132,  132,  132,
      132,  135,  135,  143,  143,  135,  135,  135,  139,  206,
      143,  139,  143,  206,  144,  145,  269,  145,  139,  147,

      139,  144,  145,  144,  145,  146,  147,  146,  147,  148,
      266,  147,  148,  149,  146,  265,  146,  149,  151,  148,
      154,  148,  154,  158,  149,  151,  149,  151,  159,  154,
      158,  154,  158,  160,  158,  159,  161,  159,  207,  173,
      161,  160,  207,  160,  264,  263,  173,  161,  173,  161,
      164,  164,  164,  164,  169,  174,  233,  169,  169,  169,
      233,  178,  174,  262,  174,  175,  175,  175,  178,  179,
      178,  179,  180,  181,  258,  255,  179,  182,  179,  180,
      181,  180,  181,  183,  182,  183,  182,  254,  184,  186,
      252,  186,  183,  251,  183,  184,  184,  184,  186,  191,

      186,  195,  195,  196,  196,  197,  191,  195,  191,  196,
      198,  250,  249,  197,  248,  197,  198,  196,  198,  246,
      198,  200,  200,  201,  201,  201,  201,  200,  202,  202,
      202,  205,  205,  205,  208,  208,  208,  208,  211,  211,
      212,  212,  213,  213,  211,  245,  212,  226,  213,  214,
      214,  216,  216,  221,  221,  214,  244,  216,  243,  221,
      225,  225,  226,  226,  227,  234,  225,  211,  212,  234,
      227,  237,  214,  236,  227,  228,  228,  228,  238,  238,
      216,  232,  232,  232,  238,  239,  239,  240,  242,  256,
      231,  239,  325,  256,  240,  242,  240,  242,  253,  253,

      253,  257,  325,  260,  253,  257,  261,  268,  268,  268,
      260,  238,  260,  261,  261,  261,  271,  271,  279,  275,
      271,  271,  271,  275,  276,  279,  230,  279,  276,  285,
      285,  285,  285,  289,  229,  292,  289,  289,  289,  292,
      293,  294,  224,  294,  293,  302,  302,  302,  223,  306,
      294,  307,  294,  306,  309,  307,  316,  316,  316,  222,
      319,  309,  320,  309,  319,  321,  320,  330,  220,  326,
      219,  330,  321,  218,  321,  326,  331,  321,  333,  326,
      331,  338,  336,  217,  215,  333,  336,  333,  338,  333,
      338,  340,  340,  340,  342,  344,  344,  344,  342,  347,

      347,  344,  210,  347,  347,  347,  351,  209,  204,  351,
      351,  351,  352,  352,  352,  353,  353,  353,  355,  355,
      203,  355,  355,  355,  356,  356,  357,  357,  358,  358,
      359,  359,  359,  360,  360,  361,  361,  362,  362,  362,
      364,  364,  365,  365,  366,  366,  366,  367,  367,  367,
      368,  194,  193,  368,  192,  368,  368,  369,  369,  370,
      370,  371,  371,  371,  373,  190,  189,  373,  188,  187,
      373,  374,  374,  375,  375,  376,  376,  376,  377,  377,
      377,  378,  378,  379,  379,  380,  380,  380,  382,  382,
      383,  383,  384,  384,  384,  385,  385,  385,  386,  386,

      387,  387,  388,  388,  388,  390,  390,  391,  391,  392,
      392,  392,  393,  393,  393,  394,  394,  395,  395,  396,
      396,  396,  398,  185,  177,  398,  176,  167,  398,  399,
      399,  400,  400,  401,  401,  401,  402,  402,  402,  403,
      403,  404,  404,  405,  405,  405,  407,  407,  408,  408,
      409,  409,  409,  410,  410,  411,  411,  412,  412,  413,
      413,  414,  414,  166,  165,  157,  156,  155,  150,  142,
      141,  140,  134,  133,  131,  122,  121,  115,  100,   99,
       66,   36,   34,   16,   14,   10,    9,    7,    3,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,

      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "inject_r6.l"
#define INITIAL 0
#line 2 "inject_r6.l"
/*
  filename: inject_r6.l

  description:
    Defines the tokenizer for an RPSLng route6 inject attribute.  It is
    derived from inject.l.

  notes:
    Tokens are defined in the associated grammar, inject_r6.y.

  $Id: inject_r6.lex.c,v 1.1 2004/12/27 16:38:45 can Exp $
*/
#line 39 "inject_r6.l"
#include <string.h>
#include <stdlib.h>
#include <ctype.h>

/* tokens defined in the grammar */
#include "inject_r6.tab.h"

#define inject_r6wrap yywrap
void syntax_error(char *fmt, ...);
void yy_input(char *buf, int *result, int max_size);
#undef YY_INPUT
#define YY_INPUT(buf,result,max_size) yy_input(buf,&result,max_size)
#line 785 "inject_r6.lex.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 53 "inject_r6.l"


#line 939 "inject_r6.lex.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 355 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1090 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 55 "inject_r6.l"
{ ; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 57 "inject_r6.l"
{ return OP_AND; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 58 "inject_r6.l"
{ return OP_OR; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 59 "inject_r6.l"
{ return OP_COMPARE; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 60 "inject_r6.l"
{ return OP_EQUAL; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 61 "inject_r6.l"
{ return OP_APPEND; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 64 "inject_r6.l"
{ return KEYW_ACTION; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 65 "inject_r6.l"
{ return KEYW_IGP_COST; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 66 "inject_r6.l"
{ return KEYW_SELF; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 67 "inject_r6.l"
{ return KEYW_PREPEND; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 68 "inject_r6.l"
{ return KEYW_APPEND; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 69 "inject_r6.l"
{ return KEYW_DELETE; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 70 "inject_r6.l"
{ return KEYW_CONTAINS; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 72 "inject_r6.l"
{ return KEYW_INTERNET; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 73 "inject_r6.l"
{ return KEYW_NO_EXPORT; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 74 "inject_r6.l"
{ return KEYW_NO_ADVERTISE; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 76 "inject_r6.l"
{ return KEYW_AT; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 77 "inject_r6.l"
{ return KEYW_EXCEPT; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 78 "inject_r6.l"
{ return KEYW_UPON; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 79 "inject_r6.l"
{ return KEYW_STATIC; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 80 "inject_r6.l"
{ return KEYW_EXCLUDE; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 82 "inject_r6.l"
{ return KEYW_HAVE_COMPONENTS; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 84 "inject_r6.l"
{ return KEYW_MASKLEN; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 86 "inject_r6.l"
{ return KEYW_AFI; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 88 "inject_r6.l"
{ return KEYW_AFI_VALUE; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 90 "inject_r6.l"
{ return TKN_PREF; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 91 "inject_r6.l"
{ return TKN_MED; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 92 "inject_r6.l"
{ return TKN_DPA; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 93 "inject_r6.l"
{ return TKN_ASPATH; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 94 "inject_r6.l"
{ return TKN_COMMUNITY; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 95 "inject_r6.l"
{ return TKN_NEXT_HOP; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 96 "inject_r6.l"
{ return TKN_COST; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 98 "inject_r6.l"
{
    long int val;
    char *s;
    val = strtol(yytext+2, &s, 10);
    if ((val < 0) || (val > 65535) || (*s != '\0')) {
        syntax_error("AS number \"%s\" is not between 0 and 65535", yytext);
    }
    return TKN_ASNO;
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 108 "inject_r6.l"
{
    return TKN_RTRSNAME;
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 112 "inject_r6.l"
{
    /* check each number of 1.2.3.4/5 in prefix is valid, as
       well as any bit ranges specified */
    long int val;
    long int endval;
    char *s, *p;
    p = s = yytext;
    while (*s != '/') {
        val = strtol(p, &s, 10);
        if ((val < 0) || (val > 255)) {
             syntax_error("IP prefix \"%s\" contains an invalid octet",
                          yytext);
        }
        p = s + 1;
    }
    val = strtol(p, &s, 10);
    if ((val < 0) || (val > 32)) {
        syntax_error("IP prefix range \"%s\" contains an invalid prefix length",                     yytext);
    }
    p = s + 1;
    if (isdigit((int)*p)) {
        val = strtol(p, &s, 10);
        if ((val < 0) || (val > 32)) {
            syntax_error("IP prefix range \"%s\" contains an invalid range",
                         yytext);
        }
        p = s + 1;
        if (isdigit((int)*p)) {
            endval = strtol(p, NULL, 10);
            if ((endval < 0) || (endval > 32)) {
                syntax_error("IP prefix \"%s\" contains an invalid prefix range",
                             yytext);
            }
            if (endval < val) {
                syntax_error("IP prefix \"%s\" range end is less than range start",
                             yytext);
            }
        }
    }
    return TKN_PRFXV4RNG;
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 154 "inject_r6.l"
{
    /* check each quad of 1A:3:7:8:AAAA:BBBB:DEAD:BEEF/55 in prefix is valid, as
       well as any bit ranges specified */
    long int val;
    long int endval;
    char *s, *p;
    p = s = yytext;
    while (*s != '/') {
        val = strtol(p, &s, 16);
        if ((val < 0) || (val > 65535)) {
             syntax_error("IPv6 prefix \"%s\" contains an invalid quad",
                          yytext);
        }
        p = s + 1;
    }
    val = strtol(p, &s, 10);
    if ((val < 0) || (val > 128)) {
        syntax_error("IPv6 prefix range \"%s\" contains an invalid prefix length",
                     yytext);
    }
    p = s + 1;
    if (isdigit((int)*p)) {
        val = strtol(p, &s, 10);
        if ((val < 0) || (val > 128)) {
            syntax_error("IPv6 prefix range \"%s\" contains an invalid range",
                         yytext);
        }
        p = s + 1;
        if (isdigit((int)*p)) {
            endval = strtol(p, NULL, 10);
            if ((endval < 0) || (endval > 128)) {
                syntax_error("IPv6 prefix \"%s\" contains an invalid prefix range",
                             yytext);
            }
            if (endval < val) {
                syntax_error("IPv6 prefix \"%s\" range end is less than range start",
                             yytext);
            }
        }
    }
    return TKN_PRFXV6RNG;
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 197 "inject_r6.l"
{
    /* check each quad of 1A:3:7:8:AAAA:BBBB:DEAD:BEEF/55 in prefix is valid, as
       well as any bit ranges specified */
    long int val;
    long int endval;
    char *s, *p, *r;
    int leftquads = 0;
    int rightquads = 0;

    p = s = yytext;
    while (*s != '/') {
        val = strtol(p, &s, 16);
        if ((val < 0) || (val > 65535)) {
             syntax_error("IPv6 prefix \"%s\" contains an invalid quad",
                          yytext);
        }
        p = s + 1;
    }
    val = strtol(p, &s, 10);
    if ((val < 0) || (val > 128)) {
        syntax_error("IPv6 prefix range \"%s\" contains an invalid prefix length",
                     yytext);
    }
    p = s + 1;
    if (isdigit((int)*p)) {
        val = strtol(p, &s, 10);
        if ((val < 0) || (val > 128)) {
            syntax_error("IPv6 prefix range \"%s\" contains an invalid range",
                         yytext);
        }
        p = s + 1;
        if (isdigit((int)*p)) {
            endval = strtol(p, NULL, 10);
            if ((endval < 0) || (endval > 128)) {
                syntax_error("IPv6 prefix \"%s\" contains an invalid prefix range",
                             yytext);
            }
            if (endval < val) {
                syntax_error("IPv6 prefix \"%s\" range end is less than range start",
                             yytext);
            }
        }
    }

    /* And now, count colons to the left of "::" - this is
       one less than the number of left quads */

    r = strchr(yytext, ':');
    leftquads++;
    while (r[1] != ':') {
        leftquads++;
        r = strchr(r+1, ':');
    }
    /* skip "::" */
    r += 2;
    /* count colons to the right of "::" - one less than the number of right quads */
    if (r[0] != '\0') {
        do {
            rightquads++;
            r = strchr(r+1, ':');
        } while (r != NULL);
    }
    /* check for too many quads */
    if ((leftquads + rightquads) > 8) {
        syntax_error("IPv6 address \"%s\" contains too many digits", yytext);
    }

    return TKN_PRFXV6DCRNG;
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 267 "inject_r6.l"
{
    /* check each number of 1.2.3.4/5 in prefix is valid */
    long int val;
    char *s, *p;
    p = s = yytext;
    while (*s != '/') {
        val = strtol(p, &s, 10);
        if ((val < 0) || (val > 255)) {
             syntax_error("IP prefix \"%s\" contains an invalid octet",
                          yytext);
        }
        p = s + 1;
    }
    val = strtol(p, NULL, 10);
    if ((val < 0) || (val > 32)) {
        syntax_error("IP prefix \"%s\" contains an invalid prefix length",
                     yytext);
    }
    return TKN_PRFXV4;
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 288 "inject_r6.l"
{
    /* check each quad of 1A:3:7:8:AAAA:BBBB:DEAD:BEEF/55 in prefix is valid */
    long int val;
    char *s, *p;
    p = s = yytext;
    while (*s != '/') {
        val = strtol(p, &s, 16);
        if ((val < 0) || (val > 65535)) {
             syntax_error("IPv6 prefix \"%s\" contains an invalid quad",
                          yytext);
        }
        p = s + 1;
    }
    val = strtol(p, NULL, 10);
    if ((val < 0) || (val > 128)) {
        syntax_error("IPv6 prefix \"%s\" contains an invalid prefix length",
                     yytext);
    }
    return TKN_PRFXV6;
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 309 "inject_r6.l"
{
    /* check each quad of 1A::AAAA:BBBB:DEAD:BEEF/55 in prefix is valid */
    long int val;
    char *s, *p, *r;
    int leftquads = 0;
    int rightquads = 0;

    r = p = s = yytext;
    while (*s != '/') {
        val = strtol(p, &s, 16);
        if ((val < 0) || (val > 65535)) {
             syntax_error("IPv6 prefix \"%s\" contains an invalid quad",
                          yytext);
        }
        p = s + 1;
    }
    val = strtol(p, NULL, 10);
    if ((val < 0) || (val > 128)) {
        syntax_error("IPv6 prefix \"%s\" contains an invalid prefix length",
                     yytext);
    }

    /* And now, count colons to the left of "::" - this is
       one less then the number of left quads */

    r = strchr(yytext, ':');
    leftquads++;
    while (r[1] != ':') {
        leftquads++;
        r = strchr(r+1, ':');
    }
    /* skip "::" */
    r += 2;
    /* count colons to the right of "::" - one less then the number of right quads */
    if (r[0] != '\0') {
        do {
            rightquads++;
            r = strchr(r+1, ':');
        } while (r != NULL);
    }
    /* check for too many quads */
    if ((leftquads + rightquads) > 8) {
        syntax_error("IPv6 address \"%s\" contains too many digits", yytext);
    }

    return TKN_PRFXV6DC;
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 357 "inject_r6.l"
{
    /* check each number of 1.2.3.4 is valid */
    long int val;
    char *s, *p;
    p = s = yytext;
    while (*s != '\0') {
        val = strtol(p, &s, 10);
        if ((val < 0) || (val > 255)) {
             syntax_error("IP address \"%s\" contains an invalid octet", 
                          yytext);
        }
        p = s + 1;
    }
    return TKN_IPV4;
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 373 "inject_r6.l"
{
    /* check each quad of 1A:3:7:8:AAAA:BBBB:DEAD:BEEF in address is valid */
    long int val;
    char *s, *p;
    p = s = yytext;
    while (*s != '\0') {
        val = strtol(p, &s, 16);
        if ((val < 0) || (val > 65535)) {
             syntax_error("IPv6 address \"%s\" contains an invalid quad",
                          yytext);
        }
        p = s + 1;
    }
    return TKN_IPV6;
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 389 "inject_r6.l"
{
    /* check each quad of 1A::AAAA:BBBB:DEAD:BEEF in address is valid */
    long int val;
    char *s, *p, *r;
    int leftquads = 0;
    int rightquads = 0;

    r = p = s = yytext;
    while (*s != '\0') {
        val = strtol(p, &s, 16);
        if ((val < 0) || (val > 65535)) {
             syntax_error("IPv6 address \"%s\" contains an invalid quad",
                          yytext);
        }
        p = s + 1;
    }
    /* And now, count colons to the left of "::" - this is
       one less then the number of left quads */

    r = strchr(yytext, ':');
    leftquads++;
    while (r[1] != ':') {
        leftquads++;
        r = strchr(r+1, ':');
    }
    /* skip "::" */
    r += 2;
    /* count colons to the right of "::" - one less then the number of right quads */
    if (r[0] != '\0') {
        do {
            rightquads++;
            r = strchr(r+1, ':');
        } while (r != NULL);
    }
    /* check for too many quads */
    if ((leftquads + rightquads) > 8) {
        syntax_error("IPv6 address \"%s\" contains too many digits", yytext);
    }

    return TKN_IPV6DC;
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 431 "inject_r6.l"
{
    /* verify each part is a 16-bit number */
    long int val;
    char *s, *p;
    p = s = yytext;
    while (*s != '\0') {
        val = strtol(p, &s, 10);
        if ((val < 0) || (val > 65535)) {
             syntax_error("Community number \"%s\" contains an invalid number", 
                           yytext);
        }
        p = s + 1;
    }
    return TKN_COMM_NO;
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 447 "inject_r6.l"
{ 
    inject_r6lval.sval = yytext;
    return TKN_INT; 
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 452 "inject_r6.l"
{ 
    /* check the length */
    if (strlen(yytext) > 63) {
       syntax_error("Portion of domain name \"%s\" is longer "
                                                           "than 63 characters",                    yytext);
    }
    inject_r6lval.sval = yytext;
    return TKN_DNS;
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 462 "inject_r6.l"
{ return yytext[0]; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 464 "inject_r6.l"
ECHO;
	YY_BREAK
#line 1598 "inject_r6.lex.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 355 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 355 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 354);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 464 "inject_r6.l"


void 
inject_r6_reset ()
{
    yy_flush_buffer(YY_CURRENT_BUFFER);
}

