#line 2 "members_rs.lex.c"

#line 4 "members_rs.lex.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 33
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE members_rsrestart(members_rsin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int members_rsleng;

extern FILE *members_rsin, *members_rsout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up members_rstext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up members_rstext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef unsigned int yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via members_rsrestart()), so that the user can continue scanning by
	 * just pointing members_rsin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when members_rstext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int members_rsleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow members_rswrap()'s to do buffer switches
 * instead of setting up a fresh members_rsin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void members_rsrestart (FILE *input_file  );
void members_rs_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE members_rs_create_buffer (FILE *file,int size  );
void members_rs_delete_buffer (YY_BUFFER_STATE b  );
void members_rs_flush_buffer (YY_BUFFER_STATE b  );
void members_rspush_buffer_state (YY_BUFFER_STATE new_buffer  );
void members_rspop_buffer_state (void );

static void members_rsensure_buffer_stack (void );
static void members_rs_load_buffer_state (void );
static void members_rs_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER members_rs_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE members_rs_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE members_rs_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE members_rs_scan_bytes (yyconst char *bytes,int len  );

void *members_rsalloc (yy_size_t  );
void *members_rsrealloc (void *,yy_size_t  );
void members_rsfree (void *  );

#define yy_new_buffer members_rs_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        members_rsensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            members_rs_create_buffer(members_rsin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        members_rsensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            members_rs_create_buffer(members_rsin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *members_rsin = (FILE *) 0, *members_rsout = (FILE *) 0;

typedef int yy_state_type;

extern int members_rslineno;

int members_rslineno = 1;

extern char *members_rstext;
#define yytext_ptr members_rstext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up members_rstext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	members_rsleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 13
#define YY_END_OF_BUFFER 14
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[295] =
    {   0,
        0,    0,   14,   12,    1,    1,    1,   12,   12,   12,
       12,   12,    0,    0,    1,    1,    0,    0,    3,    2,
        4,    0,    0,    0,    0,    0,    0,    0,    6,    6,
        6,    6,    0,    0,    0,    0,    5,    0,    9,    9,
        0,    0,    0,    6,    6,    6,    6,    0,    0,    8,
        8,    0,    0,    9,    7,    7,    7,    7,    0,    0,
        0,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        0,    0,    8,    0,    0,    0,    9,    7,    7,    7,
        7,    7,    7,    0,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    0,    0,    0,    0,    8,

        0,    0,    0,    7,    7,    7,    7,    7,    7,    0,
        0,    0,    0,    6,    6,    6,    6,    6,    0,    0,
        0,    0,    0,    0,    0,    9,    9,    9,    9,    0,
        7,    7,    7,    7,    7,    7,    7,    0,    0,    0,
        0,    0,    6,    6,    0,    6,    6,    6,    0,    8,
        8,    8,    8,    0,    0,   10,    0,    9,    9,    0,
        9,    9,    9,    9,    0,    7,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    8,    8,    8,    8,
        0,    0,    8,    8,    0,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    0,    7,    7,    7,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    0,
        8,   11,   11,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    0,    0,    0,    0,
        0,    0,    0,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    0,    9,    9,    9,
        9,    9,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    8,    8,    8,    8,    8,    0,    0,   11,    9,
        9,    0,    9,    9,    9,    0,    8,    8,    0,    8,
        8,    8,    0,    0

    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    5,    1,    6,    7,    8,    9,   10,   10,
       11,   12,   13,   14,   15,   15,   15,   16,    1,    1,
        1,    1,    1,    1,   19,   20,   20,   20,   21,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   22,
       20,   23,   24,   20,   20,   20,   20,   20,   20,   20,
        1,    1,    1,   17,   18,    1,   19,   20,   20,   20,

       21,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   22,   20,   23,   24,   20,   20,   20,   20,   20,
       20,   20,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[25] =
    {   0,
        1,    1,    1,    2,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[297] =
    {   0,
        0,    0, 1032, 1008,   23,   41,   26,   54,   69,   12,
       13,   14, 1003,   16,   87,   44,   98,    0,  953,  894,
       44,  112,   18,   35,   43,  905,  119,  134,  152,  165,
      173,  180,   32,  193,   78,  209,    0,    0,  859,   70,
      216,   34,  223,  230,  237,  244,  251,  746,    0,  725,
       76,  730,   74,   61,  715,  256,  267,  274,   52,   80,
       79,   86,  279,  287,  294,  299,  306,  313,  320,  327,
       95,  141,  153,  332,   96,  146,  341,  714,  330,  349,
      356,  363,  370,  375,  382,  389,  396,  403,  408,  413,
      418,  423,  428,  428,  439,  437,  332,  253,  401,  448,

      585,  459,  334,  421,  466,  473,  480,  487,  449,  496,
      509,  516,  523,  528,  535,  546,  553,  452,  560,   88,
      567,  485,   53,  574,  589,  607,  620,  628,  635,  147,
      642,  498,  543,  608,  611,  653,  498,  660,  667,  674,
      681,  688,  643,  646,  697,  497,  698,  710,  447,  720,
      733,  741,  748,  491,  761,  494,    0,  451,  634,  777,
      784,  791,  798,  805,  426,  809,  609,  816,  823,  830,
      835,  842,  849,  856,  863,  868,  875,  882,  889,  896,
      333,    0,  323,  688,  905,  650,  700,  912,  920,  927,
      932,  939,  946,  953,  960,  641,  965,  972,  979,  984,

      991,  998, 1005, 1010, 1015, 1020, 1025, 1030,  702, 1037,
      701, 1042, 1050, 1057, 1062, 1069, 1076, 1083, 1090,  686,
      714,  254,  726, 1095, 1103, 1110, 1117, 1124, 1129, 1134,
     1139, 1144, 1149, 1149, 1160,  719, 1165, 1172, 1183, 1190,
     1096, 1197,  608, 1204, 1211, 1218, 1225, 1230, 1235, 1240,
     1245, 1250, 1250, 1261, 1259, 1270, 1278, 1285, 1292, 1303,
     1310, 1099, 1317, 1260, 1180, 1271, 1328,  181,  706, 1340,
     1327, 1348, 1355, 1366, 1373, 1274, 1380, 1333,    0, 1300,
     1332, 1391,  157, 1331, 1403, 1390, 1341, 1363, 1415,  122,
     1394, 1427, 1396, 1444,  115,   57

    } ;

static yyconst flex_int16_t yy_def[297] =
    {   0,
      294,    1,  294,  295,  295,  295,  294,  295,  295,  295,
      295,  295,  295,  295,  295,  294,  295,    8,  295,  295,
        9,   17,  295,  295,  295,   17,   17,  294,  295,   17,
       30,   31,  295,  294,  295,   17,   27,   28,   28,   28,
       27,  295,   27,   31,   31,   31,   46,  295,   34,   34,
       34,   36,  295,   28,  296,  296,   56,   57,  295,  295,
      295,  295,   36,   63,   64,   46,   46,   46,   46,   69,
      295,  295,   34,   36,  295,  295,   28,  296,  296,   57,
       57,   57,   82,   22,   64,   64,   64,   87,   69,   69,
       69,   69,   69,  295,   93,  295,  295,  295,  295,   34,

       74,   74,  295,  296,   82,   82,   82,   82,  108,  295,
       93,  111,  112,   87,   87,   87,   87,  117,   74,   95,
       74,  295,  295,   74,  294,  295,   74,  127,  128,  295,
      296,  108,  108,  108,  108,  108,  296,   74,  112,  112,
      112,  141,  117,  117,  117,  145,  145,  145,  295,  295,
      117,  151,  152,  295,  294,  124,  125,  125,  125,  124,
      128,  128,  128,  163,  295,  136,  295,  117,  117,  169,
      141,  141,  141,  141,  174,  124,  152,  152,  152,  179,
      295,  155,  155,  155,  124,  125,  295,  124,  188,  189,
      163,  163,  163,  163,  194,  295,  136,  136,  198,  169,

      169,  169,  202,  174,  174,  174,  174,  174,  295,  208,
      295,  202,  212,  213,  179,  179,  179,  179,  218,  295,
      155,  295,  185,  125,  189,  189,  189,  227,  194,  194,
      194,  194,  194,  295,  233,  295,  202,  202,  202,  202,
      240,  124,  210,  213,  213,  213,  246,  218,  218,  218,
      218,  218,  295,  252,  295,  155,  124,  227,  227,  227,
      227,  261,  124,  235,  240,  240,  240,  267,  267,  267,
      295,  246,  246,  246,  246,  275,  124,  254,  257,  261,
      261,  261,  282,  282,  282,  295,  275,  275,  275,  289,
      289,  289,  295,    0,  294,  294

    } ;

static yyconst flex_int16_t yy_nxt[1469] =
    {   0,
        4,    5,    6,    7,    4,    4,    4,    4,    8,    8,
        8,    8,    8,    8,    8,    4,    9,    4,   10,    4,
        4,   11,   12,    4,   15,   15,   16,   16,   16,   16,
       14,   14,   14,   23,   14,   22,   14,   24,   33,   25,
       34,   14,   15,   15,   16,   16,   16,   16,   13,   27,
       14,   35,   59,   14,   48,   60,   61,   78,  155,   14,
       17,   14,   18,   18,   18,   18,   18,   18,   18,   77,
       14,   14,   14,   19,   20,   84,   53,   21,   21,   21,
       21,   21,   21,   21,   41,   53,   35,   14,   15,   15,
       16,   72,   75,   54,   13,   76,   14,   14,   14,   73,

       23,   42,   24,   13,   14,   14,   26,   26,   26,   26,
       26,   26,   26,   14,   14,   13,   14,   28,   96,  102,
       29,   30,   30,   30,   30,   31,   32,   37,   37,   37,
       37,   37,   37,   37,   13,   13,   13,   72,   13,   38,
       13,   13,   39,   39,   39,   39,   39,   39,   39,   13,
       13,   38,   40,   39,   39,   39,   39,   39,   41,   97,
       35,  100,   98,   99,   14,   14,  103,   42,   72,  165,
       14,   43,   53,   44,   44,   44,   44,   44,   44,   44,
       42,   45,   45,   45,   45,   46,   47,   47,   47,   47,
       47,   47,   47,   13,   13,   13,   42,   13,   49,   13,

       13,   50,   50,   50,   50,   50,   50,   50,   13,   13,
       49,   51,   50,   50,   50,   50,   50,   52,   52,   52,
       52,   52,   52,   52,   55,   56,   56,   56,   56,   57,
       58,   62,   63,   63,   63,   63,   64,   65,   66,   66,
       66,   66,   66,   66,   66,   67,   67,   67,   67,   67,
       67,   67,   68,   68,   68,   68,   69,   70,   70,   70,
       70,   70,   70,   70,   80,   80,   80,   80,   80,   80,
       80,   14,   14,  122,   79,   81,   81,   81,   81,   82,
       83,   83,   83,   83,   83,   83,   83,   85,   85,   85,
       85,   85,   85,   85,   42,   86,   86,   86,   86,   87,

       88,   88,   88,   88,   88,   88,   88,   89,   89,   89,
       89,   89,   89,   89,   90,   90,   90,   90,   90,   90,
       90,   91,   91,   91,   91,   91,   91,   91,   92,   92,
       93,   94,   95,   94,   94,   94,   94,   94,   72,   94,
      101,  101,  101,  101,  101,  101,  101,   41,   79,   77,
       14,  220,   14,  104,  130,  121,   53,  105,  105,  105,
      105,  105,  105,  105,  106,  106,  106,  106,  106,  106,
      106,  107,  107,  107,  107,  108,  109,  109,  109,  109,
      109,  109,  109,  110,  111,  111,  111,  111,  112,  113,
      114,  114,  114,  114,  114,  114,  114,  115,  115,  115,

      115,  115,  115,  115,  116,  116,  116,  116,  117,  118,
      118,  118,  118,  118,  118,  118,   94,   94,   94,   14,
       94,   94,   94,   94,  123,   94,   94,   94,   94,  131,
       94,   94,   94,   94,   43,   94,   94,   94,   94,   79,
       94,   13,   13,   42,  196,   35,   14,  119,  119,   13,
       13,  120,   42,   43,   41,   14,  100,  137,  137,  137,
       62,   62,   62,   72,  125,   14,   53,  126,  127,  127,
      127,  127,  128,  129,  132,  132,  132,  132,  132,  132,
      132,  133,  133,  133,  133,  133,  133,  133,  134,  134,
      134,  134,  134,  134,  134,  135,  135,  136,  137,  137,

      137,  137,   41,   14,   35,  154,  137,  137,  137,   14,
      185,   42,   42,  181,   14,  138,   79,  139,  139,  139,
      139,  139,  139,  139,  140,  140,  140,  140,  141,  142,
      142,  142,  142,  142,  142,  142,  143,  143,  143,  143,
      143,  143,  143,  144,  144,  144,  144,  144,  144,  144,
      145,  137,  137,  137,  146,  146,  146,  146,  146,  146,
      146,  147,  147,  148,   62,   62,   62,   62,  149,  149,
      149,  149,  149,  149,  149,  150,  151,  151,  151,  151,
      152,  153,  156,  156,  156,  156,  156,  156,  156,   13,
       13,   13,  124,   13,  157,   13,   13,  158,  158,  158,

      158,  158,  158,  158,   13,   13,  157,  159,  158,  158,
      158,  158,  158,   41,   13,   35,  137,  137,  137,  137,
      137,  137,   53,   13,   42,   14,  160,   14,  161,  161,
      161,  161,  161,  161,  161,   53,  162,  162,  162,  162,
      163,  164,  164,  164,  164,  164,  164,  164,  166,   53,
      131,   62,   62,   62,   62,   62,   62,  186,  224,   14,
       79,  137,  137,  137,  236,   53,   78,   78,  167,  168,
      168,  168,  168,  169,  170,  171,  171,  171,  171,  171,
      171,  171,  172,  172,  172,  172,  172,  172,  172,  173,
      173,  173,  173,  174,  175,  175,  175,  175,  175,  175,

      175,   62,   13,   72,   14,   62,   62,   62,  138,  255,
       13,  221,   13,   42,   13,   53,   72,   42,   14,   14,
       14,   42,  256,   13,   13,   42,   41,   35,   35,   72,
       13,  257,   79,   79,   53,   72,   74,   14,   14,  176,
       72,  177,  177,  177,  177,  177,  177,  177,   72,  178,
      178,  178,  178,  179,  180,  180,  180,  180,  180,  180,
      180,   13,   13,   13,   71,   13,  182,   13,   13,  183,
      183,  183,  183,  183,  183,  183,   13,   13,  182,  184,
      183,  183,  183,  183,  183,  187,  188,  188,  188,  188,
      189,  190,  191,  191,  191,  191,  191,  191,  191,  192,

      192,  192,  192,  192,  192,  192,  193,  193,  193,  193,
      194,  195,  195,  195,  195,  195,  195,  195,  197,  197,
      197,  197,  198,  199,  200,  200,  200,  200,  200,  200,
      200,  201,  201,  201,  201,  202,  203,  203,  203,  203,
      203,  203,  203,  204,  204,  204,  204,  204,  204,  204,
      205,  205,  205,  205,  205,  205,  205,  206,  206,  206,
      206,  206,  206,  206,  207,  207,  208,  209,  210,  209,
      209,  209,  209,  209,   53,  209,  211,  212,  212,  212,
      212,  213,  214,  215,  215,  215,  215,  215,  215,  215,
      216,  216,  216,  216,  216,  216,  216,  217,  217,  217,

      217,  218,  219,  219,  219,  219,  219,  219,  219,  222,
      222,   36,   14,  223,  223,  223,  223,  223,  223,  223,
      225,  225,  225,  225,  225,  225,  225,   53,  226,  226,
      226,  226,  227,  228,  228,  228,  228,  228,  228,  228,
      229,  229,  229,  229,  229,  229,  229,  230,  230,  230,
      230,  230,  230,  230,  231,  231,  231,  231,  231,  231,
      231,  232,  232,  233,  234,  235,  234,  234,  234,  234,
      234,   14,  234,   80,   80,   80,   80,   80,   80,   80,
       81,   81,   81,   81,   82,   83,   83,   83,   83,   83,
       83,   83,  237,  237,  237,  237,  237,  237,  237,  238,

      238,  238,  238,  238,  238,  238,  239,  239,  239,  239,
      240,  241,  241,  241,  241,  241,  241,  241,  209,  209,
      209,   14,  209,  209,  209,  209,   14,  209,  209,  209,
      209,  294,  209,  209,  209,  209,  294,  209,  209,  209,
      209,  294,  209,   13,   13,  242,  242,   13,   13,  243,
      244,  244,  244,  244,  244,  244,  244,   72,  245,  245,
      245,  245,  246,  247,  247,  247,  247,  247,  247,  247,
      248,  248,  248,  248,  248,  248,  248,  249,  249,  249,
      249,  249,  249,  249,  250,  250,  250,  250,  250,  250,
      250,  251,  251,  252,  253,  254,  253,  253,  253,  253,

      253,   41,  253,  224,  167,  167,  167,  187,  187,  187,
       53,  258,  258,  258,  258,  258,  258,  258,  259,  259,
      259,  259,  259,  259,  259,  260,  260,  260,  260,  261,
      262,  262,  262,  262,  262,  262,  262,  234,  234,  234,
      294,  234,  234,  234,  234,  294,  234,  234,  234,  234,
      294,  234,  234,  234,  234,  160,  234,  234,  234,  234,
      294,  234,   13,   13,   53,  294,  294,   14,  263,  263,
       13,   13,  264,  265,  265,  265,  265,  265,  265,  265,
      266,  266,  266,  266,  266,  266,  266,  267,  167,  167,
      167,  268,  268,  268,  268,  268,  268,  268,  269,  269,

      270,  167,  167,  167,  167,  271,  271,  271,  271,  271,
      271,  271,  272,  272,  272,  272,  272,  272,  272,  273,
      273,  273,  273,  273,  273,  273,  274,  274,  274,  274,
      275,  276,  276,  276,  276,  276,  276,  276,  253,  253,
      253,  294,  253,  253,  253,  253,  294,  253,  253,  253,
      253,  294,  253,  253,  253,  253,  176,  253,  253,  253,
      253,  294,  253,   13,   13,   72,   13,   35,   14,  277,
      277,   13,   13,  278,   72,   13,   41,   14,  256,  167,
      167,  167,  211,  211,  211,   72,  279,  279,  279,  279,
      279,  279,  279,  280,  280,  280,  280,  280,  280,  280,

      281,  281,  281,  281,  281,  281,  281,  282,  187,  187,
      187,  283,  283,  283,  283,  283,  283,  283,  284,  284,
      285,  187,  187,  187,  187,  286,  286,  286,  286,  286,
      286,  286,  167,  138,  294,   13,  167,  167,  167,   13,
      187,  187,  187,   13,   13,   14,   53,  294,   13,  211,
      211,  211,  294,   13,   13,   42,  287,  287,  287,  287,
      287,  287,  287,  288,  288,  288,  288,  288,  288,  288,
      289,  211,  211,  211,  290,  290,  290,  290,  290,  290,
      290,  291,  291,  292,  211,  211,  211,  211,  293,  293,
      293,  293,  293,  293,  293,  187,  160,  294,   13,  187,

      187,  187,  176,  294,  294,  294,   13,   13,   14,   72,
      294,  294,  294,  294,   14,  294,   13,   13,   53,  211,
      294,  294,  294,  211,  211,  211,  294,  294,  294,  294,
       13,   13,  294,  294,  294,  294,  294,  294,  294,  294,
       13,   13,   72,    3,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294
    } ;

static yyconst flex_int16_t yy_chk[1469] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    5,    5,    5,    7,    7,    7,
       10,   11,   12,   11,   14,   10,   23,   12,   23,   14,
       24,    5,    6,    6,    6,   16,   16,   16,   21,   21,
       33,   25,   42,   24,   33,   42,   42,  296,  123,    6,
        8,   25,    8,    8,    8,    8,    8,    8,    8,   54,
       59,  123,    8,    9,    9,   59,   54,    9,    9,    9,
        9,    9,    9,    9,   35,   40,   35,    9,   15,   15,
       15,   51,   53,   40,  120,   53,   35,   61,   60,   51,

       60,   62,   61,  120,   62,   15,   17,   17,   17,   17,
       17,   17,   17,   71,   75,  295,   17,   22,   71,   75,
       22,   22,   22,   22,   22,   22,   22,   27,   27,   27,
       27,   27,   27,   27,   28,   28,   28,  290,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   29,   72,
       29,   73,   72,   72,   76,  130,   76,   29,   73,  130,
       29,   30,  283,   30,   30,   30,   30,   30,   30,   30,
       30,   31,   31,   31,   31,   31,   31,   31,   32,   32,
       32,   32,   32,   34,   34,   34,  268,   34,   34,   34,

       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   36,   36,   36,
       36,   36,   36,   36,   41,   41,   41,   41,   41,   41,
       41,   43,   43,   43,   43,   43,   43,   43,   44,   44,
       44,   44,   44,   44,   44,   45,   45,   45,   45,   45,
       45,   45,   46,   46,   46,   46,   46,   46,   46,   47,
       47,   47,   47,   47,   56,   56,   56,   56,   56,   56,
       56,   98,  222,   98,   56,   57,   57,   57,   57,   57,
       57,   57,   58,   58,   58,   58,   58,   63,   63,   63,
       63,   63,   63,   63,   63,   64,   64,   64,   64,   64,

       64,   64,   65,   65,   65,   65,   65,   66,   66,   66,
       66,   66,   66,   66,   67,   67,   67,   67,   67,   67,
       67,   68,   68,   68,   68,   68,   68,   68,   69,   69,
       69,   69,   69,   69,   69,   70,   70,   70,  183,   70,
       74,   74,   74,   74,   74,   74,   74,   77,   79,   77,
       97,  181,  103,   79,  103,   97,   77,   80,   80,   80,
       80,   80,   80,   80,   81,   81,   81,   81,   81,   81,
       81,   82,   82,   82,   82,   82,   82,   82,   83,   83,
       83,   83,   83,   84,   84,   84,   84,   84,   84,   84,
       85,   85,   85,   85,   85,   85,   85,   86,   86,   86,

       86,   86,   86,   86,   87,   87,   87,   87,   87,   87,
       87,   88,   88,   88,   88,   88,   89,   89,   89,   99,
       89,   90,   90,   90,   99,   90,   91,   91,   91,  104,
       91,   92,   92,   92,   94,   92,   93,   93,   93,  104,
       93,   93,   93,   94,  165,   96,   94,   95,   95,   95,
       95,   95,   96,  149,  100,   96,  100,  109,  109,  109,
      118,  118,  118,  100,  102,  149,  158,  102,  102,  102,
      102,  102,  102,  102,  105,  105,  105,  105,  105,  105,
      105,  106,  106,  106,  106,  106,  106,  106,  107,  107,
      107,  107,  107,  107,  107,  108,  108,  108,  108,  108,

      108,  108,  110,  122,  110,  122,  132,  132,  132,  154,
      156,  110,  146,  154,  110,  111,  137,  111,  111,  111,
      111,  111,  111,  111,  112,  112,  112,  112,  112,  112,
      112,  113,  113,  113,  113,  113,  114,  114,  114,  114,
      114,  114,  114,  115,  115,  115,  115,  115,  115,  115,
      116,  133,  133,  133,  116,  116,  116,  116,  116,  116,
      116,  117,  117,  117,  117,  117,  117,  117,  119,  119,
      119,  119,  119,  119,  119,  121,  121,  121,  121,  121,
      121,  121,  124,  124,  124,  124,  124,  124,  124,  125,
      125,  125,  101,  125,  125,  125,  125,  125,  125,  125,

      125,  125,  125,  125,  125,  125,  125,  125,  125,  125,
      125,  125,  125,  126,  243,  126,  134,  134,  134,  135,
      135,  135,  126,  243,  167,  126,  127,  167,  127,  127,
      127,  127,  127,  127,  127,  127,  128,  128,  128,  128,
      128,  128,  128,  129,  129,  129,  129,  129,  131,  159,
      131,  143,  143,  143,  144,  144,  144,  159,  186,  196,
      131,  136,  136,  136,  196,  186,  136,  136,  138,  138,
      138,  138,  138,  138,  138,  139,  139,  139,  139,  139,
      139,  139,  140,  140,  140,  140,  140,  140,  140,  141,
      141,  141,  141,  141,  141,  141,  142,  142,  142,  142,

      142,  145,  147,  184,  220,  145,  145,  145,  209,  220,
      269,  184,  145,  147,  148,  187,  211,  209,  187,  211,
      209,  269,  221,  148,  148,  148,  150,  236,  150,  221,
      223,  223,   78,   55,  236,  150,   52,  236,  150,  151,
       50,  151,  151,  151,  151,  151,  151,  151,  151,  152,
      152,  152,  152,  152,  152,  152,  153,  153,  153,  153,
      153,  155,  155,  155,   48,  155,  155,  155,  155,  155,
      155,  155,  155,  155,  155,  155,  155,  155,  155,  155,
      155,  155,  155,  155,  155,  160,  160,  160,  160,  160,
      160,  160,  161,  161,  161,  161,  161,  161,  161,  162,

      162,  162,  162,  162,  162,  162,  163,  163,  163,  163,
      163,  163,  163,  164,  164,  164,  164,  164,  166,  166,
      166,  166,  166,  166,  168,  168,  168,  168,  168,  168,
      168,  169,  169,  169,  169,  169,  169,  169,  170,  170,
      170,  170,  170,  171,  171,  171,  171,  171,  171,  171,
      172,  172,  172,  172,  172,  172,  172,  173,  173,  173,
      173,  173,  173,  173,  174,  174,  174,  174,  174,  174,
      174,  175,  175,  175,   39,  175,  176,  176,  176,  176,
      176,  176,  176,  177,  177,  177,  177,  177,  177,  177,
      178,  178,  178,  178,  178,  178,  178,  179,  179,  179,

      179,  179,  179,  179,  180,  180,  180,  180,  180,  185,
      185,   26,   20,  185,  185,  185,  185,  185,  185,  185,
      188,  188,  188,  188,  188,  188,  188,  188,  189,  189,
      189,  189,  189,  189,  189,  190,  190,  190,  190,  190,
      191,  191,  191,  191,  191,  191,  191,  192,  192,  192,
      192,  192,  192,  192,  193,  193,  193,  193,  193,  193,
      193,  194,  194,  194,  194,  194,  194,  194,  195,  195,
      195,   19,  195,  197,  197,  197,  197,  197,  197,  197,
      198,  198,  198,  198,  198,  198,  198,  199,  199,  199,
      199,  199,  200,  200,  200,  200,  200,  200,  200,  201,

      201,  201,  201,  201,  201,  201,  202,  202,  202,  202,
      202,  202,  202,  203,  203,  203,  203,  203,  204,  204,
      204,   13,  204,  205,  205,  205,    4,  205,  206,  206,
      206,    3,  206,  207,  207,  207,    0,  207,  208,  208,
      208,    0,  208,  208,  208,  210,  210,  210,  210,  210,
      212,  212,  212,  212,  212,  212,  212,  212,  213,  213,
      213,  213,  213,  213,  213,  214,  214,  214,  214,  214,
      215,  215,  215,  215,  215,  215,  215,  216,  216,  216,
      216,  216,  216,  216,  217,  217,  217,  217,  217,  217,
      217,  218,  218,  218,  218,  218,  218,  218,  219,  219,

      219,  224,  219,  224,  241,  241,  241,  262,  262,  262,
      224,  225,  225,  225,  225,  225,  225,  225,  226,  226,
      226,  226,  226,  226,  226,  227,  227,  227,  227,  227,
      227,  227,  228,  228,  228,  228,  228,  229,  229,  229,
        0,  229,  230,  230,  230,    0,  230,  231,  231,  231,
        0,  231,  232,  232,  232,  234,  232,  233,  233,  233,
        0,  233,  233,  233,  234,    0,    0,  234,  235,  235,
      235,  235,  235,  237,  237,  237,  237,  237,  237,  237,
      238,  238,  238,  238,  238,  238,  238,  239,  265,  265,
      265,  239,  239,  239,  239,  239,  239,  239,  240,  240,

      240,  240,  240,  240,  240,  242,  242,  242,  242,  242,
      242,  242,  244,  244,  244,  244,  244,  244,  244,  245,
      245,  245,  245,  245,  245,  245,  246,  246,  246,  246,
      246,  246,  246,  247,  247,  247,  247,  247,  248,  248,
      248,    0,  248,  249,  249,  249,    0,  249,  250,  250,
      250,    0,  250,  251,  251,  251,  253,  251,  252,  252,
      252,    0,  252,  252,  252,  253,  264,  255,  253,  254,
      254,  254,  254,  254,  255,  264,  256,  255,  256,  266,
      266,  266,  276,  276,  276,  256,  257,  257,  257,  257,
      257,  257,  257,  258,  258,  258,  258,  258,  258,  258,

      259,  259,  259,  259,  259,  259,  259,  260,  280,  280,
      280,  260,  260,  260,  260,  260,  260,  260,  261,  261,
      261,  261,  261,  261,  261,  263,  263,  263,  263,  263,
      263,  263,  267,  271,    0,  284,  267,  267,  267,  278,
      281,  281,  281,  267,  270,  271,  284,    0,  278,  287,
      287,  287,    0,  270,  270,  270,  272,  272,  272,  272,
      272,  272,  272,  273,  273,  273,  273,  273,  273,  273,
      274,  288,  288,  288,  274,  274,  274,  274,  274,  274,
      274,  275,  275,  275,  275,  275,  275,  275,  277,  277,
      277,  277,  277,  277,  277,  282,  286,    0,  291,  282,

      282,  282,  293,    0,    0,    0,  282,  285,  286,  291,
        0,    0,    0,    0,  293,    0,  285,  285,  285,  289,
        0,    0,    0,  289,  289,  289,    0,    0,    0,    0,
      289,  292,    0,    0,    0,    0,    0,    0,    0,    0,
      292,  292,  292,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int members_rs_flex_debug;
int members_rs_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *members_rstext;
#line 1 "members_rs.l"
#line 2 "members_rs.l"
/*
  filename: members_rs.l

  description:
    Defines the tokenizer for an RPSL members_rs attribute.  

  notes:
    Tokens are defined in the associated grammar, members_rs.y.

  $Id: members_rs.lex.c,v 1.2.12.1 2006/09/29 12:32:29 katie Exp $
*/

/******************
  Copyright (c) 2002                              RIPE NCC

  All Rights Reserved

  Permission to use, copy, modify, and distribute this software and its
  documentation for any purpose and without fee is hereby granted,
  provided that the above copyright notice appear in all copies and that
  both that copyright notice and this permission notice appear in
  supporting documentation, and that the name of the author not be
  used in advertising or publicity pertaining to distribution of the
  software without specific, written prior permission.

  THE AUTHOR DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING
  ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS; IN NO EVENT SHALL
  AUTHOR BE LIABLE FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY
  DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN
  AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
  OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
  ***************************************/
#line 50 "members_rs.l"
#include <stdlib.h>
#include <ctype.h>

/* tokens defined in the grammar */
#include "members_rs.tab.h"
void syntax_error(char *fmt, ...);
void yy_input(char *buf, int *result, int max_size);
#undef YY_INPUT
#define YY_INPUT(buf,result,max_size) yy_input(buf,&result,max_size)
#line 915 "members_rs.lex.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int members_rswrap (void );
#else
extern int members_rswrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( members_rstext, members_rsleng, 1, members_rsout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( members_rsin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( members_rsin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, members_rsin))==0 && ferror(members_rsin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(members_rsin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int members_rslex (void);

#define YY_DECL int members_rslex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after members_rstext and members_rsleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 61 "members_rs.l"


#line 1071 "members_rs.lex.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! members_rsin )
			members_rsin = stdin;

		if ( ! members_rsout )
			members_rsout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			members_rsensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				members_rs_create_buffer(members_rsin,YY_BUF_SIZE );
		}

		members_rs_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of members_rstext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 295 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1444 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 63 "members_rs.l"
{ ; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 65 "members_rs.l"
{ return OP_MS; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 66 "members_rs.l"
{ return OP_MS; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 67 "members_rs.l"
{ 
    long int val;
    val = strtol(members_rstext+1, NULL, 10);
    if ((val < 0) || (val > 32)) {
        syntax_error("more specifics operator \"%s\" not 0 to 32 bits", 
                     members_rstext);
    }
    return OP_MS;
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 76 "members_rs.l"
{
    long int val1, val2;
    char *p;
    val1 = strtol(members_rstext+1, &p, 10);
    if ((val1 < 0) || (val1 > 32)) {
        syntax_error("more specifics operator \"%s\" not 0 to 32 bits", 
                     members_rstext);
    }
    val2 = strtol(p+1, NULL, 10);
    if ((val2 < 0) || (val2 > 32)) {
        syntax_error("more specifics operator \"%s\" not 0 to 32 bits", 
                     members_rstext);
    }
    if (val2 < val1) {
        syntax_error("more specifics operator \"%s\" not 0 to 32 bits", 
                     members_rstext);
    }
    return OP_MS;
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 96 "members_rs.l"
{ return TKN_ASNO; }
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 98 "members_rs.l"
{ 
    syntax_error("The RIPE Database currently represents 16-bit AS numbers in \'ASn\' notation");
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 102 "members_rs.l"
{
    return TKN_RSNAME;
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 106 "members_rs.l"
{
    return TKN_ASNAME;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 110 "members_rs.l"
{
    /* check each number of 1.2.3.4/5 in prefix is valid */
    long int val;
    char *s, *p;
    p = s = members_rstext;
    while (*s != '/') {
        val = strtol(p, &s, 10);
        if ((val < 0) || (val > 255)) {
             syntax_error("IP prefix \"%s\" contains an invalid octet", 
                          members_rstext);
        }
        p = s + 1;
    }
    val = strtol(p, NULL, 10);
    if ((val < 0) || (val > 32)) {
        syntax_error("IP prefix \"%s\" contains an invalid prefix length", 
                     members_rstext);
    }
    return TKN_PRFXV4;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 131 "members_rs.l"
{
    /* check each number of 1.2.3.4/5 in prefix is valid, as
       well as any bit ranges specified */
    long int val;
    long int endval;
    char *s, *p;
    p = s = members_rstext;
    while (*s != '/') {
        val = strtol(p, &s, 10);
        if ((val < 0) || (val > 255)) {
             syntax_error("IP prefix \"%s\" contains an invalid octet", 
                          members_rstext);
        }
        p = s + 1;
    }
    val = strtol(p, &s, 10);
    if ((val < 0) || (val > 32)) {
        syntax_error("IP prefix range \"%s\" contains an invalid prefix length",
                     members_rstext);
    }
    p = s + 1;
    if (isdigit((int)*p)) {
        val = strtol(p, &s, 10);
        if ((val < 0) || (val > 32)) {
            syntax_error("IP prefix range \"%s\" contains an invalid range",
                         members_rstext);
        }
        p = s + 1;
        if (isdigit((int)*p)) {
            endval = strtol(p, NULL, 10);
            if ((endval < 0) || (endval > 32)) {
                syntax_error("IP prefix \"%s\" contains an invalid prefix range", 
                             members_rstext);
            }
            if (endval < val) {
                syntax_error("IP prefix \"%s\" range end is less than range start",
                             members_rstext);
            }
        }
    }
    return TKN_PRFXV4RNG;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 174 "members_rs.l"
{ return members_rstext[0]; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 176 "members_rs.l"
ECHO;
	YY_BREAK
#line 1313 "members_rs.lex.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed members_rsin at a new source and called
			 * members_rslex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = members_rsin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( members_rswrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * members_rstext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of members_rslex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					members_rsrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			members_rsrestart(members_rsin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 295 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 295 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 294);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up members_rstext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					members_rsrestart(members_rsin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( members_rswrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve members_rstext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void members_rsrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        members_rsensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            members_rs_create_buffer(members_rsin,YY_BUF_SIZE );
	}

	members_rs_init_buffer(YY_CURRENT_BUFFER,input_file );
	members_rs_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void members_rs_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		members_rspop_buffer_state();
	 *		members_rspush_buffer_state(new_buffer);
     */
	members_rsensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	members_rs_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (members_rswrap()) processing, but the only time this flag
	 * is looked at is after members_rswrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void members_rs_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	members_rsin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE members_rs_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) members_rsalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in members_rs_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) members_rsalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in members_rs_create_buffer()" );

	b->yy_is_our_buffer = 1;

	members_rs_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with members_rs_create_buffer()
 * 
 */
    void members_rs_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		members_rsfree((void *) b->yy_ch_buf  );

	members_rsfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a members_rsrestart() or at EOF.
 */
    static void members_rs_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	members_rs_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then members_rs_init_buffer was _probably_
     * called from members_rsrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void members_rs_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		members_rs_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void members_rspush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	members_rsensure_buffer_stack();

	/* This block is copied from members_rs_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from members_rs_switch_to_buffer. */
	members_rs_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void members_rspop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	members_rs_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		members_rs_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void members_rsensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)members_rsalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)members_rsrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE members_rs_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) members_rsalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in members_rs_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	members_rs_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to members_rslex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       members_rs_scan_bytes() instead.
 */
YY_BUFFER_STATE members_rs_scan_string (yyconst char * yystr )
{
    
	return members_rs_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to members_rslex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE members_rs_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) members_rsalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in members_rs_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = members_rs_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in members_rs_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up members_rstext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		members_rstext[members_rsleng] = (yy_hold_char); \
		(yy_c_buf_p) = members_rstext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		members_rsleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int members_rsget_lineno  (void)
{
        
    return members_rslineno;
}

/** Get the input stream.
 * 
 */
FILE *members_rsget_in  (void)
{
        return members_rsin;
}

/** Get the output stream.
 * 
 */
FILE *members_rsget_out  (void)
{
        return members_rsout;
}

/** Get the length of the current token.
 * 
 */
int members_rsget_leng  (void)
{
        return members_rsleng;
}

/** Get the current token.
 * 
 */

char *members_rsget_text  (void)
{
        return members_rstext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void members_rsset_lineno (int  line_number )
{
    
    members_rslineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see members_rs_switch_to_buffer
 */
void members_rsset_in (FILE *  in_str )
{
        members_rsin = in_str ;
}

void members_rsset_out (FILE *  out_str )
{
        members_rsout = out_str ;
}

int members_rsget_debug  (void)
{
        return members_rs_flex_debug;
}

void members_rsset_debug (int  bdebug )
{
        members_rs_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from members_rslex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    members_rsin = stdin;
    members_rsout = stdout;
#else
    members_rsin = (FILE *) 0;
    members_rsout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * members_rslex_init()
     */
    return 0;
}

/* members_rslex_destroy is for both reentrant and non-reentrant scanners. */
int members_rslex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		members_rs_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		members_rspop_buffer_state();
	}

	/* Destroy the stack itself. */
	members_rsfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * members_rslex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *members_rsalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *members_rsrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void members_rsfree (void * ptr )
{
	free( (char *) ptr );	/* see members_rsrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 176 "members_rs.l"



void
members_rs_reset ()
{
    members_rs_flush_buffer(YY_CURRENT_BUFFER);
}


int members_rswrap() { return 1; }

