#define yy_create_buffer mp_default_create_buffer
#define yy_delete_buffer mp_default_delete_buffer
#define yy_scan_buffer mp_default_scan_buffer
#define yy_scan_string mp_default_scan_string
#define yy_scan_bytes mp_default_scan_bytes
#define yy_flex_debug mp_default_flex_debug
#define yy_init_buffer mp_default_init_buffer
#define yy_flush_buffer mp_default_flush_buffer
#define yy_load_buffer_state mp_default_load_buffer_state
#define yy_switch_to_buffer mp_default_switch_to_buffer
#define yyin mp_defaultin
#define yyleng mp_defaultleng
#define yylex mp_defaultlex
#define yyout mp_defaultout
#define yyrestart mp_defaultrestart
#define yytext mp_defaulttext
#define yywrap mp_defaultwrap

#line 20 "mp_default.lex.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 60
#define YY_END_OF_BUFFER 61
static yyconst short int yy_accept[418] =
    {   0,
        0,    0,   61,   59,    1,    1,   59,   57,   59,    6,
       58,   59,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   59,   59,    1,    7,    0,
        0,   57,    0,   58,   58,   55,    5,    9,    8,   10,
        0,   58,   58,   58,   58,   58,   26,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,    2,   58,   58,
       58,   58,   14,    0,   37,   38,    0,    0,   57,   58,
       56,    0,    0,   55,    0,   58,   27,    3,   12,   58,
        0,   42,   58,   58,   58,   58,   58,   32,   58,   58,
       58,   58,   31,   58,   58,    0,    4,   58,   58,   58,

        0,   58,    0,    0,   57,   58,   56,    0,    0,   52,
       55,    0,   11,   58,   58,    0,   44,    0,    0,   58,
       58,   58,   36,   58,   58,    0,   58,   28,   29,   58,
       58,    0,    0,   58,   30,   58,   58,    0,   45,    0,
       18,    0,    0,   57,   56,    0,    0,    0,   55,   55,
       58,   58,    0,   44,    0,    0,    0,    0,   58,   58,
       58,   58,    0,    0,   58,    0,    0,   58,    0,    0,
        0,   58,   58,    0,    0,   45,    0,   39,    0,    0,
       56,    0,    0,    0,   49,   49,   55,   55,    0,   15,
       20,    0,    0,    0,    0,    0,    0,    0,   33,   58,

       58,   21,    0,   43,    0,    0,   58,    0,    0,    0,
        0,   58,    0,    0,    0,   13,   58,    0,   46,    0,
        0,    0,    0,    0,   41,   53,   56,    0,    0,    0,
       55,   55,    0,    0,    0,    0,    0,    0,    0,    0,
       58,   58,    0,   43,    0,   58,    0,    0,    0,    0,
       58,    0,    0,    0,   19,    0,   46,    0,    0,    0,
        0,    0,    0,    0,    0,   49,   55,   55,    0,    0,
       44,    0,    0,    0,    0,   58,   22,    0,    0,    0,
       17,   23,    0,    0,    0,    0,   16,   35,    0,    0,
        0,    0,   45,    0,    0,    0,   50,    0,    0,   55,

       55,    0,   44,    0,    0,    0,    0,   34,    0,    0,
        0,    0,    0,    0,    0,    0,   24,    0,    0,    0,
        0,    0,   45,   40,    0,    0,    0,    0,   55,   55,
        0,    0,    0,   43,    0,    0,    0,    0,    0,    0,
        0,   46,    0,    0,    0,   47,   47,    0,    0,   55,
       55,   44,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   45,    0,    0,    0,    0,   55,   55,    0,    0,
        0,    0,   28,    0,   29,   25,    0,    0,   47,    0,
        0,   55,   55,    0,   43,   43,    0,    0,   46,    0,
       46,    0,    0,    0,   55,   55,    0,    0,   54,   55,

       55,    0,    0,   54,   55,   55,   51,   54,   55,    0,
       54,   55,   48,   48,    0,   48,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,   10,   10,   10,
       10,   11,   10,   12,   10,   10,   10,   13,    1,    1,
       14,    1,    1,    1,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
       27,   34,   35,   36,   37,   38,   39,   40,   41,   27,
        1,    1,    1,   16,   17,    1,   18,   19,   20,   21,

       22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
       32,   33,   27,   34,   35,   36,   37,   38,   39,   40,
       41,   27,   42,    1,   43,   44,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[45] =
    {   0,
        1,    1,    1,    1,    1,    1,    2,    3,    4,    5,
        5,    5,    6,    1,    7,    1,    8,    5,    5,    5,
        5,    5,    5,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    1,    1,    1
    } ;

static yyconst short int yy_base[487] =
    {   0,
        0,    0, 1202, 1203,   43,   45, 1187,   42, 1187, 1185,
       59,   63,   69,  104, 1166,   36, 1168,  121,  124,  128,
      131,  135,  148,  151,  155, 1170,  162,   54, 1203,   70,
      108,  197,  164,  171,  178, 1186, 1203, 1203, 1203,  185,
     1181,  190,  104,  214,  199,  249,  200,  210,  170,  218,
      233,  213,  234,  248,  254,  259,  260,  270,  276,  280,
      240,  307,  255, 1162, 1203, 1203, 1166,  311,  327,  316,
      201, 1178,  160,  138,  170,  327,  344,  347,  351,  354,
      301,  299,  361,  358,  365,  373,  376,  383,  386,  395,
      397,  410,  417,  419,  421,  131,  428,  430,  383,  409,

      326,  421, 1154,  436,  455,  442,  459, 1176, 1175,  463,
      216,    0,  449,  469,  454,  370,  473,  221,  466,  471,
      472,  488,  484,  487,  484, 1167,  517,  519,  521,  528,
      530, 1165, 1145,  532,  541,  545,  548,  555,  556,  375,
      567,  233,  571,  577,  581, 1171, 1170,  590,  241,  402,
      533,  575,   53,  596, 1147, 1152,   99, 1145,  586,  574,
      590,  596,  561, 1147,  591,  280,  326,  601, 1153, 1139,
     1143,  606,  607,  629,  480,  635,  245, 1203,  639,  643,
      646, 1162, 1161, 1160, 1203,  653,  533,  634,    0,  637,
      638, 1137, 1149,  665, 1134, 1147, 1137, 1160,  649,  655,

      654,  659,  682,  687,  476, 1131,  674, 1128, 1133, 1091,
     1096,  682, 1093, 1102, 1089,  701,  704,  686,  709,  667,
     1085, 1096, 1082, 1049, 1203,  709,  717, 1066, 1064,  720,
      682,  724,  728, 1054,  727,  735, 1039, 1038, 1046,  734,
      742,  745,  736,  749, 1033,  757, 1020, 1022, 1017, 1019,
      760, 1009, 1007, 1005,  764,  256,  768,  772, 1016, 1020,
      989,  776, 1011, 1007, 1005,  779,  748,  783,    0,  787,
      787,  983,  997,  985,  994,  794,  798,  965,  968,  974,
     1203,  801,  958,  973,  946,  960,  805, 1203,  943,  939,
      938,  308,  809,  938,  808,  915,  816,  933,  932,  820,

      821,  824,  829,  922,  830,  904,  831,  832,  839,  899,
      902,  897,  894,  885,  878,  858, 1203,  842,  849,  839,
      826,  848,  849, 1203,  862,  830,  811,  810,  848,  850,
        0,  782,  803,  865,  776,  769,  759,  741,  754,  728,
      725,  869,  709,  718,  701, 1203,  876,  710,  654,  851,
      876,  653,  638,  615,  610,  590,  594,  568,  564,  559,
      558,  546,  880,  531,  520,  518,  884,  885,    0,  851,
      487,  481, 1203,  475, 1203, 1203,  459,  888,  889,  468,
      443,  893,  894,  897,  902,  440,  415,  403,  418,  901,
      903,  400,  387,  384,  904,  912,    0,  382,  366,  913,

      361,  331,  917,  322,  921,  316,  921,  296,  288,  931,
      243,  185, 1203,  937,  940,  943, 1203,  954,  957,  960,
      961,  964,  969,  976,  980,  982,  985,  188,  990,  997,
     1001, 1003, 1006, 1009, 1014, 1021, 1025, 1027, 1030,  180,
     1035, 1042, 1046, 1048, 1051, 1054, 1056, 1058, 1061,  108,
     1066, 1073, 1077, 1079, 1082, 1085, 1087, 1089, 1092,   80,
     1094, 1096, 1099, 1102, 1104, 1106, 1109,   54, 1114, 1121,
     1125, 1127, 1130, 1133, 1135, 1137, 1140,   46, 1142, 1145,
     1147, 1150, 1152, 1154, 1156, 1158
    } ;

static yyconst short int yy_def[487] =
    {   0,
      417,    1,  417,  417,  417,  417,  417,  418,  417,  417,
      418,  417,  417,  418,   14,   14,   14,  418,  418,  418,
      418,  418,  418,  418,  418,  417,  417,  417,  417,  418,
      417,   14,  419,  418,   32,  420,  417,  417,  417,  417,
      419,   32,   42,  418,   18,   18,   18,   18,   42,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
      418,  418,  418,  417,  417,  417,  417,  417,   32,   69,
      421,  421,  417,  422,  417,  418,  418,  418,  418,  418,
      423,   46,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  417,  418,  418,   18,   18,

      424,   18,  417,  417,  418,  418,  425,  426,  425,  417,
      427,  428,  417,  418,   18,  423,  423,  429,  417,   18,
       18,   18,   18,   18,  418,  417,  418,  418,  418,  418,
      418,  417,  417,  418,  418,  418,  418,  424,  424,  430,
      418,  417,  417,  418,  431,  431,  432,  417,  433,  434,
       18,   18,  417,  429,  417,  417,  417,  417,   18,   18,
       18,   18,  435,  417,   18,  417,  417,   18,  417,  417,
      417,   18,   18,  436,  417,  430,  417,  417,  417,  417,
      417,  417,  437,  438,  417,  417,  417,  439,  440,   18,
       18,  417,  417,  417,  417,  417,  417,  417,   18,   18,

       18,   18,  435,  435,  441,  417,   18,  417,  417,  417,
      417,   18,  417,  417,  417,  418,  418,  436,  436,  442,
      417,  417,  417,  417,  417,  417,  417,  443,  444,  417,
      445,  446,  417,  417,  429,  417,  417,  417,  417,  430,
      418,  418,  417,  441,  417,  418,  417,  417,  417,  417,
      418,  417,  417,  417,  418,  417,  442,  417,  417,  417,
      417,  417,  417,  447,  448,  417,  417,  449,  450,  451,
      417,  417,  417,  417,  417,  418,  418,  417,  417,  417,
      417,  418,  417,  417,  417,  417,  418,  417,  417,  417,
      417,  417,  417,  417,  452,  417,  417,  453,  454,  455,

      456,  451,  451,  417,  441,  417,  442,  418,  417,  417,
      417,  417,  417,  417,  417,  417,  417,  417,  417,  417,
      417,  452,  452,  417,  417,  417,  457,  458,  417,  459,
      460,  417,  417,  417,  417,  417,  417,  417,  417,  417,
      417,  417,  417,  417,  417,  417,  417,  461,  462,  463,
      464,  417,  417,  417,  417,  417,  417,  417,  417,  417,
      417,  417,  417,  417,  465,  466,  417,  467,  468,  469,
      417,  417,  417,  417,  417,  417,  417,  470,  417,  471,
      472,  473,  474,  469,  469,  417,  417,  417,  417,  470,
      470,  417,  475,  476,  417,  477,  478,  479,  480,  481,

      482,  417,  417,  483,  417,  484,  417,  485,  486,  417,
      417,  417,  417,  417,  417,  417,    0,  417,  417,  417,
      417,  417,  417,  417,  417,  417,  417,  417,  417,  417,
      417,  417,  417,  417,  417,  417,  417,  417,  417,  417,
      417,  417,  417,  417,  417,  417,  417,  417,  417,  417,
      417,  417,  417,  417,  417,  417,  417,  417,  417,  417,
      417,  417,  417,  417,  417,  417,  417,  417,  417,  417,
      417,  417,  417,  417,  417,  417,  417,  417,  417,  417,
      417,  417,  417,  417,  417,  417
    } ;

static yyconst short int yy_nxt[1248] =
    {   0,
        4,    5,    6,    4,    4,    4,    4,    7,    4,    8,
        8,    8,    9,   10,   11,   12,    4,   13,   14,   15,
       16,   14,   17,   11,   11,   18,   11,   11,   11,   19,
       20,   21,   22,   23,   24,   25,   11,   11,   11,   11,
       11,   26,    4,   27,   28,   28,   28,   28,   30,   31,
      401,   32,   32,   32,   33,   28,   28,   49,  383,   35,
       35,   35,   35,   35,   35,   30,  417,   38,   50,   39,
      192,  417,   40,   40,   40,   30,   30,  417,   35,   35,
       35,   41,  417,   34,  351,  193,   35,   35,   42,   35,
       35,   43,   34,   34,   34,   34,   34,   34,   34,   44,

       34,   45,   34,   46,   47,   34,   34,   34,   34,   34,
       30,  417,  301,   35,   35,   35,   41,   68,   68,   68,
      196,   35,   35,   35,   35,   35,   35,   30,  417,   77,
       30,  417,  197,  417,   30,  417,  417,   30,  417,   34,
      417,   30,  417,  417,   52,   55,   73,  417,  132,   56,
      112,   53,  133,   54,   30,  417,   59,   30,  417,   57,
      417,   30,  417,  417,   58,   65,   66,  417,   60,  110,
      110,  110,   62,   71,   71,   71,   36,   30,  417,  113,
      113,  113,   61,  417,  232,  417,   63,   70,   70,   70,
       41,   75,  150,   73,   40,   40,   40,  417,   87,   70,

       70,   70,   41,   67,   31,   34,   69,   69,   69,   33,
      107,  107,  107,  108,   70,   70,   70,   70,   70,   70,
       30,  417,   34,   34,   73,   76,  417,  118,  112,   34,
       34,   80,   34,   34,   78,   88,   34,  118,  177,   84,
       85,   34,   34,   34,   86,   90,  101,  417,   34,   73,
       34,  403,  417,  112,   79,   81,   34,   34,   82,   82,
       82,   30,  417,   34,   34,   34,   34,  417,   89,   91,
      224,   34,   34,  291,   93,  178,   96,   34,   34,   34,
       34,   83,   34,   34,   34,   92,   34,  225,  292,   34,
       34,   34,   34,   34,   94,   97,   73,   98,   95,   34,

       34,   99,   34,   34,  403,   30,   34,  116,   34,  208,
      100,  119,   34,   30,  417,   34,  209,  118,  104,  417,
       68,   68,   68,  417,   73,  106,  106,  106,   41,  319,
      403,   34,  138,   30,  417,  102,  105,  105,  105,  417,
       34,  320,  140,  394,  106,  106,  106,  106,  106,  106,
       30,  417,  114,   30,  417,  210,  417,   30,  417,  417,
       30,  417,  211,  417,   30,  417,  417,   30,  417,   73,
      417,   30,  417,  417,  403,  115,  116,  417,  120,   30,
      417,  140,   30,  417,   34,  417,  118,  121,  417,   30,
      417,  140,   30,  417,  394,  417,   36,  124,  417,  394,

      122,   30,  417,   30,  417,  135,   34,  417,  123,  417,
       73,  126,  366,   34,  189,  136,   30,  417,  127,  125,
      128,  129,  417,   30,  417,   30,  417,   30,  417,  417,
      256,  417,  137,  417,   30,  417,   30,  417,  375,   34,
      417,   34,  417,  141,   34,  143,  143,  143,   30,  417,
      373,   34,  243,   34,   41,  394,  131,  130,  113,  113,
      113,   30,   31,  134,  144,  144,  144,   33,  145,  145,
      145,  108,  110,  110,  110,   30,  417,   34,  148,  116,
      366,  417,  205,  155,  152,  153,   34,   34,  156,  118,
      163,  417,  205,  389,   34,   34,  417,  221,  157,  158,

      151,   34,   34,   34,   34,  161,  159,   34,  160,  388,
       34,   34,  222,  223,   34,  387,   34,   34,   34,   34,
       34,  386,  162,   30,  417,   30,  166,   30,  167,  417,
       36,  417,  366,  417,   30,  417,   30,  417,   30,  417,
      417,   73,  417,  328,  417,  112,  169,   30,  417,  172,
      165,   30,  417,  417,  174,  417,   34,  417,  175,  168,
      417,  138,  138,  190,  378,   34,  173,  203,  175,   34,
       34,  140,  140,   30,  417,   34,  377,  205,  179,  417,
      143,  143,  143,   30,   31,  376,  144,  144,  144,  180,
      181,  181,  181,  108,  185,  191,  185,   34,   34,  186,

      186,  186,  118,  375,  200,   34,   34,   34,  153,   34,
      199,  374,  118,   34,   34,  201,   34,  202,   34,   34,
       34,  207,   34,   34,   34,  373,   34,  372,   34,   34,
       34,   34,  371,   34,  212,  218,   34,  217,   34,   34,
      216,  140,   73,   34,  370,  220,  189,  175,  226,  226,
      226,  140,  227,  227,  227,  227,  227,  227,  108,  230,
       34,   34,  186,  186,  186,  153,  366,   34,   34,   34,
       34,  235,   34,  220,  236,  236,  236,   34,   34,   34,
      241,   34,   34,  220,  242,   34,   34,   34,  203,   34,
       73,   34,  218,  203,  189,  246,   34,   34,  205,  243,

       34,   34,  220,  205,   34,   34,   34,   30,  417,  251,
       30,  417,   34,  119,   34,  218,  417,  262,  226,  226,
      226,  256,  328,   34,  255,  220,  227,  227,  227,  266,
      266,  266,   73,  118,  270,  362,  269,  271,  271,  271,
      140,  361,  360,  118,  236,  236,  236,  119,   30,  417,
      140,   30,  417,  278,  417,  205,   73,  417,  279,  359,
      189,  243,  358,   30,  417,  205,   30,  417,  280,  417,
       30,  417,  417,  357,  220,  356,  417,  276,  355,  277,
      256,  293,  293,  293,  220,  297,  297,  297,  266,  266,
      266,   73,  282,  302,  287,  269,  271,  271,  271,  153,

       30,  417,  354,  302,   30,  417,  417,   30,  417,  353,
      417,   30,  417,  417,  322,  119,  352,  417,  293,  293,
      293,  175,   36,  328,  322,  297,  297,  297,   73,   73,
      302,  325,  269,  331,  308,  302,  205,  220,   30,  417,
      302,  153,  265,  345,  417,  302,  205,  220,  334,  334,
      334,  342,  342,  342,  322,  322,   73,  384,   73,   73,
      269,  175,  331,  331,  322,  322,  346,  384,  346,  344,
      343,  347,  347,  347,  334,  334,  334,  243,  342,  342,
      342,  256,  363,  341,   73,  347,  347,  347,  369,  379,
      379,  379,   73,   73,  390,  340,  331,  369,  379,  379,

      379,   73,   73,  384,  390,  369,  397,  390,  384,  390,
      339,  338,   73,  384,  243,  256,  369,  390,  384,  390,
       73,   73,  337,  336,  397,  397,  407,  407,  407,   73,
      407,  407,  407,  397,  335,  413,  410,  413,  333,  332,
      414,  414,  414,  415,  328,  265,  414,  414,  414,  416,
      416,  416,  416,  416,  416,   34,   34,  324,   34,   34,
       34,   72,   72,   74,   74,  109,  109,  111,  111,  111,
      117,  321,  318,  117,  317,  117,  117,  139,  316,  315,
      139,  314,  139,  139,  146,  146,  147,  147,  149,  149,
      149,  154,  313,  312,  154,  311,  310,  154,  176,  309,

      307,  176,  306,  305,  176,  182,  182,  183,  183,  187,
      187,  187,  188,  188,  188,  204,  304,   36,  204,  265,
      204,  204,  219,  184,  296,  219,  295,  219,  219,  228,
      228,  229,  229,  231,  231,  231,  244,  294,  290,  244,
      289,  288,  244,  257,  286,  285,  257,  284,  283,  257,
      263,  263,  264,  264,  267,  267,  267,  268,  268,  268,
      298,  298,  299,  299,  300,  300,  300,  303,  281,  275,
      303,  274,  273,  303,  323,  272,  265,  323,  184,  261,
      323,  326,  326,  327,  327,  329,  329,  329,  330,  330,
      330,  348,  348,  349,  349,  350,  350,  350,  364,  364,

      365,  365,  367,  367,  367,  368,  368,  368,  380,  380,
      381,  381,  382,  382,  382,  385,  260,  259,  385,  258,
      254,  385,  391,  253,  252,  391,  250,  249,  391,  392,
      392,  393,  393,  395,  395,  395,  396,  396,  396,  398,
      398,  399,  399,  400,  400,  400,  402,  402,  404,  404,
      405,  405,  405,  406,  406,  408,  408,  409,  409,  411,
      411,  412,  412,  248,  247,  245,  240,  239,  238,  237,
      234,  233,   36,  184,  108,  215,  214,  213,  206,  198,
      195,  194,  184,  108,  171,  170,  164,  108,   36,  142,
      108,   64,  103,   36,   73,   64,   51,   48,   37,   36,

       29,  417,    3,  417,  417,  417,  417,  417,  417,  417,
      417,  417,  417,  417,  417,  417,  417,  417,  417,  417,
      417,  417,  417,  417,  417,  417,  417,  417,  417,  417,
      417,  417,  417,  417,  417,  417,  417,  417,  417,  417,
      417,  417,  417,  417,  417,  417,  417
    } ;

static yyconst short int yy_chk[1248] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    5,    5,    6,    6,    8,    8,
      478,    8,    8,    8,    8,   28,   28,   16,  468,    8,
        8,    8,    8,    8,    8,   11,   11,   12,   16,   12,
      153,   11,   12,   12,   12,   13,   30,   30,   13,   13,
       13,   13,   30,   13,  460,  153,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,

       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       14,   14,  450,   14,   14,   14,   14,   31,   31,   31,
      157,   14,   14,   14,   14,   14,   14,   18,   18,   43,
       19,   19,  157,   18,   20,   20,   19,   21,   21,   43,
       20,   22,   22,   21,   18,   19,   74,   22,   96,   20,
       74,   18,   96,   18,   23,   23,   22,   24,   24,   20,
       23,   25,   25,   24,   21,   27,   27,   25,   22,   73,
       73,   73,   24,   33,   33,   33,   33,   34,   34,   75,
       75,   75,   23,   34,  440,   35,   25,   35,   35,   35,
       35,   40,  428,  412,   40,   40,   40,   42,   49,   42,

       42,   42,   42,   27,   32,   49,   32,   32,   32,   32,
       71,   71,   71,   71,   32,   32,   32,   32,   32,   32,
       44,   44,   45,   47,  111,   42,   44,  118,  111,   45,
       47,   45,   47,   48,   44,   50,   52,  118,  142,   48,
       48,   50,   48,   52,   48,   52,   61,   61,   50,  149,
       50,  411,   61,  149,   44,   46,   51,   53,   46,   46,
       46,   63,   63,   51,   53,   51,   53,   63,   51,   53,
      177,   54,   46,  256,   55,  142,   57,   55,   54,   46,
       54,   46,   56,   57,   55,   54,   55,  177,  256,   56,
       57,   56,   57,   58,   56,   57,  409,   59,   56,   59,

       58,   60,   58,   60,  408,   82,   59,   81,   59,  166,
       60,   82,   60,   62,   62,   81,  166,   81,   68,   62,
       68,   68,   68,   70,  406,   70,   70,   70,   70,  292,
      404,   82,  101,   76,   76,   62,   69,   69,   69,   76,
      101,  292,  101,  402,   69,   69,   69,   69,   69,   69,
       77,   77,   76,   78,   78,  167,   77,   79,   79,   78,
       80,   80,  167,   79,   84,   84,   80,   83,   83,  401,
       84,   85,   85,   83,  399,   80,  116,   85,   83,   86,
       86,  140,   87,   87,  116,   86,  116,   84,   87,   88,
       88,  140,   89,   89,  398,   88,  394,   87,   89,  393,

       85,   90,   90,   91,   91,   99,   99,   90,   86,   91,
      150,   90,  392,   99,  150,   99,   92,   92,   91,   89,
       92,   92,   92,   93,   93,   94,   94,   95,   95,   93,
      389,   94,  100,   95,   97,   97,   98,   98,  388,  100,
       97,  100,   98,  102,  102,  104,  104,  104,  106,  106,
      387,  102,  386,  102,  106,  381,   95,   94,  113,  113,
      113,  105,  105,   98,  105,  105,  105,  105,  107,  107,
      107,  107,  110,  110,  110,  114,  114,  115,  110,  117,
      380,  114,  205,  119,  115,  117,  115,  117,  119,  117,
      125,  125,  205,  377,  120,  121,  125,  175,  119,  119,

      114,  120,  121,  120,  121,  122,  120,  123,  121,  374,
      124,  122,  175,  175,  123,  372,  123,  124,  122,  124,
      122,  371,  124,  127,  127,  128,  128,  129,  129,  127,
      366,  128,  365,  129,  130,  130,  131,  131,  134,  134,
      130,  187,  131,  364,  134,  187,  131,  135,  135,  134,
      127,  136,  136,  135,  137,  137,  151,  136,  362,  130,
      137,  138,  139,  151,  361,  151,  136,  163,  139,  138,
      139,  138,  139,  141,  141,  163,  360,  163,  143,  141,
      143,  143,  143,  144,  144,  359,  144,  144,  144,  144,
      145,  145,  145,  145,  148,  152,  148,  160,  152,  148,

      148,  148,  154,  358,  160,  152,  160,  152,  154,  159,
      159,  357,  154,  161,  165,  161,  159,  162,  159,  162,
      161,  165,  161,  165,  168,  356,  162,  355,  162,  172,
      173,  168,  354,  168,  168,  174,  172,  173,  172,  173,
      172,  176,  188,  174,  353,  174,  188,  176,  179,  179,
      179,  176,  180,  180,  180,  181,  181,  181,  181,  186,
      190,  191,  186,  186,  186,  352,  349,  190,  191,  190,
      191,  194,  199,  220,  194,  194,  194,  201,  200,  199,
      200,  199,  202,  220,  201,  200,  201,  200,  203,  202,
      231,  202,  218,  204,  231,  207,  203,  207,  203,  204,

      218,  204,  218,  204,  207,  212,  207,  216,  216,  212,
      217,  217,  212,  216,  212,  219,  217,  226,  226,  226,
      226,  219,  348,  219,  217,  219,  227,  227,  227,  230,
      230,  230,  232,  235,  233,  345,  232,  233,  233,  233,
      240,  344,  343,  235,  236,  236,  236,  236,  241,  241,
      240,  242,  242,  243,  241,  244,  267,  242,  243,  341,
      267,  244,  340,  246,  246,  244,  251,  251,  243,  246,
      255,  255,  251,  339,  257,  338,  255,  241,  337,  242,
      257,  258,  258,  258,  257,  262,  262,  262,  266,  266,
      266,  268,  246,  270,  251,  268,  271,  271,  271,  271,

      276,  276,  336,  270,  277,  277,  276,  282,  282,  335,
      277,  287,  287,  282,  295,  333,  332,  287,  293,  293,
      293,  293,  328,  327,  295,  297,  297,  297,  300,  301,
      302,  297,  300,  301,  276,  303,  305,  307,  308,  308,
      302,  303,  326,  321,  308,  303,  305,  307,  309,  309,
      309,  318,  318,  318,  322,  323,  329,  370,  330,  350,
      329,  323,  330,  350,  322,  323,  325,  370,  325,  320,
      319,  325,  325,  325,  334,  334,  334,  334,  342,  342,
      342,  342,  347,  316,  351,  347,  347,  347,  351,  363,
      363,  363,  367,  368,  378,  315,  367,  368,  379,  379,

      379,  382,  383,  384,  378,  382,  383,  390,  385,  391,
      314,  313,  395,  384,  385,  391,  395,  390,  385,  391,
      396,  400,  312,  311,  396,  400,  403,  403,  403,  405,
      407,  407,  407,  405,  310,  410,  407,  410,  306,  304,
      410,  410,  410,  414,  299,  298,  414,  414,  414,  415,
      415,  415,  416,  416,  416,  418,  418,  296,  418,  418,
      418,  419,  419,  420,  420,  421,  421,  422,  422,  422,
      423,  294,  291,  423,  290,  423,  423,  424,  289,  286,
      424,  285,  424,  424,  425,  425,  426,  426,  427,  427,
      427,  429,  284,  283,  429,  280,  279,  429,  430,  278,

      275,  430,  274,  273,  430,  431,  431,  432,  432,  433,
      433,  433,  434,  434,  434,  435,  272,  265,  435,  264,
      435,  435,  436,  263,  261,  436,  260,  436,  436,  437,
      437,  438,  438,  439,  439,  439,  441,  259,  254,  441,
      253,  252,  441,  442,  250,  249,  442,  248,  247,  442,
      443,  443,  444,  444,  445,  445,  445,  446,  446,  446,
      447,  447,  448,  448,  449,  449,  449,  451,  245,  239,
      451,  238,  237,  451,  452,  234,  229,  452,  228,  224,
      452,  453,  453,  454,  454,  455,  455,  455,  456,  456,
      456,  457,  457,  458,  458,  459,  459,  459,  461,  461,

      462,  462,  463,  463,  463,  464,  464,  464,  465,  465,
      466,  466,  467,  467,  467,  469,  223,  222,  469,  221,
      215,  469,  470,  214,  213,  470,  211,  210,  470,  471,
      471,  472,  472,  473,  473,  473,  474,  474,  474,  475,
      475,  476,  476,  477,  477,  477,  479,  479,  480,  480,
      481,  481,  481,  482,  482,  483,  483,  484,  484,  485,
      485,  486,  486,  209,  208,  206,  198,  197,  196,  195,
      193,  192,  184,  183,  182,  171,  170,  169,  164,  158,
      156,  155,  147,  146,  133,  132,  126,  109,  108,  103,
       72,   67,   64,   41,   36,   26,   17,   15,   10,    9,

        7,    3,  417,  417,  417,  417,  417,  417,  417,  417,
      417,  417,  417,  417,  417,  417,  417,  417,  417,  417,
      417,  417,  417,  417,  417,  417,  417,  417,  417,  417,
      417,  417,  417,  417,  417,  417,  417,  417,  417,  417,
      417,  417,  417,  417,  417,  417,  417
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "mp_default.l"
#define INITIAL 0
#line 2 "mp_default.l"
/*
  filename: mp_default.l

  description:
    Defines the tokenizer for an RPSLng mp-default attribute. Derived
   from default.l. 

  notes:
    Tokens are defined in the associated grammar, mp_default.y.

  $Id: mp_default.l,v 1.2 2004/12/10 16:37:37 can Exp $
*/

#line 42 "mp_default.l"
#include <string.h>
#include <stdlib.h>
#include <ctype.h>

/* tokens defined in the grammar */
#include "mp_default.tab.h"


#define mp_defaultwrap yywrap
void syntax_error(char *fmt, ...);
void yy_input(char *buf, int *result, int max_size);
#undef YY_INPUT
#define YY_INPUT(buf,result,max_size) yy_input(buf,&result,max_size)
#define YY_NO_UNPUT  /* otherwise we get compiler warnings "`yyunput' defined but not used" */

#line 837 "mp_default.lex.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 59 "mp_default.l"


#line 991 "mp_default.lex.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 418 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1203 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 61 "mp_default.l"
{ ; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 63 "mp_default.l"
{ return OP_OR; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 64 "mp_default.l"
{ return OP_AND; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 65 "mp_default.l"
{ return OP_NOT; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 66 "mp_default.l"
{ return OP_COMPARE; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 67 "mp_default.l"
{ return OP_EQUAL; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 68 "mp_default.l"
{ return OP_APPEND; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 70 "mp_default.l"
{ return OP_MS; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 71 "mp_default.l"
{ return OP_MS; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 72 "mp_default.l"
{ 
    long int val;
    val = strtol(yytext+1, NULL, 10);
    if ((val < 0) || (val > 32)) {
        syntax_error("more specifics operator \"%s\" not 0 to 32 bits", 
                     yytext);
    }
    return OP_MS;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 81 "mp_default.l"
{
    long int val1, val2;
    char *p;
    val1 = strtol(yytext+1, &p, 10);
    if ((val1 < 0) || (val1 > 32)) {
        syntax_error("more specifics operator \"%s\" not 0 to 32 bits", 
                     yytext);
    }
    val2 = strtol(p+1, NULL, 10);
    if ((val2 < 0) || (val2 > 32)) {
        syntax_error("more specifics operator \"%s\" not 0 to 32 bits", 
                     yytext);
    }
    if (val2 < val1) {
        syntax_error("more specifics operator \"%s\" not 0 to 32 bits", 
                     yytext);
    }
    return OP_MS;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 102 "mp_default.l"
{ return KEYW_ANY; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 103 "mp_default.l"
{ return KEYW_PEERAS; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 105 "mp_default.l"
{ return KEYW_TO; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 106 "mp_default.l"
{ return KEYW_ACTION; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 107 "mp_default.l"
{ return KEYW_NETWORKS; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 108 "mp_default.l"
{ return KEYW_IGP_COST; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 109 "mp_default.l"
{ return KEYW_SELF; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 110 "mp_default.l"
{ return KEYW_PREPEND; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 111 "mp_default.l"
{ return KEYW_APPEND; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 112 "mp_default.l"
{ return KEYW_DELETE; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 113 "mp_default.l"
{ return KEYW_CONTAINS; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 115 "mp_default.l"
{ return KEYW_INTERNET; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 116 "mp_default.l"
{ return KEYW_NO_EXPORT; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 117 "mp_default.l"
{ return KEYW_NO_ADVERTISE; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 119 "mp_default.l"
{ return KEYW_AT; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 121 "mp_default.l"
{ return KEYW_AFI; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 123 "mp_default.l"
{ return KEYW_AFI_VALUE_V4; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 124 "mp_default.l"
{ return KEYW_AFI_VALUE_V6; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 126 "mp_default.l"
{ return TKN_PREF; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 127 "mp_default.l"
{ return TKN_MED; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 128 "mp_default.l"
{ return TKN_DPA; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 129 "mp_default.l"
{ return TKN_ASPATH; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 130 "mp_default.l"
{ return TKN_COMMUNITY; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 131 "mp_default.l"
{ return TKN_NEXT_HOP; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 132 "mp_default.l"
{ return TKN_COST; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 134 "mp_default.l"
{ return ASPATH_POSTFIX; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 135 "mp_default.l"
{ return ASPATH_POSTFIX; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 136 "mp_default.l"
{ return ASPATH_POSTFIX; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 137 "mp_default.l"
{ return ASPATH_POSTFIX; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 138 "mp_default.l"
{ return ASPATH_POSTFIX; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 140 "mp_default.l"
{
    long int val;
    char *s;
    val = strtol(yytext+2, &s, 10);
    if ((val < 0) || (val > 65535) || (*s != '\0')) {
        syntax_error("AS number \"%s\" is not between 0 and 65535", yytext);
    }
    return TKN_ASNO;
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 150 "mp_default.l"
{
    return TKN_FLTRNAME;
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 154 "mp_default.l"
{
    return TKN_ASNAME;
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 158 "mp_default.l"
{
    return TKN_RSNAME;
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 162 "mp_default.l"
{
    return TKN_PRNGNAME; 
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 166 "mp_default.l"
{
    /* check each number of 1.2.3.4/5 in prefix is valid, as
       well as any bit ranges specified */
    long int val;
    long int endval;
    char *s, *p;
    p = s = yytext;
    while (*s != '/') {
        val = strtol(p, &s, 10);
        if ((val < 0) || (val > 255)) {
             syntax_error("IP prefix \"%s\" contains an invalid octet", 
                          yytext);
        }
        p = s + 1;
    }
    val = strtol(p, &s, 10);
    if ((val < 0) || (val > 32)) {
        syntax_error("IP prefix range \"%s\" contains an invalid prefix length",
                     yytext);
    }
    p = s + 1;
    if (isdigit((int)*p)) {
        val = strtol(p, &s, 10);
        if ((val < 0) || (val > 32)) {
            syntax_error("IP prefix range \"%s\" contains an invalid range",
                         yytext);
        }
        p = s + 1;
        if (isdigit((int)*p)) {
            endval = strtol(p, NULL, 10);
            if ((endval < 0) || (endval > 32)) {
                syntax_error("IP prefix \"%s\" contains an invalid prefix range", 
                             yytext);
            }
            if (endval < val) {
                syntax_error("IP prefix \"%s\" range end is less than range start",
                             yytext);
            }
        }
    }
    return TKN_PRFXV4RNG;
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 209 "mp_default.l"
{
    /* check each quad of 1A:3:7:8:AAAA:BBBB:DEAD:BEEF/55 in prefix is valid, as
       well as any bit ranges specified */
    long int val;
    long int endval;
    char *s, *p;
    p = s = yytext;
    while (*s != '/') {
        val = strtol(p, &s, 16);
        if ((val < 0) || (val > 65535)) {
             syntax_error("IPv6 prefix \"%s\" contains an invalid quad",
                          yytext);
        }
        p = s + 1;
    }
    val = strtol(p, &s, 10);
    if ((val < 0) || (val > 128)) {
        syntax_error("IPv6 prefix range \"%s\" contains an invalid prefix length",
                     yytext);
    }
    p = s + 1;
    if (isdigit((int)*p)) {
        val = strtol(p, &s, 10);
        if ((val < 0) || (val > 128)) {
            syntax_error("IPv6 prefix range \"%s\" contains an invalid range",
                         yytext);
        }
        p = s + 1;
        if (isdigit((int)*p)) {
            endval = strtol(p, NULL, 10);
            if ((endval < 0) || (endval > 128)) {
                syntax_error("IPv6 prefix \"%s\" contains an invalid prefix range",
                             yytext);
            }
            if (endval < val) {
                syntax_error("IPv6 prefix \"%s\" range end is less than range start",
                             yytext);
            }
        }
    }
    return TKN_PRFXV6RNG;
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 252 "mp_default.l"
{
    /* check each quad of 1A:3:7:8:AAAA:BBBB:DEAD:BEEF/55 in prefix is valid, as
       well as any bit ranges specified */
    long int val;
    long int endval;
    char *s, *p, *r;
    int leftquads = 0;
    int rightquads = 0;

    p = s = yytext;
    while (*s != '/') {
        val = strtol(p, &s, 16);
        if ((val < 0) || (val > 65535)) {
             syntax_error("IPv6 prefix \"%s\" contains an invalid quad",
                          yytext);
        }
        p = s + 1;
    }
    val = strtol(p, &s, 10);
    if ((val < 0) || (val > 128)) {
        syntax_error("IPv6 prefix range \"%s\" contains an invalid prefix length",
                     yytext);
    }
    p = s + 1;
    if (isdigit((int)*p)) {
        val = strtol(p, &s, 10);
        if ((val < 0) || (val > 128)) {
            syntax_error("IPv6 prefix range \"%s\" contains an invalid range",
                         yytext);
        }
        p = s + 1;
        if (isdigit((int)*p)) {
            endval = strtol(p, NULL, 10);
            if ((endval < 0) || (endval > 128)) {
                syntax_error("IPv6 prefix \"%s\" contains an invalid prefix range",
                             yytext);
            }
            if (endval < val) {
                syntax_error("IPv6 prefix \"%s\" range end is less than range start",
                             yytext);
            }
        }
    }

    /* And now, count colons to the left of "::" - this is
       one less than the number of left quads */

    r = strchr(yytext, ':');
    leftquads++;
    while (r[1] != ':') {
        leftquads++;
        r = strchr(r+1, ':');
    }
    /* skip "::" */
    r += 2;
    /* count colons to the right of "::" - one less than the number of right quads */
    if (r[0] != '\0') {
        do {
            rightquads++;
            r = strchr(r+1, ':');
        } while (r != NULL);
    }
    /* check for too many quads */
    if ((leftquads + rightquads) > 8) {
        syntax_error("IPv6 address \"%s\" contains too many digits", yytext);
    }

    return TKN_PRFXV6DCRNG;
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 322 "mp_default.l"
{
    /* check each number of 1.2.3.4/5 in prefix is valid */
    long int val;
    char *s, *p;
    p = s = yytext;
    while (*s != '/') {
        val = strtol(p, &s, 10);
        if ((val < 0) || (val > 255)) {
             syntax_error("IP prefix \"%s\" contains an invalid octet", 
                          yytext);
        }
        p = s + 1;
    }
    val = strtol(p, NULL, 10);
    if ((val < 0) || (val > 32)) {
        syntax_error("IP prefix \"%s\" contains an invalid prefix length", 
                     yytext);
    }
    return TKN_PRFXV4;
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 343 "mp_default.l"
{
    /* check each quad of 1A:3:7:8:AAAA:BBBB:DEAD:BEEF/55 in prefix is valid */
    long int val;
    char *s, *p;
    p = s = yytext;
    while (*s != '/') {
        val = strtol(p, &s, 16);
        if ((val < 0) || (val > 65535)) {
             syntax_error("IPv6 prefix \"%s\" contains an invalid quad",
                          yytext);
        }
        p = s + 1;
    }
    val = strtol(p, NULL, 10);
    if ((val < 0) || (val > 128)) {
        syntax_error("IPv6 prefix \"%s\" contains an invalid prefix length",
                     yytext);
    }
    return TKN_PRFXV6;
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 364 "mp_default.l"
{
    /* check each quad of 1A::AAAA:BBBB:DEAD:BEEF/55 in prefix is valid */
    long int val;
    char *s, *p, *r;
    int leftquads = 0;
    int rightquads = 0;

    r = p = s = yytext;
    while (*s != '/') {
        val = strtol(p, &s, 16);
        if ((val < 0) || (val > 65535)) {
             syntax_error("IPv6 prefix \"%s\" contains an invalid quad",
                          yytext);
        }
        p = s + 1;
    }
    val = strtol(p, NULL, 10);
    if ((val < 0) || (val > 128)) {
        syntax_error("IPv6 prefix \"%s\" contains an invalid prefix length",
                     yytext);
    }

    /* And now, count colons to the left of "::" - this is
       one less then the number of left quads */

    r = strchr(yytext, ':');
    leftquads++;
    while (r[1] != ':') {
        leftquads++;
        r = strchr(r+1, ':');
    }
    /* skip "::" */
    r += 2;
    /* count colons to the right of "::" - one less then the number of right quads */
    if (r[0] != '\0') {
        do {
            rightquads++;
            r = strchr(r+1, ':');
        } while (r != NULL);
    }
    /* check for too many quads */
    if ((leftquads + rightquads) > 8) {
        syntax_error("IPv6 address \"%s\" contains too many digits", yytext);
    }

    return TKN_PRFXV6DC;
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 412 "mp_default.l"
{
    /* check each number of 1.2.3.4 is valid */
    long int val;
    char *s, *p;
    p = s = yytext;
    while (*s != '\0') {
        val = strtol(p, &s, 10);
        if ((val < 0) || (val > 255)) {
             syntax_error("IP address \"%s\" contains an invalid octet", 
                          yytext);
        }
        p = s + 1;
    }
    return TKN_IPV4;
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 428 "mp_default.l"
{
    /* check each quad of 1A:3:7:8:AAAA:BBBB:DEAD:BEEF in address is valid */
    long int val;
    char *s, *p;
    p = s = yytext;
    while (*s != '\0') {
        val = strtol(p, &s, 16);
        if ((val < 0) || (val > 65535)) {
             syntax_error("IPv6 address \"%s\" contains an invalid quad",
                          yytext);
        }
        p = s + 1;
    }
    return TKN_IPV6;
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 444 "mp_default.l"
{
    /* check each quad of 1A::AAAA:BBBB:DEAD:BEEF in address is valid */
    long int val;
    char *s, *p, *r;
    int leftquads = 0;
    int rightquads = 0;

    r = p = s = yytext;
    while (*s != '\0') {
        val = strtol(p, &s, 16);
        if ((val < 0) || (val > 65535)) {
             syntax_error("IPv6 address \"%s\" contains an invalid quad",
                          yytext);
        }
        p = s + 1;
    }
    /* And now, count colons to the left of "::" - this is
       one less then the number of left quads */

    r = strchr(yytext, ':');
    leftquads++;
    while (r[1] != ':') {
        leftquads++;
        r = strchr(r+1, ':');
    }
    /* skip "::" */
    r += 2;
    /* count colons to the right of "::" - one less then the number of right quads */
    if (r[0] != '\0') {
        do {
            rightquads++;
            r = strchr(r+1, ':');
        } while (r != NULL);
    }
    /* check for too many quads */
    if ((leftquads + rightquads) > 8) {
        syntax_error("IPv6 address \"%s\" contains too many digits", yytext);
    }

    return TKN_IPV6DC;
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 486 "mp_default.l"
{
    /* verify each part is a 16-bit number */
    long int val;
    char *s, *p;
    p = s = yytext;
    while (*s != '\0') {
        val = strtol(p, &s, 10);
        if ((val < 0) || (val > 65535)) {
             syntax_error("Community number \"%s\" contains an invalid number", 
                           yytext);
        }
        p = s + 1;
    }
    return TKN_COMM_NO;
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 502 "mp_default.l"
{ 
    mp_defaultlval.sval = yytext;
    return TKN_INT; 
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 507 "mp_default.l"
{ 
    /* check the length */
    if (strlen(yytext) > 63) {
       syntax_error("Portion of domain name \"%s\" is longer "
                                                           "than 63 characters",                    yytext);
    }
    mp_defaultlval.sval = yytext;
    return TKN_DNS;
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 517 "mp_default.l"
{ return yytext[0]; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 519 "mp_default.l"
ECHO;
	YY_BREAK
#line 1743 "mp_default.lex.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 418 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 418 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 417);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 519 "mp_default.l"


void 
mp_default_reset ()
{
    yy_flush_buffer(YY_CURRENT_BUFFER);
}

