#define yy_create_buffer mp_export_create_buffer
#define yy_delete_buffer mp_export_delete_buffer
#define yy_scan_buffer mp_export_scan_buffer
#define yy_scan_string mp_export_scan_string
#define yy_scan_bytes mp_export_scan_bytes
#define yy_flex_debug mp_export_flex_debug
#define yy_init_buffer mp_export_init_buffer
#define yy_flush_buffer mp_export_flush_buffer
#define yy_load_buffer_state mp_export_load_buffer_state
#define yy_switch_to_buffer mp_export_switch_to_buffer
#define yyin mp_exportin
#define yyleng mp_exportleng
#define yylex mp_exportlex
#define yyout mp_exportout
#define yyrestart mp_exportrestart
#define yytext mp_exporttext
#define yywrap mp_exportwrap

#line 20 "mp_export.lex.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 66
#define YY_END_OF_BUFFER 67
static yyconst short int yy_accept[483] =
    {   0,
        0,    0,   67,   65,    1,    1,   65,   63,   65,    6,
       64,   65,   64,   64,   64,   64,   64,   64,   64,   64,
       64,   64,   64,   64,   64,   64,   65,   65,    1,    7,
        0,    0,   63,    0,   64,   64,   61,    5,    9,    8,
       10,    0,   64,   64,   64,   64,   64,   26,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   64,   64,   64,
       64,   64,   64,   64,   64,    2,   64,   64,   64,   64,
       64,   64,   64,   64,   64,   14,    0,   43,   44,    0,
        0,   63,   64,   62,    0,    0,   61,    0,   64,   32,
        3,   64,   12,   64,    0,   48,   64,   64,   31,   64,

       64,   64,   64,   38,   64,   64,   64,   64,   64,   64,
       64,    0,   37,   64,   64,   64,    0,    4,   64,   64,
       64,   64,   64,   64,   64,   31,    0,   64,   64,    0,
        0,   63,   64,   62,    0,    0,   58,   61,    0,   11,
       64,   64,    0,   64,    0,   50,    0,    0,   64,   64,
       64,   42,   64,   64,   64,   64,    0,   64,   28,   33,
       34,   64,   64,   64,   64,    0,    0,   64,    0,   36,
       64,   64,   64,   64,   64,    0,   51,    0,   17,   64,
        0,    0,   63,   62,    0,    0,    0,   61,   61,   64,
       64,    0,    0,   64,    0,   50,    0,    0,    0,    0,

       64,   64,   64,   64,   64,    0,    0,   64,    0,    0,
        0,    0,    0,   64,   64,   64,   64,    0,   64,   64,
        0,   51,   64,    0,   45,    0,    0,   62,    0,    0,
        0,   55,   55,   61,   61,    0,   15,   64,    0,    0,
       18,    0,    0,    0,    0,    0,    0,    0,   39,   64,
       64,   19,   30,    0,   49,    0,    0,   64,    0,    0,
        0,    0,    0,    0,    0,   13,   64,    0,   52,    0,
       64,   29,    0,    0,    0,    0,   47,   59,   62,    0,
        0,    0,   61,   61,   64,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   64,   64,    0,   49,    0,

       64,    0,    0,    0,    0,    0,    0,    0,   21,    0,
       52,   64,    0,    0,    0,    0,    0,    0,    0,    0,
       55,   61,   61,    0,   22,    0,    0,    0,   50,    0,
        0,    0,    0,   64,   20,    0,    0,    0,   16,   23,
        0,    0,    0,    0,   41,    0,    0,    0,    0,   27,
       51,    0,    0,    0,   56,    0,    0,   61,   61,    0,
        0,    0,   50,    0,    0,    0,    0,   40,    0,    0,
        0,    0,    0,    0,    0,    0,   24,    0,    0,    0,
        0,    0,   51,   46,    0,    0,    0,    0,   61,   61,
        0,    0,    0,    0,    0,   49,    0,    0,    0,    0,

        0,    0,    0,   52,    0,    0,    0,   53,   53,    0,
        0,   61,   61,    0,   35,   50,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   51,    0,    0,    0,    0,
       61,   61,    0,    0,    0,    0,    0,   33,    0,   34,
       25,    0,    0,   53,    0,    0,   61,   61,    0,   49,
       49,    0,    0,   52,    0,   52,    0,    0,    0,   61,
       61,    0,    0,   60,   61,   61,    0,    0,   60,   61,
       61,   57,   60,   61,    0,   60,   61,   54,   54,    0,
       54,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,   10,   10,   10,
       10,   11,   10,   12,   10,   10,   10,   13,    1,    1,
       14,    1,    1,    1,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   27,   28,   29,   30,   31,   32,
       27,   33,   34,   35,   36,   37,   27,   38,   39,   27,
        1,    1,    1,   16,   17,    1,   18,   19,   20,   21,

       22,   23,   24,   25,   26,   27,   27,   28,   29,   30,
       31,   32,   27,   33,   34,   35,   36,   37,   27,   38,
       39,   27,   40,    1,   41,   42,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[43] =
    {   0,
        1,    1,    1,    1,    1,    1,    2,    1,    3,    4,
        4,    4,    5,    1,    6,    1,    2,    4,    4,    4,
        4,    4,    4,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    1,
        1,    1
    } ;

static yyconst short int yy_base[551] =
    {   0,
        0,    0,  976,  977,   41,   43,  961,   40,  961,  959,
       72,   91,   96,  110,   81,  103,   73,   86,  109,  114,
       93,   23,  116,  122,   64,  941,  945,  146,   85,  977,
        0,  142,  177,  147,    0,  153,  961,  977,  977,  977,
      160,  956,  166,  147,  154,  936,  195,    0,  935,  931,
      151,  127,  947,  935,  943,  927,  136,  926,  923,  952,
      937,  923,  937,  917,  112,    0,  922,  931,  923,  161,
      928,  918,  942,  920,  929,    0,  916,  977,  977,  919,
      200,  218,  205,  209,  931,  213,  104,  221,  917,    0,
        0,  911,  933,  918,  227,  235,  921,  927,    0,  908,

      901,  900,  912,    0,  900,  910,  898,  913,  897,  172,
      238,  902,    0,  895,  902,  890,  233,    0,  901,  890,
      915,  203,  897,  885,  893,  888,  245,  894,  881,  880,
      246,  253,  901,  257,  900,  899,  261,  265,    0,  269,
      880,  874,  246,  879,  269,  276,  197,  267,  873,  871,
      888,    0,  870,  872,  871,  895,  881,  867,    0,  891,
      890,  863,  873,  863,  877,  872,  854,  873,  267,    0,
      868,  882,  857,  857,  862,  280,  289,  236,    0,  859,
       48,  297,  302,  306,  871,  870,  315,  285,  315,  852,
      851,  844,  849,  857,  303,  316,  843,  848,  270,  841,

      849,  843,  846,  849,  835,  323,  838,  838,  303,  305,
      842,  829,  833,  830,  834,  833,  831,  329,  840,  837,
      319,  336,  838,  316,  977,  344,  348,  351,  844,  843,
      842,  977,  358,  358,  363,    0,    0,  834,  825,  826,
        0,  817,  828,  367,  814,  826,  817,  839,    0,  819,
      814,    0,    0,  366,  373,  368,  809,  820,  805,  810,
      803,  808,  806,  814,  804,  821,  812,  377,  380,  382,
      801,    0,  797,  808,  795,  798,  977,  391,  394,  814,
      813,  397,  401,  402,  803,  789,  803,  406,  800,  405,
      413,  788,  787,  795,  412,  783,  783,  409,  421,  781,

      780,  786,  787,  784,  785,  778,  776,  775,    0,  313,
      423,  779,  432,  784,  798,  769,  435,  790,  789,  788,
      438,  422,  424,    0,    0,  774,  781,  444,  442,  765,
      790,  778,  788,  755,    0,  759,  764,  769,  977,    0,
      755,  769,  753,  767,  977,  751,  750,  750,  434,    0,
      447,  750,  455,  741,  453,  768,  767,  457,  462,  759,
      744,  461,  466,  759,  467,  742,  469,    0,  470,  740,
      752,  747,  754,  745,  752,  743,  977,  477,  746,  737,
      748,  478,  483,  977,  487,  752,  751,  750,  492,  493,
        0,  744,  726,  726,  746,  497,  725,  724,  736,  721,

      734,  719,  718,  501,  683,  689,  642,  977,  508,  660,
      640,  508,  513,  616,  977,  627,  631,  617,  615,  585,
      599,  572,  583,  584,  593,  567,  513,  566,  561,  560,
      518,  519,    0,  534,  486,  524,  523,  977,  512,  977,
      977,  511,  522,  523,  517,  503,  527,  528,  531,  536,
      491,  456,  442,  426,  535,  537,  408,  407,  385,  538,
      546,    0,  383,  382,  547,  373,  353,  551,  341,  555,
      339,  555,  338,  302,  565,  250,  245,  977,  571,  574,
      577,  977,  586,  589,  590,  593,  597,  602,  605,  607,
      610,  205,  614,  617,  618,  620,  623,  626,  630,  635,

      638,  640,  643,  186,  647,  650,  651,  653,  656,  659,
      661,  663,  666,  133,  670,  673,  674,  676,  679,  682,
      684,  686,  689,  128,  691,  693,  696,  699,  701,  703,
      706,   77,  710,  713,  714,  716,  719,  722,  724,  726,
      729,   45,  731,  734,  736,  739,  741,  743,  745,  747
    } ;

static yyconst short int yy_def[551] =
    {   0,
      482,    1,  482,  482,  482,  482,  482,  482,  482,  482,
        8,  482,    8,    8,   14,   14,   14,   14,   11,   11,
       11,   11,   11,   11,   11,   11,  482,  482,  482,  482,
       11,  482,    8,  483,   11,   33,  484,  482,  482,  482,
      482,  483,   33,   43,   11,   11,   11,   11,   11,   43,
       11,   43,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,  482,  482,  482,  482,
      482,   33,   82,  485,  485,  482,  486,  482,   11,   11,
       11,   11,   11,   11,  487,   11,   11,   11,   11,   11,

       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,  482,   11,   11,   11,
       11,   11,   11,   11,   11,   11,  488,   11,   11,  482,
      482,   11,   11,  489,  490,  489,  482,  491,  492,  482,
       11,   11,  482,   11,  487,  487,  493,  482,   11,   11,
       11,   11,   11,   11,   11,   11,  482,   11,   11,   11,
       11,   11,   11,   11,   11,  482,  482,   11,   11,   11,
       11,   11,   11,   11,   11,  488,  488,  494,   11,   11,
      482,  482,   11,  495,  495,  496,  482,  497,  498,   11,
       11,  482,  482,   11,  482,  493,  482,  482,  482,  482,

       11,   11,   11,   11,   11,  499,  482,   11,  482,  482,
      482,  482,  482,   11,   11,   11,   11,  500,   11,   11,
      482,  494,   11,  482,  482,  482,  482,  482,  482,  501,
      502,  482,  482,  482,  503,  504,   11,   11,  482,  482,
       11,  482,  482,  482,  482,  482,  482,  482,   11,   11,
       11,   11,   11,  499,  499,  505,  482,   11,  482,  482,
      482,  482,  482,  482,  482,   11,   11,  500,  500,  506,
       11,   11,  482,  482,  482,  482,  482,  482,  482,  507,
      508,  482,  509,  510,   11,  482,  482,  482,  482,  493,
      482,  482,  482,  482,  494,   11,   11,  482,  505,  482,

       11,  482,  482,  482,  482,  482,  482,  482,   11,  482,
      506,   11,  482,  482,  482,  482,  482,  482,  511,  512,
      482,  482,  513,  514,   11,  482,  482,  515,  482,  482,
      482,  482,  482,   11,   11,  482,  482,  482,  482,   11,
      482,  482,  482,  482,  482,  482,  482,  482,  482,   11,
      482,  482,  516,  482,  482,  517,  518,  519,  520,  482,
      482,  515,  515,  482,  505,  482,  506,   11,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  516,  516,  482,  482,  482,  521,  522,  482,  523,
      524,  482,  482,  482,  482,  482,  482,  482,  482,  482,

      482,  482,  482,  482,  482,  482,  482,  482,  482,  525,
      526,  527,  528,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  529,  530,
      482,  531,  532,  482,  533,  482,  482,  482,  482,  482,
      482,  482,  534,  482,  535,  536,  537,  538,  533,  533,
      482,  482,  482,  482,  534,  534,  482,  539,  540,  482,
      541,  542,  543,  544,  545,  546,  482,  482,  547,  482,
      548,  482,  549,  550,  482,  482,  482,  482,  482,  482,
      482,    0,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,

      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482
    } ;

static yyconst short int yy_nxt[1020] =
    {   0,
        4,    5,    6,    4,    4,    4,    4,    7,    4,    8,
        8,    8,    9,   10,   11,   12,    4,   13,   14,   15,
       16,   17,   18,   11,   11,   19,   11,   11,   20,   21,
       22,   23,   24,   25,   26,   11,   11,   11,   11,   27,
        4,   28,   29,   29,   29,   29,   31,   32,  466,   33,
       33,   33,   34,  224,   35,   66,   67,   36,   36,   36,
       36,   36,   36,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,  482,
      448,   35,   35,   35,  482,   74,   29,   29,  225,   35,
       35,   35,   35,   35,   35,   39,   35,   40,   75,   50,

       41,   41,   41,  482,   35,   36,   36,   36,   42,   35,
       55,   51,   86,   56,   64,   43,  139,  482,   44,   36,
       36,   36,   42,   65,   52,   45,   35,   46,  117,   47,
       48,  413,   57,   49,   53,   61,  359,   68,   58,   54,
       59,   69,   60,   71,   62,   63,  118,   72,   70,   78,
       79,   81,   81,   81,  103,   73,   84,   84,   84,   37,
      482,   35,   83,   83,   83,   42,   88,  108,  109,   41,
       41,   41,   90,  482,   91,   83,   83,   83,   42,  100,
      101,   35,  122,   92,  102,   80,   82,   82,   82,  284,
      123,  124,   93,  158,   83,   83,   83,   83,   83,   83,

       89,   95,  159,  147,   96,   96,   96,  131,  189,   81,
       81,   81,  482,  147,  133,  133,  133,   42,  134,  134,
      134,  135,  137,  137,  137,  170,   97,  132,  132,  132,
      140,  140,  140,  145,  171,  133,  133,  133,  133,  133,
      133,   35,  178,  147,   96,   96,   96,  148,  160,  161,
      166,  176,  178,   86,  167,  182,  182,  182,  468,   35,
       32,  178,  183,  183,  183,   34,  184,  184,  184,  135,
      137,  137,  137,   86,  192,  145,  187,  139,  140,  140,
      140,  193,  145,   35,  197,  147,  176,  215,  195,  198,
       35,  246,  147,   86,   35,  176,  178,  139,  199,  200,

      216,  221,  247,   35,  226,  178,  182,  182,  182,   32,
       86,  183,  183,  183,  227,  228,  228,  228,  135,  232,
      242,  232,  147,   86,  233,  233,  233,  236,  195,  254,
      348,  259,  147,  261,  243,  268,  273,   35,  260,  256,
      262,  276,  178,   35,  349,  270,  468,   86,  221,  468,
      274,  275,  178,  278,  278,  278,  277,  279,  279,  279,
      279,  279,  279,  135,  282,  459,   86,  233,  233,  233,
      139,   86,  254,  290,  256,  236,  291,  291,  291,  254,
       35,   86,  256,  268,  256,  298,  268,   35,  270,  256,
      468,   35,  310,  270,   35,  459,  270,   37,  270,  317,

      278,  278,  278,  279,  279,  279,  321,  321,  321,   86,
       86,  147,  328,  236,  324,  329,  329,  329,  178,  459,
      430,  147,  291,  291,  291,  148,  336,  256,  178,  270,
       86,  337,   86,  298,  236,  310,  324,  256,  310,  270,
      338,  351,  351,  351,  355,  355,  355,  321,  321,  321,
      362,  329,  329,  329,  195,  379,  351,  351,  351,  221,
      362,  382,  355,  355,  355,   86,  380,  362,  385,  324,
       86,  382,  362,  256,  391,  270,  440,  362,  195,  396,
      396,  396,  362,  256,  382,  270,  404,  404,  404,  382,
      438,  408,  449,  408,  382,  221,  409,  409,  409,  382,

       86,   86,  449,  298,  324,  391,  396,  396,  396,  298,
      404,  404,  404,  310,  427,  459,   86,  409,  409,  409,
      391,   86,  444,  444,  444,  433,   86,   86,  455,  430,
      391,  433,  444,  444,  444,   86,   86,  449,  455,  433,
      462,  455,  449,  455,  454,  453,   86,  449,  298,  310,
      433,  455,  449,  455,   86,   86,  452,  451,  462,  462,
      472,  472,  472,   86,  472,  472,  472,  462,  415,  478,
      475,  478,   37,  430,  479,  479,  479,  480,  388,  221,
      479,  479,  479,  481,  481,  481,  481,  481,  481,   85,
       85,   87,   87,  136,  136,  138,  138,  138,  146,  443,

      146,  442,  146,  177,  441,  177,  440,  177,  185,  185,
      186,  186,  188,  188,  188,  196,  439,  196,  222,  438,
      222,  229,  229,  230,  230,  234,  234,  234,  235,  235,
      235,  255,  437,  255,  436,  255,  269,  435,  269,  195,
      269,  280,  280,  281,  281,  283,  283,  283,  299,  434,
      299,  311,  430,  311,  318,  318,  319,  319,  322,  322,
      322,  323,  323,  323,  356,  356,  357,  357,  358,  358,
      358,  363,  388,  363,  383,  426,  383,  386,  386,  387,
      387,  389,  389,  389,  390,  390,  390,  410,  410,  411,
      411,  412,  412,  412,  428,  428,  429,  429,  431,  431,

      431,  432,  432,  432,  445,  445,  446,  446,  447,  447,
      447,  450,  425,  450,  456,  424,  456,  457,  457,  458,
      458,  460,  460,  460,  461,  461,  461,  463,  463,  464,
      464,  465,  465,  465,  467,  467,  469,  469,  470,  470,
      470,  471,  471,  473,  473,  474,  474,  476,  476,  477,
      477,  423,  422,  421,  420,  419,  418,  417,  148,  416,
      415,  414,   37,  388,  320,  407,  406,  405,  403,  402,
      401,  400,  399,  398,  397,  395,  394,  393,  392,  388,
      320,  384,  381,  378,  377,  376,  375,  374,  373,  372,
      371,  370,  369,  368,  367,  366,  365,  364,  361,  360,

       37,  320,  231,  354,  353,  352,  350,  347,  346,  345,
      344,  343,  342,  341,  340,  339,  335,  334,  333,  332,
      331,  330,  327,  326,  325,  320,  231,  316,  315,  314,
      313,  312,  309,  148,  308,  307,  306,  305,  304,  303,
      302,  301,  300,  297,  296,  295,  294,  293,  292,  289,
      288,  287,  286,  285,   37,  231,  135,   99,  272,  271,
      267,   99,   99,  266,  265,  264,  263,  258,  257,  253,
      252,  251,  250,  249,  248,  245,  244,  241,  240,  239,
      238,  237,  231,  135,  223,   99,  220,  219,  218,  217,
      214,  213,  212,  211,   99,   99,   99,  210,  209,  208,

      207,  206,  205,   99,  204,  203,  202,  201,  194,  191,
      190,  135,   37,   42,  181,  180,  179,  175,  174,  173,
      172,  169,  168,   99,  165,  164,  163,  162,   99,  157,
      156,  155,  154,  153,  152,  151,  150,   99,  149,  144,
      143,  142,  141,  135,   77,  130,  129,  128,  127,  126,
      125,  121,  120,  119,  116,  115,  114,  113,  112,  111,
      110,  107,  106,  105,  104,   99,   98,   94,   37,   86,
       77,   76,   38,   37,   30,  482,    3,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,

      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482
    } ;

static yyconst short int yy_chk[1020] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    5,    5,    6,    6,    8,    8,  542,    8,
        8,    8,    8,  181,    8,   22,   22,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,   11,
      532,   11,   11,   11,   11,   25,   29,   29,  181,   11,
       11,   11,   11,   11,   11,   12,   17,   12,   25,   15,

       12,   12,   12,   13,   15,   13,   13,   13,   13,   18,
       17,   15,   87,   18,   21,   13,   87,   14,   13,   14,
       14,   14,   14,   21,   16,   13,   16,   13,   65,   13,
       13,  524,   19,   14,   16,   20,  514,   23,   19,   16,
       19,   23,   19,   24,   20,   20,   65,   24,   23,   28,
       28,   32,   32,   32,   52,   24,   34,   34,   34,   34,
       36,   52,   36,   36,   36,   36,   41,   57,   57,   41,
       41,   41,   44,   43,   45,   43,   43,   43,   43,   51,
       51,   44,   70,   45,   51,   28,   33,   33,   33,  504,
       70,   70,   45,  110,   33,   33,   33,   33,   33,   33,

       43,   47,  110,  147,   47,   47,   47,   81,  492,   81,
       81,   81,   83,  147,   83,   83,   83,   83,   84,   84,
       84,   84,   86,   86,   86,  122,   47,   82,   82,   82,
       88,   88,   88,   95,  122,   82,   82,   82,   82,   82,
       82,   95,  178,   95,   96,   96,   96,   96,  111,  111,
      117,  127,  178,  477,  117,  131,  131,  131,  476,  127,
      132,  127,  132,  132,  132,  132,  134,  134,  134,  134,
      137,  137,  137,  138,  143,  145,  137,  138,  140,  140,
      140,  143,  146,  145,  148,  145,  176,  169,  146,  148,
      146,  199,  146,  188,  176,  177,  176,  188,  148,  148,

      169,  177,  199,  177,  182,  177,  182,  182,  182,  183,
      474,  183,  183,  183,  183,  184,  184,  184,  184,  187,
      195,  187,  196,  189,  187,  187,  187,  189,  196,  206,
      310,  209,  196,  210,  195,  218,  221,  206,  209,  206,
      210,  224,  222,  218,  310,  218,  473,  471,  222,  469,
      221,  221,  222,  226,  226,  226,  224,  227,  227,  227,
      228,  228,  228,  228,  233,  467,  234,  233,  233,  233,
      234,  235,  254,  244,  256,  235,  244,  244,  244,  255,
      254,  466,  254,  268,  256,  255,  269,  255,  270,  255,
      464,  268,  269,  268,  269,  463,  269,  459,  270,  278,

      278,  278,  278,  279,  279,  279,  282,  282,  282,  283,
      284,  290,  288,  283,  284,  288,  288,  288,  295,  458,
      457,  290,  291,  291,  291,  291,  298,  299,  295,  311,
      322,  298,  323,  299,  322,  311,  323,  299,  454,  311,
      298,  313,  313,  313,  317,  317,  317,  321,  321,  321,
      328,  329,  329,  329,  329,  349,  351,  351,  351,  351,
      328,  353,  355,  355,  355,  358,  349,  362,  355,  358,
      359,  353,  363,  365,  359,  367,  453,  362,  363,  369,
      369,  369,  363,  365,  382,  367,  378,  378,  378,  383,
      452,  385,  435,  385,  382,  383,  385,  385,  385,  383,

      389,  390,  435,  451,  389,  390,  396,  396,  396,  396,
      404,  404,  404,  404,  409,  446,  412,  409,  409,  409,
      412,  413,  427,  427,  427,  413,  431,  432,  443,  445,
      431,  432,  444,  444,  444,  447,  448,  449,  443,  447,
      448,  455,  450,  456,  442,  439,  460,  449,  450,  456,
      460,  455,  450,  456,  461,  465,  437,  436,  461,  465,
      468,  468,  468,  470,  472,  472,  472,  470,  434,  475,
      472,  475,  430,  429,  475,  475,  475,  479,  428,  426,
      479,  479,  479,  480,  480,  480,  481,  481,  481,  483,
      483,  484,  484,  485,  485,  486,  486,  486,  487,  425,

      487,  424,  487,  488,  423,  488,  422,  488,  489,  489,
      490,  490,  491,  491,  491,  493,  421,  493,  494,  420,
      494,  495,  495,  496,  496,  497,  497,  497,  498,  498,
      498,  499,  419,  499,  418,  499,  500,  417,  500,  416,
      500,  501,  501,  502,  502,  503,  503,  503,  505,  414,
      505,  506,  411,  506,  507,  507,  508,  508,  509,  509,
      509,  510,  510,  510,  511,  511,  512,  512,  513,  513,
      513,  515,  410,  515,  516,  407,  516,  517,  517,  518,
      518,  519,  519,  519,  520,  520,  520,  521,  521,  522,
      522,  523,  523,  523,  525,  525,  526,  526,  527,  527,

      527,  528,  528,  528,  529,  529,  530,  530,  531,  531,
      531,  533,  406,  533,  534,  405,  534,  535,  535,  536,
      536,  537,  537,  537,  538,  538,  538,  539,  539,  540,
      540,  541,  541,  541,  543,  543,  544,  544,  545,  545,
      545,  546,  546,  547,  547,  548,  548,  549,  549,  550,
      550,  403,  402,  401,  400,  399,  398,  397,  395,  394,
      393,  392,  388,  387,  386,  381,  380,  379,  376,  375,
      374,  373,  372,  371,  370,  366,  364,  361,  360,  357,
      356,  354,  352,  348,  347,  346,  344,  343,  342,  341,
      338,  337,  336,  334,  333,  332,  331,  330,  327,  326,

      320,  319,  318,  316,  315,  314,  312,  308,  307,  306,
      305,  304,  303,  302,  301,  300,  297,  296,  294,  293,
      292,  289,  287,  286,  285,  281,  280,  276,  275,  274,
      273,  271,  267,  266,  265,  264,  263,  262,  261,  260,
      259,  258,  257,  251,  250,  248,  247,  246,  245,  243,
      242,  240,  239,  238,  231,  230,  229,  223,  220,  219,
      217,  216,  215,  214,  213,  212,  211,  208,  207,  205,
      204,  203,  202,  201,  200,  198,  197,  194,  193,  192,
      191,  190,  186,  185,  180,  175,  174,  173,  172,  171,
      168,  167,  166,  165,  164,  163,  162,  161,  160,  158,

      157,  156,  155,  154,  153,  151,  150,  149,  144,  142,
      141,  136,  135,  133,  130,  129,  128,  126,  125,  124,
      123,  121,  120,  119,  116,  115,  114,  112,  109,  108,
      107,  106,  105,  103,  102,  101,  100,   98,   97,   94,
       93,   92,   89,   85,   80,   77,   75,   74,   73,   72,
       71,   69,   68,   67,   64,   63,   62,   61,   60,   59,
       58,   56,   55,   54,   53,   50,   49,   46,   42,   37,
       27,   26,   10,    9,    7,    3,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,

      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "mp_export.l"
#define INITIAL 0
#line 2 "mp_export.l"
/*
  filename: mp_export.l

  description:
    Defines the tokenizer for an RPSLng mp-export attribute. Derived
    from export.l. 

  notes:
    Tokens are defined in the associated grammar, mp_export.y.

  $Id: mp_export.l,v 1.2 2004/12/10 16:37:39 can Exp $
*/
#line 42 "mp_export.l"
#include <string.h>
#include <stdlib.h>
#include <ctype.h>

/* tokens defined in the grammar */
#include "mp_export.tab.h"

#define mp_exportwrap yywrap
void syntax_error(char *fmt, ...);
void yy_input(char *buf, int *result, int max_size);
#undef YY_INPUT
#define YY_INPUT(buf,result,max_size) yy_input(buf,&result,max_size)
#define YY_NO_UNPUT  /* otherwise we get compiler warnings "`yyunput' defined but not used" */

#line 806 "mp_export.lex.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 58 "mp_export.l"


#line 960 "mp_export.lex.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 483 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 977 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 60 "mp_export.l"
{ ; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 62 "mp_export.l"
{ return OP_OR; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 63 "mp_export.l"
{ return OP_AND; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 64 "mp_export.l"
{ return OP_NOT; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 65 "mp_export.l"
{ return OP_COMPARE; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 66 "mp_export.l"
{ return OP_EQUAL; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 67 "mp_export.l"
{ return OP_APPEND; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 69 "mp_export.l"
{ return OP_MS; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 70 "mp_export.l"
{ return OP_MS; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 71 "mp_export.l"
{ 
    long int val;
    val = strtol(yytext+1, NULL, 10);
    if ((val < 0) || (val > 32)) {
        syntax_error("more specifics operator \"%s\" not 0 to 32 bits", 
                     yytext);
    }
    return OP_MS;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 80 "mp_export.l"
{
    long int val1, val2;
    char *p;
    val1 = strtol(yytext+1, &p, 10);
    if ((val1 < 0) || (val1 > 32)) {
        syntax_error("more specifics operator \"%s\" not 0 to 32 bits", 
                     yytext);
    }
    val2 = strtol(p+1, NULL, 10);
    if ((val2 < 0) || (val2 > 32)) {
        syntax_error("more specifics operator \"%s\" not 0 to 32 bits", 
                     yytext);
    }
    if (val2 < val1) {
        syntax_error("more specifics operator \"%s\" not 0 to 32 bits", 
                     yytext);
    }
    return OP_MS;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 101 "mp_export.l"
{ return KEYW_ANY; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 102 "mp_export.l"
{ return KEYW_PEERAS; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 104 "mp_export.l"
{ return KEYW_TO; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 105 "mp_export.l"
{ return KEYW_ACTION; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 106 "mp_export.l"
{ return KEYW_IGP_COST; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 107 "mp_export.l"
{ return KEYW_SELF; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 108 "mp_export.l"
{ return KEYW_APPEND; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 109 "mp_export.l"
{ return KEYW_DELETE; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 110 "mp_export.l"
{ return KEYW_CONTAINS; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 111 "mp_export.l"
{ return KEYW_PREPEND; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 112 "mp_export.l"
{ return KEYW_ANNOUNCE; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 114 "mp_export.l"
{ return KEYW_INTERNET; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 115 "mp_export.l"
{ return KEYW_NO_EXPORT; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 116 "mp_export.l"
{ return KEYW_NO_ADVERTISE; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 118 "mp_export.l"
{ return KEYW_AT; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 119 "mp_export.l"
{ return KEYW_PROTOCOL; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 120 "mp_export.l"
{ return KEYW_INTO; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 121 "mp_export.l"
{ return KEYW_REFINE; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 122 "mp_export.l"
{ return KEYW_EXCEPT; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 124 "mp_export.l"
{ return TKN_PROTOCOL; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 126 "mp_export.l"
{ return KEYW_AFI; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 128 "mp_export.l"
{ return KEYW_AFI_VALUE_V4; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 129 "mp_export.l"
{ return KEYW_AFI_VALUE_V6; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 130 "mp_export.l"
{ return KEYW_AFI_VALUE_ANY; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 132 "mp_export.l"
{ return TKN_PREF; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 133 "mp_export.l"
{ return TKN_MED; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 134 "mp_export.l"
{ return TKN_DPA; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 135 "mp_export.l"
{ return TKN_ASPATH; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 136 "mp_export.l"
{ return TKN_COMMUNITY; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 137 "mp_export.l"
{ return TKN_NEXT_HOP; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 138 "mp_export.l"
{ return TKN_COST; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 140 "mp_export.l"
{ return ASPATH_POSTFIX; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 141 "mp_export.l"
{ return ASPATH_POSTFIX; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 142 "mp_export.l"
{ return ASPATH_POSTFIX; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 143 "mp_export.l"
{ return ASPATH_POSTFIX; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 144 "mp_export.l"
{ return ASPATH_POSTFIX; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 146 "mp_export.l"
{
    long int val;
    char *s;
    val = strtol(yytext+2, &s, 10);
    if ((val < 0) || (val > 65535) || (*s != '\0')) {
        syntax_error("AS number \"%s\" is not between 0 and 65535", yytext);
    }
    return TKN_ASNO;
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 156 "mp_export.l"
{
    return TKN_FLTRNAME;
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 160 "mp_export.l"
{
    return TKN_ASNAME;
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 164 "mp_export.l"
{
    return TKN_RSNAME;
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 168 "mp_export.l"
{
    return TKN_PRNGNAME;
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 172 "mp_export.l"
{
    /* check each number of 1.2.3.4/5 in prefix is valid, as
       well as any bit ranges specified */
    long int val;
    long int endval;
    char *s, *p;
    p = s = yytext;
    while (*s != '/') {
        val = strtol(p, &s, 10);
        if ((val < 0) || (val > 255)) {
             syntax_error("IP prefix \"%s\" contains an invalid octet", 
                          yytext);
        }
        p = s + 1;
    }
    val = strtol(p, &s, 10);
    if ((val < 0) || (val > 32)) {
        syntax_error("IP prefix range \"%s\" contains an invalid prefix length",
                     yytext);
    }
    p = s + 1;
    if (isdigit((int)*p)) {
        val = strtol(p, &s, 10);
        if ((val < 0) || (val > 32)) {
            syntax_error("IP prefix range \"%s\" contains an invalid range",
                         yytext);
        }
        p = s + 1;
        if (isdigit((int)*p)) {
            endval = strtol(p, NULL, 10);
            if ((endval < 0) || (endval > 32)) {
                syntax_error("IP prefix \"%s\" contains an invalid prefix range", 
                             yytext);
            }
            if (endval < val) {
                syntax_error("IP prefix \"%s\" range end is less than range start",
                             yytext);
            }
        }
    }
    return TKN_PRFXV4RNG;
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 215 "mp_export.l"
{
    /* check each quad of 1A:3:7:8:AAAA:BBBB:DEAD:BEEF/55 in prefix is valid, as
       well as any bit ranges specified */
    long int val;
    long int endval;
    char *s, *p;
    p = s = yytext;
    while (*s != '/') {
        val = strtol(p, &s, 16);
        if ((val < 0) || (val > 65535)) {
             syntax_error("IPv6 prefix \"%s\" contains an invalid quad",
                          yytext);
        }
        p = s + 1;
    }
    val = strtol(p, &s, 10);
    if ((val < 0) || (val > 128)) {
        syntax_error("IPv6 prefix range \"%s\" contains an invalid prefix length",
                     yytext);
    }
    p = s + 1;
    if (isdigit((int)*p)) {
        val = strtol(p, &s, 10);
        if ((val < 0) || (val > 128)) {
            syntax_error("IPv6 prefix range \"%s\" contains an invalid range",
                         yytext);
        }
        p = s + 1;
        if (isdigit((int)*p)) {
            endval = strtol(p, NULL, 10);
            if ((endval < 0) || (endval > 128)) {
                syntax_error("IPv6 prefix \"%s\" contains an invalid prefix range",
                             yytext);
            }
            if (endval < val) {
                syntax_error("IPv6 prefix \"%s\" range end is less than range start",
                             yytext);
            }
        }
    }
    return TKN_PRFXV6RNG;
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 258 "mp_export.l"
{
    /* check each quad of 1A:3:7:8:AAAA:BBBB:DEAD:BEEF/55 in prefix is valid, as
       well as any bit ranges specified */
    long int val;
    long int endval;
    char *s, *p, *r;
    int leftquads = 0;
    int rightquads = 0;

    p = s = yytext;
    while (*s != '/') {
        val = strtol(p, &s, 16);
        if ((val < 0) || (val > 65535)) {
             syntax_error("IPv6 prefix \"%s\" contains an invalid quad",
                          yytext);
        }
        p = s + 1;
    }
    val = strtol(p, &s, 10);
    if ((val < 0) || (val > 128)) {
        syntax_error("IPv6 prefix range \"%s\" contains an invalid prefix length",
                     yytext);
    }
    p = s + 1;
    if (isdigit((int)*p)) {
        val = strtol(p, &s, 10);
        if ((val < 0) || (val > 128)) {
            syntax_error("IPv6 prefix range \"%s\" contains an invalid range",
                         yytext);
        }
        p = s + 1;
        if (isdigit((int)*p)) {
            endval = strtol(p, NULL, 10);
            if ((endval < 0) || (endval > 128)) {
                syntax_error("IPv6 prefix \"%s\" contains an invalid prefix range",
                             yytext);
            }
            if (endval < val) {
                syntax_error("IPv6 prefix \"%s\" range end is less than range start",
                             yytext);
            }
        }
    }

    /* And now, count colons to the left of "::" - this is
       one less than the number of left quads */

    r = strchr(yytext, ':');
    leftquads++;
    while (r[1] != ':') {
        leftquads++;
        r = strchr(r+1, ':');
    }
    /* skip "::" */
    r += 2;
    /* count colons to the right of "::" - one less than the number of right quads */
    if (r[0] != '\0') {
        do {
            rightquads++;
            r = strchr(r+1, ':');
        } while (r != NULL);
    }
    /* check for too many quads */
    if ((leftquads + rightquads) > 8) {
        syntax_error("IPv6 address \"%s\" contains too many digits", yytext);
    }

    return TKN_PRFXV6DCRNG;
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 328 "mp_export.l"
{
    /* check each number of 1.2.3.4/5 in prefix is valid */
    long int val;
    char *s, *p;
    p = s = yytext;
    while (*s != '/') {
        val = strtol(p, &s, 10);
        if ((val < 0) || (val > 255)) {
             syntax_error("IP prefix \"%s\" contains an invalid octet", 
                          yytext);
        }
        p = s + 1;
    }
    val = strtol(p, NULL, 10);
    if ((val < 0) || (val > 32)) {
        syntax_error("IP prefix \"%s\" contains an invalid prefix length", 
                     yytext);
    }
    return TKN_PRFXV4;
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 349 "mp_export.l"
{
    /* check each quad of 1A:3:7:8:AAAA:BBBB:DEAD:BEEF/55 in prefix is valid */
    long int val;
    char *s, *p;
    p = s = yytext;
    while (*s != '/') {
        val = strtol(p, &s, 16);
        if ((val < 0) || (val > 65535)) {
             syntax_error("IPv6 prefix \"%s\" contains an invalid quad",
                          yytext);
        }
        p = s + 1;
    }
    val = strtol(p, NULL, 10);
    if ((val < 0) || (val > 128)) {
        syntax_error("IPv6 prefix \"%s\" contains an invalid prefix length",
                     yytext);
    }
    return TKN_PRFXV6;
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 370 "mp_export.l"
{
    /* check each quad of 1A::AAAA:BBBB:DEAD:BEEF/55 in prefix is valid */
    long int val;
    char *s, *p, *r;
    int leftquads = 0;
    int rightquads = 0;

    r = p = s = yytext;
    while (*s != '/') {
        val = strtol(p, &s, 16);
        if ((val < 0) || (val > 65535)) {
             syntax_error("IPv6 prefix \"%s\" contains an invalid quad",
                          yytext);
        }
        p = s + 1;
    }
    val = strtol(p, NULL, 10);
    if ((val < 0) || (val > 128)) {
        syntax_error("IPv6 prefix \"%s\" contains an invalid prefix length",
                     yytext);
    }

    /* And now, count colons to the left of "::" - this is
       one less then the number of left quads */

    r = strchr(yytext, ':');
    leftquads++;
    while (r[1] != ':') {
        leftquads++;
        r = strchr(r+1, ':');
    }
    /* skip "::" */
    r += 2;
    /* count colons to the right of "::" - one less then the number of right quads */
    if (r[0] != '\0') {
        do {
            rightquads++;
            r = strchr(r+1, ':');
        } while (r != NULL);
    }
    /* check for too many quads */
    if ((leftquads + rightquads) > 8) {
        syntax_error("IPv6 address \"%s\" contains too many digits", yytext);
    }

    return TKN_PRFXV6DC;
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 418 "mp_export.l"
{
    /* check each number of 1.2.3.4 is valid */
    long int val;
    char *s, *p;
    p = s = yytext;
    while (*s != '\0') {
        val = strtol(p, &s, 10);
        if ((val < 0) || (val > 255)) {
             syntax_error("IP address \"%s\" contains an invalid octet", 
                          yytext);
        }
        p = s + 1;
    }
    return TKN_IPV4;
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 434 "mp_export.l"
{
    /* check each quad of 1A:3:7:8:AAAA:BBBB:DEAD:BEEF in address is valid */
    long int val;
    char *s, *p;
    p = s = yytext;
    while (*s != '\0') {
        val = strtol(p, &s, 16);
        if ((val < 0) || (val > 65535)) {
             syntax_error("IPv6 address \"%s\" contains an invalid quad",
                          yytext);
        }
        p = s + 1;
    }
    return TKN_IPV6;
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 450 "mp_export.l"
{
    /* check each quad of 1A::AAAA:BBBB:DEAD:BEEF in address is valid */
    long int val;
    char *s, *p, *r;
    int leftquads = 0;
    int rightquads = 0;

    r = p = s = yytext;
    while (*s != '\0') {
        val = strtol(p, &s, 16);
        if ((val < 0) || (val > 65535)) {
             syntax_error("IPv6 address \"%s\" contains an invalid quad",
                          yytext);
        }
        p = s + 1;
    }
    /* And now, count colons to the left of "::" - this is
       one less then the number of left quads */

    r = strchr(yytext, ':');
    leftquads++;
    while (r[1] != ':') {
        leftquads++;
        r = strchr(r+1, ':');
    }
    /* skip "::" */
    r += 2;
    /* count colons to the right of "::" - one less then the number of right quads */
    if (r[0] != '\0') {
        do {
            rightquads++;
            r = strchr(r+1, ':');
        } while (r != NULL);
    }
    /* check for too many quads */
    if ((leftquads + rightquads) > 8) {
        syntax_error("IPv6 address \"%s\" contains too many digits", yytext);
    }

    return TKN_IPV6DC;
}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 492 "mp_export.l"
{
    /* verify each part is a 16-bit number */
    long int val;
    char *s, *p;
    p = s = yytext;
    while (*s != '\0') {
        val = strtol(p, &s, 10);
        if ((val < 0) || (val > 65535)) {
             syntax_error("Community number \"%s\" contains an invalid number", 
                           yytext);
        }
        p = s + 1;
    }
    return TKN_COMM_NO;
}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 508 "mp_export.l"
{ 
    mp_exportlval.sval = yytext;
    return TKN_INT; 
}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 513 "mp_export.l"
{ 
    /* check the length */
    if (strlen(yytext) > 63) {
        syntax_error("Portion of domain name \"%s\" is longer "
                                                          "than 63 characters", 
                     yytext);
    }
    mp_exportlval.sval = yytext;
    return TKN_DNS; 
}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 524 "mp_export.l"
{ return yytext[0]; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 526 "mp_export.l"
ECHO;
	YY_BREAK
#line 1743 "mp_export.lex.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 483 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 483 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 482);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 526 "mp_export.l"


void 
mp_export_reset ()
{
    yy_flush_buffer(YY_CURRENT_BUFFER);
}

