#define yy_create_buffer mp_import_create_buffer
#define yy_delete_buffer mp_import_delete_buffer
#define yy_scan_buffer mp_import_scan_buffer
#define yy_scan_string mp_import_scan_string
#define yy_scan_bytes mp_import_scan_bytes
#define yy_flex_debug mp_import_flex_debug
#define yy_init_buffer mp_import_init_buffer
#define yy_flush_buffer mp_import_flush_buffer
#define yy_load_buffer_state mp_import_load_buffer_state
#define yy_switch_to_buffer mp_import_switch_to_buffer
#define yyin mp_importin
#define yyleng mp_importleng
#define yylex mp_importlex
#define yyout mp_importout
#define yyrestart mp_importrestart
#define yytext mp_importtext
#define yywrap mp_importwrap

#line 20 "mp_import.lex.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 66
#define YY_END_OF_BUFFER 67
static yyconst short int yy_accept[482] =
    {   0,
        0,    0,   67,   65,    1,    1,   65,   63,   65,    6,
       64,   65,   64,   64,   64,   64,   64,   64,   64,   64,
       64,   64,   64,   64,   64,   65,   65,    1,    7,    0,
        0,   63,    0,   64,   64,   61,    5,    9,    8,   10,
        0,   64,   64,   64,   64,   64,   26,   64,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   64,   64,   64,
       64,   64,   64,   64,   64,    2,   64,   64,   64,   64,
       64,   64,   64,   64,   64,    0,   43,   44,    0,    0,
       63,   64,   62,    0,    0,   61,    0,   64,   64,   32,
        3,   12,   64,    0,   48,   64,   64,   31,   64,   64,

       64,   64,   38,   64,   64,   64,   64,   64,   64,   64,
       64,    0,   37,   64,   64,   64,    0,    4,   64,   64,
       64,   64,   64,   64,   64,   31,    0,   64,   64,    0,
        0,   63,   64,   62,    0,    0,   58,   61,    0,   11,
       64,   64,    0,   64,    0,   50,    0,    0,   64,   64,
       64,   42,   64,   64,   64,   64,   14,    0,   64,   28,
       33,   34,   64,   64,   64,   64,    0,    0,   64,    0,
       36,   64,   64,   64,   64,   64,    0,   51,    0,   17,
       64,    0,    0,   63,   62,    0,    0,    0,   61,   61,
       64,   64,    0,    0,   64,    0,   50,    0,    0,    0,

        0,   64,   64,   64,   64,   64,    0,    0,   64,    0,
        0,    0,    0,    0,   64,   64,   64,   64,    0,   64,
       64,    0,   51,   64,    0,   45,    0,    0,   62,    0,
        0,    0,   55,   55,   61,   61,    0,   22,   15,    0,
        0,   19,    0,    0,    0,    0,    0,    0,    0,   39,
       64,   64,   20,   30,    0,   49,    0,    0,   64,    0,
        0,    0,    0,    0,    0,    0,   13,   64,    0,   52,
        0,   64,   29,    0,    0,    0,    0,   47,   59,   62,
        0,    0,    0,   61,   61,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   64,   64,    0,   49,    0,

       64,    0,    0,    0,    0,    0,    0,    0,   18,    0,
       52,   64,    0,    0,    0,    0,    0,    0,    0,    0,
       55,   61,   61,    0,    0,    0,    0,   50,    0,    0,
        0,    0,   64,   21,    0,    0,    0,   16,   23,    0,
        0,    0,    0,   41,    0,    0,    0,    0,   27,   51,
        0,    0,    0,   56,    0,    0,   61,   61,    0,    0,
        0,   50,    0,    0,    0,    0,   40,    0,    0,    0,
        0,    0,    0,    0,    0,   24,    0,    0,    0,    0,
        0,   51,   46,    0,    0,    0,    0,   61,   61,    0,
        0,    0,    0,    0,   49,    0,    0,    0,    0,    0,

        0,    0,   52,    0,    0,    0,   53,   53,    0,    0,
       61,   61,    0,   35,   50,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   51,    0,    0,    0,    0,   61,
       61,    0,    0,    0,    0,    0,   33,    0,   34,   25,
        0,    0,   53,    0,    0,   61,   61,    0,   49,   49,
        0,    0,   52,    0,   52,    0,    0,    0,   61,   61,
        0,    0,   60,   61,   61,    0,    0,   60,   61,   61,
       57,   60,   61,    0,   60,   61,   54,   54,    0,   54,
        0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,   10,   10,   10,
       10,   11,   10,   12,   10,   10,   10,   13,    1,    1,
       14,    1,    1,    1,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   27,   28,   29,   30,   31,   32,
       27,   33,   34,   35,   36,   37,   27,   38,   39,   27,
        1,    1,    1,   16,   17,    1,   18,   19,   20,   21,

       22,   23,   24,   25,   26,   27,   27,   28,   29,   30,
       31,   32,   27,   33,   34,   35,   36,   37,   27,   38,
       39,   27,   40,    1,   41,   42,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[43] =
    {   0,
        1,    1,    1,    1,    1,    1,    2,    1,    3,    4,
        4,    4,    5,    1,    6,    1,    2,    4,    4,    4,
        4,    4,    4,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    1,
        1,    1
    } ;

static yyconst short int yy_base[550] =
    {   0,
        0,    0,  985,  986,   41,   43,  970,   40,  970,  968,
       72,   91,   96,  110,   81,  103,   73,  105,  112,  117,
       93,   23,  119,  121,   64,  955,  146,   85,  986,    0,
      146,  177,  149,    0,  155,  971,  986,  986,  986,  162,
      966,  193,  144,   93,  946,  170,    0,  945,  155,  178,
      156,  958,  946,  954,  938,  941,  121,  936,  933,  962,
      947,  933,  947,  927,  175,    0,  932,  941,  933,  163,
      938,  928,  952,  930,  939,  926,  986,  986,  929,  206,
      219,  211,  222,  941,  215,  104,  233,  238,  927,    0,
        0,  944,  929,  240,  251,  932,  938,    0,  919,  912,

      911,  923,    0,  911,  921,  909,  912,  923,  907,  189,
      241,  912,    0,  905,  912,  900,  236,    0,  911,  900,
      925,  233,  907,  895,  903,  898,  252,  904,  891,  890,
      260,  265,  911,  269,  910,  909,  273,  277,    0,  281,
      255,  890,  142,  890,  281,  287,  288,  283,  884,  882,
      899,    0,  881,  883,  882,  906,    0,  892,  878,    0,
      902,  901,  874,  884,  874,  888,  883,  865,  884,  276,
        0,  879,  893,  868,  868,  873,  292,  304,  296,    0,
      870,   48,  312,  317,  321,  882,  881,  330,  299,  305,
      858,  862,  855,  860,  868,  318,  331,  854,  859,  321,

      852,  860,  854,  857,  860,  846,  332,  849,  849,  316,
      317,  853,  840,  844,  841,  845,  844,  842,  344,  851,
      848,  337,  349,  849,  331,  986,  353,  363,  366,  855,
      854,  853,  986,  373,  358,  373,    0,    0,    0,  837,
      838,    0,  829,  840,  380,  826,  838,  829,  851,    0,
      831,  826,    0,    0,  381,  382,  351,  821,  832,  817,
      822,  815,  820,  818,  826,  816,  833,  824,  386,  387,
      398,  813,    0,  809,  820,  807,  810,  986,  397,  400,
      826,  825,  406,  410,  411,  802,  816,  415,  813,  414,
      422,  801,  800,  808,  421,  796,  796,  418,  430,  794,

      793,  799,  800,  797,  798,  791,  789,  788,    0,  412,
      432,  792,  441,  797,  811,  782,  444,  803,  802,  801,
      447,  433,  451,    0,  787,  794,  454,  455,  778,  803,
      791,  801,  768,    0,  772,  777,  782,  986,    0,  768,
      782,  766,  780,  986,  764,  763,  763,  407,    0,  462,
      763,  462,  754,  466,  781,  780,  471,  472,  772,  757,
      476,  479,  772,  480,  755,  481,    0,  479,  753,  765,
      760,  767,  758,  765,  756,  986,  489,  759,  750,  761,
      487,  495,  986,  504,  765,  764,  763,  494,  497,    0,
      757,  739,  739,  759,  507,  738,  737,  749,  734,  747,

      732,  731,  511,  731,  739,  728,  986,  518,  713,  710,
      518,  523,  652,  986,  670,  656,  642,  632,  613,  627,
      608,  608,  609,  610,  602,  523,  599,  597,  577,  528,
      529,    0,  554,  488,  550,  549,  986,  545,  986,  986,
      534,  532,  533,  554,  543,  537,  538,  541,  546,  542,
      505,  491,  500,  545,  547,  457,  450,  449,  548,  556,
        0,  435,  405,  557,  404,  368,  561,  351,  565,  317,
      565,  265,  257,  575,  227,  206,  986,  581,  584,  587,
      986,  596,  599,  600,  603,  607,  612,  615,  617,  620,
      205,  624,  627,  628,  630,  633,  636,  640,  645,  648,

      650,  653,  179,  657,  660,  661,  663,  666,  669,  671,
      673,  676,  133,  680,  683,  684,  686,  689,  692,  694,
      696,  699,  106,  701,  703,  706,  709,  711,  713,  716,
       77,  720,  723,  724,  726,  729,  732,  734,  736,  739,
       45,  741,  744,  746,  749,  751,  753,  755,  757
    } ;

static yyconst short int yy_def[550] =
    {   0,
      481,    1,  481,  481,  481,  481,  481,  481,  481,  481,
        8,  481,    8,    8,   14,   14,   14,   14,   11,   11,
       11,   11,   11,   11,   11,  481,  481,  481,  481,   11,
      481,    8,  482,   11,   32,  483,  481,  481,  481,  481,
      482,   32,   42,   11,   11,   11,   11,   11,   42,   11,
       42,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,  481,  481,  481,  481,  481,
       32,   81,  484,  484,  481,  485,  481,   81,   11,   11,
       11,   11,   11,  486,   11,   11,   11,   11,   11,   11,

       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,  481,   11,   11,   11,
       11,   11,   11,   11,   11,   11,  487,   11,   11,  481,
      481,   11,   11,  488,  489,  488,  481,  490,  491,  481,
       11,   11,  481,   11,  486,  486,  492,  481,   11,   11,
       11,   11,   11,   11,   11,   11,   11,  481,   11,   11,
       11,   11,   11,   11,   11,   11,  481,  481,   11,   11,
       11,   11,   11,   11,   11,   11,  487,  487,  493,   11,
       11,  481,  481,   11,  494,  494,  495,  481,  496,  497,
       11,   11,  481,  481,   11,  481,  492,  481,  481,  481,

      481,   11,   11,   11,   11,   11,  498,  481,   11,  481,
      481,  481,  481,  481,   11,   11,   11,   11,  499,   11,
       11,  481,  493,   11,  481,  481,  481,  481,  481,  481,
      500,  501,  481,  481,  481,  502,  503,   11,   11,  481,
      481,   11,  481,  481,  481,  481,  481,  481,  481,   11,
       11,   11,   11,   11,  498,  498,  504,  481,   11,  481,
      481,  481,  481,  481,  481,  481,   11,   11,  499,  499,
      505,   11,   11,  481,  481,  481,  481,  481,  481,  481,
      506,  507,  481,  508,  509,  481,  481,  481,  481,  492,
      481,  481,  481,  481,  493,   11,   11,  481,  504,  481,

       11,  481,  481,  481,  481,  481,  481,  481,   11,  481,
      505,   11,  481,  481,  481,  481,  481,  481,  510,  511,
      481,  481,  512,  513,  481,  481,  514,  481,  481,  481,
      481,  481,   11,   11,  481,  481,  481,  481,   11,  481,
      481,  481,  481,  481,  481,  481,  481,  481,   11,  481,
      481,  515,  481,  481,  516,  517,  518,  519,  481,  481,
      514,  514,  481,  504,  481,  505,   11,  481,  481,  481,
      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,
      515,  515,  481,  481,  481,  520,  521,  481,  522,  523,
      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,

      481,  481,  481,  481,  481,  481,  481,  481,  524,  525,
      526,  527,  481,  481,  481,  481,  481,  481,  481,  481,
      481,  481,  481,  481,  481,  481,  481,  528,  529,  481,
      530,  531,  481,  532,  481,  481,  481,  481,  481,  481,
      481,  533,  481,  534,  535,  536,  537,  532,  532,  481,
      481,  481,  481,  533,  533,  481,  538,  539,  481,  540,
      541,  542,  543,  544,  545,  481,  481,  546,  481,  547,
      481,  548,  549,  481,  481,  481,  481,  481,  481,  481,
        0,  481,  481,  481,  481,  481,  481,  481,  481,  481,
      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,

      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,
      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,
      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,
      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,
      481,  481,  481,  481,  481,  481,  481,  481,  481
    } ;

static yyconst short int yy_nxt[1029] =
    {   0,
        4,    5,    6,    4,    4,    4,    4,    7,    4,    8,
        8,    8,    9,   10,   11,   12,    4,   13,   14,   15,
       16,   17,   18,   11,   11,   19,   11,   11,   20,   21,
       22,   23,   24,   25,   11,   11,   11,   11,   11,   26,
        4,   27,   28,   28,   28,   28,   30,   31,  465,   32,
       32,   32,   33,  225,   34,   66,   67,   35,   35,   35,
       35,   35,   35,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,  481,
      447,   34,   34,   34,  481,   74,   28,   28,  226,   34,
       34,   34,   34,   34,   34,   38,   34,   39,   75,   49,

       40,   40,   40,  481,   34,   35,   35,   35,   41,  412,
       54,   50,   85,   91,   64,   42,  139,  481,   43,   35,
       35,   35,   41,   65,   51,   44,   34,   45,   34,   46,
       47,   92,   55,   48,   52,   57,  358,   56,   61,   53,
       68,   58,   71,   59,   69,   60,   72,   62,   63,   77,
       78,   70,  108,  109,   73,   80,   80,   80,   83,   83,
       83,   36,  481,   82,   82,   82,   82,   41,   87,   90,
      193,   40,   40,   40,   82,   82,   94,  194,   34,   95,
       95,   95,  285,  102,  122,   79,   81,   81,   81,   98,
       34,  117,  123,  124,   82,   82,   82,   82,   82,   82,

      481,   96,   82,   82,   82,   41,   99,  100,  190,  118,
      159,  101,   88,  131,   85,   80,   80,   80,  481,  160,
      133,  133,  133,   41,  137,  137,  137,   89,  132,  132,
      132,  134,  134,  134,  135,  467,  133,  133,  133,  133,
      133,  133,  140,  140,  140,  481,  145,  133,  133,  133,
       41,  161,  162,  167,   34,  171,  147,  168,  177,  141,
       95,   95,   95,  148,  172,   85,   34,   41,  179,  183,
      183,  183,   31,  467,  184,  184,  184,   33,  185,  185,
      185,  135,  137,  137,  137,   85,  191,  145,  188,  139,
      140,  140,  140,  145,  147,   34,  216,  147,  177,  196,

      198,   34,  179,  147,  147,  199,   34,   85,  179,  217,
      177,  139,  179,   85,  200,  201,  222,  237,   34,  227,
      179,  183,  183,  183,   31,   85,  184,  184,  184,  228,
      229,  229,  229,  135,  233,  243,  233,  147,  255,  234,
      234,  234,  247,  196,  260,  262,   34,  147,  257,  244,
      269,  261,  263,  248,  274,  179,  277,  257,   34,  467,
      271,  222,  279,  279,  279,  179,   85,  257,  275,  276,
      139,  278,  280,  280,  280,  280,  280,  280,  135,  283,
      458,   85,  234,  234,  234,  237,  290,  255,  255,  291,
      291,  291,  269,  269,  298,   34,   34,  257,  257,  310,

       34,   34,  271,  271,  271,  317,  279,  279,  279,  280,
      280,  280,   85,  467,  271,  321,  321,  321,   85,   85,
      147,  327,  237,  324,  328,  328,  328,  179,  378,  347,
      147,  291,  291,  291,  148,  335,  257,  179,  271,  379,
      336,   85,  298,  348,  310,  237,  257,  458,  271,  337,
      350,  350,  350,  354,  354,  354,  321,  321,  321,   85,
      361,   36,  458,  324,  328,  328,  328,  196,  381,  429,
      361,  350,  350,  350,  222,  354,  354,  354,  381,   85,
       85,  384,  361,  324,  390,  361,  257,  271,  395,  395,
      395,  196,  361,  381,  448,  361,  257,  271,  403,  403,

      403,  381,   85,  381,  448,   85,  324,  222,  407,  390,
      407,  381,  310,  408,  408,  408,  395,  395,  395,  298,
      403,  403,  403,  310,  426,  439,   85,  408,  408,  408,
      390,   85,  443,  443,  443,  432,   85,   85,  454,  437,
      390,  432,  443,  443,  443,   85,   85,  448,  454,  432,
      461,  454,  448,  454,  298,  458,   85,  448,  298,  310,
      432,  454,  448,  454,   85,   85,  429,  453,  461,  461,
      471,  471,  471,   85,  471,  471,  471,  461,  452,  477,
      474,  477,  451,  450,  478,  478,  478,  479,  414,   36,
      478,  478,  478,  480,  480,  480,  480,  480,  480,   84,

       84,   86,   86,  136,  136,  138,  138,  138,  146,  429,
      146,  387,  146,  178,  222,  178,  442,  178,  186,  186,
      187,  187,  189,  189,  189,  197,  441,  197,  223,  440,
      223,  230,  230,  231,  231,  235,  235,  235,  236,  236,
      236,  256,  439,  256,  438,  256,  270,  437,  270,  436,
      270,  281,  281,  282,  282,  284,  284,  284,  299,  435,
      299,  311,  434,  311,  318,  318,  319,  319,  322,  322,
      322,  323,  323,  323,  355,  355,  356,  356,  357,  357,
      357,  362,  196,  362,  382,  433,  382,  385,  385,  386,
      386,  388,  388,  388,  389,  389,  389,  409,  409,  410,

      410,  411,  411,  411,  427,  427,  428,  428,  430,  430,
      430,  431,  431,  431,  444,  444,  445,  445,  446,  446,
      446,  449,  429,  449,  455,  387,  455,  456,  456,  457,
      457,  459,  459,  459,  460,  460,  460,  462,  462,  463,
      463,  464,  464,  464,  466,  466,  468,  468,  469,  469,
      469,  470,  470,  472,  472,  473,  473,  475,  475,  476,
      476,  425,  424,  423,  422,  421,  420,  419,  418,  417,
      416,  148,  415,  414,  413,   36,  387,  320,  406,  405,
      404,  402,  401,  400,  399,  398,  397,  396,  394,  393,
      392,  391,  387,  320,  383,  380,  377,  376,  375,  374,

      373,  372,  371,  370,  369,  368,  367,  366,  365,  364,
      363,  360,  359,   36,  320,  232,  353,  352,  351,  349,
      346,  345,  344,  343,  342,  341,  340,  339,  338,  334,
      333,  332,  331,  330,  329,  326,  325,  320,  232,  316,
      315,  314,  313,  312,  309,  148,  308,  307,  306,  305,
      304,  303,  302,  301,  300,  297,  296,  295,  294,  293,
      292,  289,  288,  287,  286,   36,  232,  135,   98,  273,
      272,  268,   98,   98,  267,  266,  265,  264,  259,  258,
      254,  253,  252,  251,  250,  249,  246,  245,  242,  241,
      240,  239,  238,  232,  135,  224,   98,  221,  220,  219,

      218,  215,  214,  213,  212,   98,   98,   98,  211,  210,
      209,  208,  207,  206,   98,  205,  204,  203,  202,  195,
      192,  135,   36,   41,  182,  181,  180,  176,  175,  174,
      173,  170,  169,   98,  166,  165,  164,  163,   98,  158,
      157,  156,  155,  154,  153,  152,  151,  150,   98,  149,
      144,  143,  142,  135,   76,  130,  129,  128,  127,  126,
      125,  121,  120,  119,  116,  115,  114,  113,  112,  111,
      110,  107,  106,  105,  104,  103,   97,   93,   36,   85,
       76,   37,   36,   29,  481,    3,  481,  481,  481,  481,
      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,

      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,
      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,
      481,  481,  481,  481,  481,  481,  481,  481
    } ;

static yyconst short int yy_chk[1029] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    5,    5,    6,    6,    8,    8,  541,    8,
        8,    8,    8,  182,    8,   22,   22,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,   11,
      531,   11,   11,   11,   11,   25,   28,   28,  182,   11,
       11,   11,   11,   11,   11,   12,   17,   12,   25,   15,

       12,   12,   12,   13,   15,   13,   13,   13,   13,  523,
       17,   15,   86,   44,   21,   13,   86,   14,   13,   14,
       14,   14,   14,   21,   16,   13,   16,   13,   18,   13,
       13,   44,   18,   14,   16,   19,  513,   18,   20,   16,
       23,   19,   24,   19,   23,   19,   24,   20,   20,   27,
       27,   23,   57,   57,   24,   31,   31,   31,   33,   33,
       33,   33,   35,   43,   35,   35,   35,   35,   40,   43,
      143,   40,   40,   40,   49,   51,   46,  143,   43,   46,
       46,   46,  503,   51,   70,   27,   32,   32,   32,   49,
       51,   65,   70,   70,   32,   32,   32,   32,   32,   32,

       42,   46,   42,   42,   42,   42,   50,   50,  491,   65,
      110,   50,   42,   80,  476,   80,   80,   80,   82,  110,
       82,   82,   82,   82,   85,   85,   85,   42,   81,   81,
       81,   83,   83,   83,   83,  475,   81,   81,   81,   81,
       81,   81,   87,   87,   87,   88,   94,   88,   88,   88,
       88,  111,  111,  117,   94,  122,   94,  117,  127,   88,
       95,   95,   95,   95,  122,  473,  127,  141,  127,  131,
      131,  131,  132,  472,  132,  132,  132,  132,  134,  134,
      134,  134,  137,  137,  137,  138,  141,  145,  137,  138,
      140,  140,  140,  146,  147,  145,  170,  145,  177,  146,

      148,  146,  179,  146,  147,  148,  177,  189,  177,  170,
      178,  189,  179,  190,  148,  148,  178,  190,  178,  183,
      178,  183,  183,  183,  184,  470,  184,  184,  184,  184,
      185,  185,  185,  185,  188,  196,  188,  197,  207,  188,
      188,  188,  200,  197,  210,  211,  207,  197,  207,  196,
      219,  210,  211,  200,  222,  223,  225,  257,  219,  468,
      219,  223,  227,  227,  227,  223,  235,  257,  222,  222,
      235,  225,  228,  228,  228,  229,  229,  229,  229,  234,
      466,  236,  234,  234,  234,  236,  245,  255,  256,  245,
      245,  245,  269,  270,  256,  255,  256,  255,  256,  270,

      269,  270,  269,  270,  271,  279,  279,  279,  279,  280,
      280,  280,  465,  463,  271,  283,  283,  283,  284,  285,
      290,  288,  284,  285,  288,  288,  288,  295,  348,  310,
      290,  291,  291,  291,  291,  298,  299,  295,  311,  348,
      298,  322,  299,  310,  311,  322,  299,  462,  311,  298,
      313,  313,  313,  317,  317,  317,  321,  321,  321,  323,
      327,  458,  457,  323,  328,  328,  328,  328,  352,  456,
      327,  350,  350,  350,  350,  354,  354,  354,  352,  357,
      358,  354,  361,  357,  358,  362,  364,  366,  368,  368,
      368,  362,  361,  381,  434,  362,  364,  366,  377,  377,

      377,  382,  388,  381,  434,  389,  388,  382,  384,  389,
      384,  382,  453,  384,  384,  384,  395,  395,  395,  395,
      403,  403,  403,  403,  408,  452,  411,  408,  408,  408,
      411,  412,  426,  426,  426,  412,  430,  431,  442,  451,
      430,  431,  443,  443,  443,  446,  447,  448,  442,  446,
      447,  454,  449,  455,  450,  445,  459,  448,  449,  455,
      459,  454,  449,  455,  460,  464,  444,  441,  460,  464,
      467,  467,  467,  469,  471,  471,  471,  469,  438,  474,
      471,  474,  436,  435,  474,  474,  474,  478,  433,  429,
      478,  478,  478,  479,  479,  479,  480,  480,  480,  482,

      482,  483,  483,  484,  484,  485,  485,  485,  486,  428,
      486,  427,  486,  487,  425,  487,  424,  487,  488,  488,
      489,  489,  490,  490,  490,  492,  423,  492,  493,  422,
      493,  494,  494,  495,  495,  496,  496,  496,  497,  497,
      497,  498,  421,  498,  420,  498,  499,  419,  499,  418,
      499,  500,  500,  501,  501,  502,  502,  502,  504,  417,
      504,  505,  416,  505,  506,  506,  507,  507,  508,  508,
      508,  509,  509,  509,  510,  510,  511,  511,  512,  512,
      512,  514,  415,  514,  515,  413,  515,  516,  516,  517,
      517,  518,  518,  518,  519,  519,  519,  520,  520,  521,

      521,  522,  522,  522,  524,  524,  525,  525,  526,  526,
      526,  527,  527,  527,  528,  528,  529,  529,  530,  530,
      530,  532,  410,  532,  533,  409,  533,  534,  534,  535,
      535,  536,  536,  536,  537,  537,  537,  538,  538,  539,
      539,  540,  540,  540,  542,  542,  543,  543,  544,  544,
      544,  545,  545,  546,  546,  547,  547,  548,  548,  549,
      549,  406,  405,  404,  402,  401,  400,  399,  398,  397,
      396,  394,  393,  392,  391,  387,  386,  385,  380,  379,
      378,  375,  374,  373,  372,  371,  370,  369,  365,  363,
      360,  359,  356,  355,  353,  351,  347,  346,  345,  343,

      342,  341,  340,  337,  336,  335,  333,  332,  331,  330,
      329,  326,  325,  320,  319,  318,  316,  315,  314,  312,
      308,  307,  306,  305,  304,  303,  302,  301,  300,  297,
      296,  294,  293,  292,  289,  287,  286,  282,  281,  277,
      276,  275,  274,  272,  268,  267,  266,  265,  264,  263,
      262,  261,  260,  259,  258,  252,  251,  249,  248,  247,
      246,  244,  243,  241,  240,  232,  231,  230,  224,  221,
      220,  218,  217,  216,  215,  214,  213,  212,  209,  208,
      206,  205,  204,  203,  202,  201,  199,  198,  195,  194,
      193,  192,  191,  187,  186,  181,  176,  175,  174,  173,

      172,  169,  168,  167,  166,  165,  164,  163,  162,  161,
      159,  158,  156,  155,  154,  153,  151,  150,  149,  144,
      142,  136,  135,  133,  130,  129,  128,  126,  125,  124,
      123,  121,  120,  119,  116,  115,  114,  112,  109,  108,
      107,  106,  105,  104,  102,  101,  100,   99,   97,   96,
       93,   92,   89,   84,   79,   76,   75,   74,   73,   72,
       71,   69,   68,   67,   64,   63,   62,   61,   60,   59,
       58,   56,   55,   54,   53,   52,   48,   45,   41,   36,
       26,   10,    9,    7,    3,  481,  481,  481,  481,  481,
      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,

      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,
      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,
      481,  481,  481,  481,  481,  481,  481,  481
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "mp_import.l"
#define INITIAL 0
#line 2 "mp_import.l"
/*
  filename: mp_import.l

  description:
    Defines the tokenizer for an RPSLng mp-import attribute. Derived from
    import.l. 

  notes:
    Tokens are defined in the associated grammar, mp_import.y.

  $Id: mp_import.l,v 1.1 2004/12/27 17:52:39 can Exp $
*/
#line 42 "mp_import.l"
#include <string.h>
#include <stdlib.h>
#include <ctype.h>

/* tokens defined in the grammar */
#include "mp_import.tab.h"

#define mp_importwrap yywrap
void syntax_error(char *fmt, ...);
void yy_input(char *buf, int *result, int max_size);
#undef YY_INPUT
#define YY_INPUT(buf,result,max_size) yy_input(buf,&result,max_size)
#define YY_NO_UNPUT  /* otherwise we get compiler warnings "`yyunput' defined but not used" */

#line 808 "mp_import.lex.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 58 "mp_import.l"


#line 962 "mp_import.lex.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 482 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 986 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 60 "mp_import.l"
{ ; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 62 "mp_import.l"
{ return OP_OR; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 63 "mp_import.l"
{ return OP_AND; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 64 "mp_import.l"
{ return OP_NOT; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 65 "mp_import.l"
{ return OP_COMPARE; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 66 "mp_import.l"
{ return OP_EQUAL; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 67 "mp_import.l"
{ return OP_APPEND; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 69 "mp_import.l"
{ return OP_MS; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 70 "mp_import.l"
{ return OP_MS; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 71 "mp_import.l"
{ 
    long int val;
    val = strtol(yytext+1, NULL, 10);
    if ((val < 0) || (val > 32)) {
        syntax_error("more specifics operator \"%s\" not 0 to 32 bits", 
                     yytext);
    }
    return OP_MS;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 80 "mp_import.l"
{
    long int val1, val2;
    char *p;
    val1 = strtol(yytext+1, &p, 10);
    if ((val1 < 0) || (val1 > 32)) {
        syntax_error("more specifics operator \"%s\" not 0 to 32 bits", 
                     yytext);
    }
    val2 = strtol(p+1, NULL, 10);
    if ((val2 < 0) || (val2 > 32)) {
        syntax_error("more specifics operator \"%s\" not 0 to 32 bits", 
                     yytext);
    }
    if (val2 < val1) {
        syntax_error("more specifics operator \"%s\" not 0 to 32 bits", 
                     yytext);
    }
    return OP_MS;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 101 "mp_import.l"
{ return KEYW_ANY; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 102 "mp_import.l"
{ return KEYW_PEERAS; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 104 "mp_import.l"
{ return KEYW_FROM; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 105 "mp_import.l"
{ return KEYW_ACTION; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 106 "mp_import.l"
{ return KEYW_IGP_COST; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 107 "mp_import.l"
{ return KEYW_SELF; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 108 "mp_import.l"
{ return KEYW_PREPEND; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 109 "mp_import.l"
{ return KEYW_APPEND; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 110 "mp_import.l"
{ return KEYW_DELETE; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 111 "mp_import.l"
{ return KEYW_CONTAINS; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 112 "mp_import.l"
{ return KEYW_ACCEPT; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 114 "mp_import.l"
{ return KEYW_INTERNET; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 115 "mp_import.l"
{ return KEYW_NO_EXPORT; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 116 "mp_import.l"
{ return KEYW_NO_ADVERTISE; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 118 "mp_import.l"
{ return KEYW_AT; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 119 "mp_import.l"
{ return KEYW_PROTOCOL; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 120 "mp_import.l"
{ return KEYW_INTO; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 121 "mp_import.l"
{ return KEYW_REFINE; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 122 "mp_import.l"
{ return KEYW_EXCEPT; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 124 "mp_import.l"
{ return TKN_PROTOCOL; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 126 "mp_import.l"
{ return KEYW_AFI; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 128 "mp_import.l"
{ return KEYW_AFI_VALUE_V4; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 129 "mp_import.l"
{ return KEYW_AFI_VALUE_V6; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 130 "mp_import.l"
{ return KEYW_AFI_VALUE_ANY; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 132 "mp_import.l"
{ return TKN_PREF; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 133 "mp_import.l"
{ return TKN_MED; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 134 "mp_import.l"
{ return TKN_DPA; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 135 "mp_import.l"
{ return TKN_ASPATH; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 136 "mp_import.l"
{ return TKN_COMMUNITY; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 137 "mp_import.l"
{ return TKN_NEXT_HOP; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 138 "mp_import.l"
{ return TKN_COST; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 140 "mp_import.l"
{ return ASPATH_POSTFIX; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 141 "mp_import.l"
{ return ASPATH_POSTFIX; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 142 "mp_import.l"
{ return ASPATH_POSTFIX; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 143 "mp_import.l"
{ return ASPATH_POSTFIX; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 144 "mp_import.l"
{ return ASPATH_POSTFIX; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 146 "mp_import.l"
{
    long int val;
    char *s;
    val = strtol(yytext+2, &s, 10);
    if ((val < 0) || (val > 65535) || (*s != '\0')) {
        syntax_error("AS number \"%s\" is not between 0 and 65535", yytext);
    }
    return TKN_ASNO;
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 156 "mp_import.l"
{
    return TKN_FLTRNAME;
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 160 "mp_import.l"
{
    return TKN_ASNAME;
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 164 "mp_import.l"
{
    return TKN_RSNAME;
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 168 "mp_import.l"
{ 
    return TKN_PRNGNAME;
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 172 "mp_import.l"
{
    /* check each number of 1.2.3.4/5 in prefix is valid, as
       well as any bit ranges specified */
    long int val;
    long int endval;
    char *s, *p;
    p = s = yytext;
    while (*s != '/') {
        val = strtol(p, &s, 10);
        if ((val < 0) || (val > 255)) {
             syntax_error("IP prefix \"%s\" contains an invalid octet", 
                          yytext);
        }
        p = s + 1;
    }
    val = strtol(p, &s, 10);
    if ((val < 0) || (val > 32)) {
        syntax_error("IP prefix range \"%s\" contains an invalid prefix length",
                     yytext);
    }
    p = s + 1;
    if (isdigit((int)*p)) {
        val = strtol(p, &s, 10);
        if ((val < 0) || (val > 32)) {
            syntax_error("IP prefix range \"%s\" contains an invalid range",
                         yytext);
        }
        p = s + 1;
        if (isdigit((int)*p)) {
            endval = strtol(p, NULL, 10);
            if ((endval < 0) || (endval > 32)) {
                syntax_error("IP prefix \"%s\" contains an invalid prefix range", 
                             yytext);
            }
            if (endval < val) {
                syntax_error("IP prefix \"%s\" range end is less than range start",
                             yytext);
            }
        }
    }
    return TKN_PRFXV4RNG;
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 215 "mp_import.l"
{
    /* check each quad of 1A:3:7:8:AAAA:BBBB:DEAD:BEEF/55 in prefix is valid, as
       well as any bit ranges specified */
    long int val;
    long int endval;
    char *s, *p;
    p = s = yytext;
    while (*s != '/') {
        val = strtol(p, &s, 16);
        if ((val < 0) || (val > 65535)) {
             syntax_error("IPv6 prefix \"%s\" contains an invalid quad",
                          yytext);
        }
        p = s + 1;
    }
    val = strtol(p, &s, 10);
    if ((val < 0) || (val > 128)) {
        syntax_error("IPv6 prefix range \"%s\" contains an invalid prefix length",
                     yytext);
    }
    p = s + 1;
    if (isdigit((int)*p)) {
        val = strtol(p, &s, 10);
        if ((val < 0) || (val > 128)) {
            syntax_error("IPv6 prefix range \"%s\" contains an invalid range",
                         yytext);
        }
        p = s + 1;
        if (isdigit((int)*p)) {
            endval = strtol(p, NULL, 10);
            if ((endval < 0) || (endval > 128)) {
                syntax_error("IPv6 prefix \"%s\" contains an invalid prefix range",
                             yytext);
            }
            if (endval < val) {
                syntax_error("IPv6 prefix \"%s\" range end is less than range start",
                             yytext);
            }
        }
    }
    return TKN_PRFXV6RNG;
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 258 "mp_import.l"
{
    /* check each quad of 1A:3:7:8:AAAA:BBBB:DEAD:BEEF/55 in prefix is valid, as
       well as any bit ranges specified */
    long int val;
    long int endval;
    char *s, *p, *r;
    int leftquads = 0;
    int rightquads = 0;

    p = s = yytext;
    while (*s != '/') {
        val = strtol(p, &s, 16);
        if ((val < 0) || (val > 65535)) {
             syntax_error("IPv6 prefix \"%s\" contains an invalid quad",
                          yytext);
        }
        p = s + 1;
    }
    val = strtol(p, &s, 10);
    if ((val < 0) || (val > 128)) {
        syntax_error("IPv6 prefix range \"%s\" contains an invalid prefix length",
                     yytext);
    }
    p = s + 1;
    if (isdigit((int)*p)) {
        val = strtol(p, &s, 10);
        if ((val < 0) || (val > 128)) {
            syntax_error("IPv6 prefix range \"%s\" contains an invalid range",
                         yytext);
        }
        p = s + 1;
        if (isdigit((int)*p)) {
            endval = strtol(p, NULL, 10);
            if ((endval < 0) || (endval > 128)) {
                syntax_error("IPv6 prefix \"%s\" contains an invalid prefix range",
                             yytext);
            }
            if (endval < val) {
                syntax_error("IPv6 prefix \"%s\" range end is less than range start",
                             yytext);
            }
        }
    }

    /* And now, count colons to the left of "::" - this is
       one less than the number of left quads */

    r = strchr(yytext, ':');
    leftquads++;
    while (r[1] != ':') {
        leftquads++;
        r = strchr(r+1, ':');
    }
    /* skip "::" */
    r += 2;
    /* count colons to the right of "::" - one less than the number of right quads */
    if (r[0] != '\0') {
        do {
            rightquads++;
            r = strchr(r+1, ':');
        } while (r != NULL);
    }
    /* check for too many quads */
    if ((leftquads + rightquads) > 8) {
        syntax_error("IPv6 address \"%s\" contains too many digits", yytext);
    }

    return TKN_PRFXV6DCRNG;
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 328 "mp_import.l"
{
    /* check each number of 1.2.3.4/5 in prefix is valid */
    long int val;
    char *s, *p;
    p = s = yytext;
    while (*s != '/') {
        val = strtol(p, &s, 10);
        if ((val < 0) || (val > 255)) {
             syntax_error("IP prefix \"%s\" contains an invalid octet", 
                          yytext);
        }
        p = s + 1;
    }
    val = strtol(p, NULL, 10);
    if ((val < 0) || (val > 32)) {
        syntax_error("IP prefix \"%s\" contains an invalid prefix length", 
                     yytext);
    }
    return TKN_PRFXV4;
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 349 "mp_import.l"
{
    /* check each quad of 1A:3:7:8:AAAA:BBBB:DEAD:BEEF/55 in prefix is valid */
    long int val;
    char *s, *p;
    p = s = yytext;
    while (*s != '/') {
        val = strtol(p, &s, 16);
        if ((val < 0) || (val > 65535)) {
             syntax_error("IPv6 prefix \"%s\" contains an invalid quad",
                          yytext);
        }
        p = s + 1;
    }
    val = strtol(p, NULL, 10);
    if ((val < 0) || (val > 128)) {
        syntax_error("IPv6 prefix \"%s\" contains an invalid prefix length",
                     yytext);
    }
    return TKN_PRFXV6;
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 370 "mp_import.l"
{
    /* check each quad of 1A::AAAA:BBBB:DEAD:BEEF/55 in prefix is valid */
    long int val;
    char *s, *p, *r;
    int leftquads = 0;
    int rightquads = 0;

    r = p = s = yytext;
    while (*s != '/') {
        val = strtol(p, &s, 16);
        if ((val < 0) || (val > 65535)) {
             syntax_error("IPv6 prefix \"%s\" contains an invalid quad",
                          yytext);
        }
        p = s + 1;
    }
    val = strtol(p, NULL, 10);
    if ((val < 0) || (val > 128)) {
        syntax_error("IPv6 prefix \"%s\" contains an invalid prefix length",
                     yytext);
    }

    /* And now, count colons to the left of "::" - this is
       one less then the number of left quads */

    r = strchr(yytext, ':');
    leftquads++;
    while (r[1] != ':') {
        leftquads++;
        r = strchr(r+1, ':');
    }
    /* skip "::" */
    r += 2;
    /* count colons to the right of "::" - one less then the number of right quads */
    if (r[0] != '\0') {
        do {
            rightquads++;
            r = strchr(r+1, ':');
        } while (r != NULL);
    }
    /* check for too many quads */
    if ((leftquads + rightquads) > 8) {
        syntax_error("IPv6 address \"%s\" contains too many digits", yytext);
    }

    return TKN_PRFXV6DC;
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 418 "mp_import.l"
{
    /* check each number of 1.2.3.4 is valid */
    long int val;
    char *s, *p;
    p = s = yytext;
    while (*s != '\0') {
        val = strtol(p, &s, 10);
        if ((val < 0) || (val > 255)) {
             syntax_error("IP address \"%s\" contains an invalid octet", 
                          yytext);
        }
        p = s + 1;
    }
    return TKN_IPV4;
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 434 "mp_import.l"
{
    /* check each quad of 1A:3:7:8:AAAA:BBBB:DEAD:BEEF in address is valid */
    long int val;
    char *s, *p;
    p = s = yytext;
    while (*s != '\0') {
        val = strtol(p, &s, 16);
        if ((val < 0) || (val > 65535)) {
             syntax_error("IPv6 address \"%s\" contains an invalid quad",
                          yytext);
        }
        p = s + 1;
    }
    return TKN_IPV6;
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 450 "mp_import.l"
{
    /* check each quad of 1A::AAAA:BBBB:DEAD:BEEF in address is valid */
    long int val;
    char *s, *p, *r;
    int leftquads = 0;
    int rightquads = 0;

    r = p = s = yytext;
    while (*s != '\0') {
        val = strtol(p, &s, 16);
        if ((val < 0) || (val > 65535)) {
             syntax_error("IPv6 address \"%s\" contains an invalid quad",
                          yytext);
        }
        p = s + 1;
    }
    /* And now, count colons to the left of "::" - this is
       one less then the number of left quads */

    r = strchr(yytext, ':');
    leftquads++;
    while (r[1] != ':') {
        leftquads++;
        r = strchr(r+1, ':');
    }
    /* skip "::" */
    r += 2;
    /* count colons to the right of "::" - one less then the number of right quads */
    if (r[0] != '\0') {
        do {
            rightquads++;
            r = strchr(r+1, ':');
        } while (r != NULL);
    }
    /* check for too many quads */
    if ((leftquads + rightquads) > 8) {
        syntax_error("IPv6 address \"%s\" contains too many digits", yytext);
    }

    return TKN_IPV6DC;
}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 492 "mp_import.l"
{
    /* verify each part is a 16-bit number */
    long int val;
    char *s, *p;
    p = s = yytext;
    while (*s != '\0') {
        val = strtol(p, &s, 10);
        if ((val < 0) || (val > 65535)) {
             syntax_error("Community number \"%s\" contains an invalid number", 
                           yytext);
        }
        p = s + 1;
    }
    return TKN_COMM_NO;
}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 508 "mp_import.l"
{ 
    mp_importlval.sval = yytext;
    return TKN_INT; 
}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 513 "mp_import.l"
{ 
    /* check the length */
    if (strlen(yytext) > 63) {
       syntax_error("Portion of domain name \"%s\" is longer "
                                                           "than 63 characters",
                    yytext); 
    }
    mp_importlval.sval = yytext;
    return TKN_DNS; 
}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 524 "mp_import.l"
{ return yytext[0]; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 526 "mp_import.l"
ECHO;
	YY_BREAK
#line 1745 "mp_import.lex.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 482 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 482 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 481);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 526 "mp_import.l"


void 
mp_import_reset ()
{
    yy_flush_buffer(YY_CURRENT_BUFFER);
}

